### PR TITLE
Lua: highlight function name

### PR DESCRIPTION
**Pull request by stsewd**

### CODE REVIEW

**Comment by TravonteD** [comment]
+1 for making function...end keywords. definition words are highlighted as keywords in most of the other languages.

**Comment by stsewd** [comment]
Yeah, I found it weird too, I'll change those to be keywords

**Comment by theHamsta** [comment]
You could also add a new highlight for that. It's actually a good feature that some of the end in Lua have a different color.

**Comment by kyazdani42** [comment]
i find it very disturbing to have different colors for end statements though. As per kernel guidelines, too much indentation is not great code basically so you shouldn't have too many nested `end` statements in your code :)

**Comment by kyazdani42** [comment]
it depends though, i really hate colored brackets but some people like them so this is more a matter of preference. Maybe having a highlight group could be actually be good.

**Comment by theHamsta** [comment]
But it was only the function end that was highlighted differently: good for visualizing the bounds of closures.

**Comment by stsewd** [comment]
I have added a new highlight group for keywords that define a function.

**Comment by vigoux** [comment]
I would rather like having `@keyword.function` because it is a `keyword` after all. Can you change that ?

**Pull request merged**
