### PR TITLE
Allow arbitrary query files in locals.lua

### PR DESCRIPTION
**Pull request by theHamsta**
This is a preparation for `textobject` queries. Maybe a bit easier to review #100 in smaller pieces.

### CODE REVIEW

**Comment by vigoux** [comment]
I don't really understand what you mean by `locals_kind` here, do you mean `scope` and such or am I misled ?

**Comment by theHamsta** [comment]
The kind of query files we are caching. Locals is using `locals.scm`. The textobjects module uses the same infrastructure for `textobjects.scm`. Users can create their own collection of queries if the want to.

**Comment by vigoux** [comment]
But that's not locals then ?

**Comment by vigoux** [comment]
> Edit: maybe query_type is a better name?

My question in more : why using `locals` instead of `query`, locals are really meant to extract "semantic" information from the syntax tree, why not refactoring this into something separate ?

**Comment by theHamsta** [comment]
You mean renaming `locals.lua`? It keeps its original functionality and API stays the same. No functionality is added.

Everything in `locals.lua` is about getting semantic regions from the current buffer, so its also needed for textobjects (even though its rather an internal detail instead of a change for user API)

**Comment by vigoux** [comment]
As you want, let's take that modification in for now, I'll do a refactor later anyway to add the `is?` predicate.

**Comment by theHamsta** [comment]
You were right! Probably, all the stuff that is shared with textobjects should go to a own lua file and scope/definition/reference functionality from `ts_utils` should go `locals.lua`

**Comment by vigoux** [comment]
That's what I am planning to do soon, no worry, hopefully I can get that out later next week

**Pull request merged**
