### PR TITLE
fix(zig): Do not indent on newline after block

### PR DESCRIPTION
**Pull request by phynalle**
An additional indentaion on newline is appended.

This PR fixes a bug that an additional indentaion on newline is appended.

Current Behaviour is 
```
}<cursor>

to

}
<indent><cursor>
```

But expected behaviour should be below
```
}<cursor>

to

}
<cursor>
```

### CODE REVIEW

**Review by theHamsta — CHANGES_REQUESTED** [review]
Can you add a test please? Copy `tests/indent/go_spec.lua` to`tests/indent/zig_spec.lua` and put a test file in a zig folder.

**Comment by phynalle** [comment]
I have added it

**Review by theHamsta — APPROVED** [review]
Thank you :heart: !

**Comment by phynalle** [comment]
oops I missed a commit which enables expandtab

**Pull request merged**
