### PR TITLE
highlights(sql): change table_expression to table_reference

### PR DESCRIPTION
**Pull request by matthias-Q**
The node name `table_expression` has been refactored and renamed into `table_reference` in [here](https://github.com/DerekStride/tree-sitter-sql/commit/b032eaa5122e70cd4b012e2272eb357e1971ddc7).
Therefore, the queries for highlighting do not work anymore. They break with the following message:

```
ERROR 2022-09-07T07:56:07.092 2000835 decor_provider_invoke:37: error in provider treesitter/highlighter:line: Error executing lua: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: error at position 257
stack traceback:
        [C]: in function '_ts_parse_query'
        /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: in function 'get_query'
        ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:122: in function 'new'
        ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:247: in function 'get_query'
        ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:265: in function 'fn'
        ...l/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:194: in function 'for_each_tree'
        ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:255: in function 'on_line_impl'
        ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:303: in function <...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:299>
```

I have changed the query accordingly. However it fails to match on the second query:
```
(table_reference
  name: (identifier) @type
  table_alias: (identifier) @variable)
```

I am still quite fresh in the tree-sitter world. Could you take another look?.

### CODE REVIEW

**Comment by matthias-Q** [comment]
This seems to work, but I don't know if it yields the correct results.

```
(relation
  (table_reference
    name: (identifier) @type)
  table_alias: (identifier) @variable)

```

**Comment by clason** [comment]
Does the update work with the current tip of the parser repo? If so, you could include the lockfile bump (and drop the unrelated commit; just rebase on master).

**Comment by clason** [comment]
> This morning I rebased to the current master of nvim-treesitter

Did you actually rebase, or merge master into your PR branch?

**Comment by clason** [comment]
But no worries, I'll fix it.

**Comment by matthias-Q** [comment]
Ok thanks, I am taking my hands of the keyboard now before I do more damage :smile: Thanks a lot.

**Review by clason — APPROVED** [review]

**Comment by clason** [comment]
No worries, all good! Thanks for fixing this (twice)!

**Pull request merged**
