### PR TITLE
fix: don't overwrite highlights when defining

### PR DESCRIPTION
**Pull request by vigoux**
This is just being a good citizen for people that already define highlights :wink:

### CODE REVIEW

**Comment by clason** [comment]
Actually, we should remove all that since Nvim 0.8 is released with the new capture groups...

**Comment by vigoux** [comment]
Well maybe we should keep that but hide it behind a `has` call?

**Comment by clason** [comment]
I don't think so. We only support the latest release version (0.8) and the latest commit on master.

**Review by clason — APPROVED** [review]

**Comment by clason** [comment]
Shouldn't block this simple fix, though.

**Pull request merged**
