### PR TITLE
Python walrus

### PR DESCRIPTION
**Pull request by theHamsta**
- Add ":=" operator (also to upstream https://github.com/tree-sitter/tree-sitter-python/pull/72)
-  Reset highlighting in f-string interpolation
       This solution is preferable to `(identifier) @Normal` #72 since otherwise
       everything without highlight will use string-highlighting (`(identifier) @Normal` solves this only for identifier).

### CODE REVIEW

**Comment by theHamsta** [comment]
Not that I deactivated the highlighting of brackets in my config to use `rainbow_parenthesis`. So brackets have no highlight and should have the default highlighting. The "{" interpolation curly braces still have a highlighting group since they have another query. So the should be highlighted.

Before:

image

After:
image

**Comment by vigoux** [comment]
Can we try using this as an example in the README ?

**Comment by theHamsta** [comment]
As an example for what?

**Comment by vigoux** [comment]
I think that we can show some things any way, otherwise I will try we an example in C or Rust, chich changed quite a lot

**Comment by theHamsta** [comment]
Apparently me memory was bad:
image

With treesitter:
![image](https://user-images.githubusercontent.com/7189118/85690675-17646980-b6d4-11ea-9995-3f2f3d168b51.png

All the intelligent syntax highlighting was done by the Semshi plugin that I used before.

**Comment by vigoux** [comment]
Coool ! Can you add that to the README ?

**Comment by theHamsta** [comment]
There's a reason why we don't use C++:
image
Problem is somewhere in the lua code performing the regexes.

**Comment by vigoux** [comment]
Does it happen each time or after some editing ?

**Comment by theHamsta** [comment]
On some files, without editing. But I only observe it after the runtime update. The messages clearly point to some Lua regex handling code.

**Comment by vigoux** [comment]
Can you raise an issue for that ? With some minimal reproducing steps, and ping me in this, I will dig into this.

**Comment by kyazdani42** [comment]
i'm pretty sure this is still the same issue related to buffer updates, highlighting is not yet stable at all, editing code with it doesn't work, it happens in any language when you operate with `~` or `r`

**Comment by vigoux** [comment]
> i'm pretty sure this is still the same issue related to buffer updates, highlighting is not yet stable at all, editing code with it doesn't work, it happens in any language when you operate with `~` or `r`

If it happens without edits, then I am pretty sure it is not related to that

**Comment by kyazdani42** [comment]
I read wrong sorry

**Comment by theHamsta** [comment]
I think this can be merged. Screenshots can go to separate PR.

**Comment by theHamsta** [comment]
I fixed the cpp queries: #112

**Pull request merged**
