### PR TITLE
feat: add ungrammar

### PR DESCRIPTION
**Pull request by Philipp-M**
Adds support for [ungrammar](https://github.com/rust-analyzer/ungrammar)

### CODE REVIEW

**Comment by amaanq** [comment]
I'd like to propose some changes, namely porting what I've changed in this [PR](https://github.com/Philipp-M/tree-sitter-ungrammar/pull/1). Happy to co-maintain this with you as well :)

**Comment by amaanq** [comment]
Mind adding me as a maintainer? Just drop my handle after yours in parsers.lua and the readme

**Comment by Philipp-M** [comment]
Should already be in there?

**Comment by amaanq** [comment]
> Should already be in there?

Pfft, really sorry I didn't refresh my browser after the changes came through.

Side note, I'll update yuck soon as well :)

**Review by theHamsta — APPROVED** [review]
Looks great! Thank you!

**Comment by amaanq** [comment]
@Philipp-M can you rebase and update so CI passes? I'll merge this once CI passes. I somewhat broke smali in the middle of this, oops..

**Pull request merged**
