### PR TITLE
feat(http): update parser queries from upstream

### PR DESCRIPTION
**Pull request by amaanq**
Would've hoped someone else would've fixed it by now..

### CODE REVIEW

**Comment by clason** [comment]
Go ahead and remove the maintainer then.

**Comment by amaanq** [comment]
Sorry for the delay in fixing this..sooo busy w/ end of semester stuff :grin:

**Comment by clason** [comment]
No worries, this isn't really your job.

**Comment by amaanq** [comment]
I have no issues maintaining practically every parser (it's really a fun hobby for me), but sometimes I won't be there right away

**Comment by clason** [comment]
Yeah, but that scales really badly, and is not sustainable in the long run. I worry about setting wrong expectations.

**Review by clason — APPROVED** [review]

**Pull request merged**
