### PR TITLE
Update Julia queries

### PR DESCRIPTION
**Pull request by savq**
See https://github.com/tree-sitter/tree-sitter-julia/pull/106

### CODE REVIEW

**Comment by lucario387** [comment]
This also requires a change in `lockfile.json`

**Comment by clason** [comment]
@savq looks like the PR got changed before merging?

**Review by clason — APPROVED** [review]

**Comment by savq** [comment]
Yeah, sorry. I wasn't sure on whether to add more to the PR or create a new PR altogether. It was kind of a messy PR anyways. The last commits didn't change anything public tho.

**Comment by clason** [comment]
Yes just needed to update the lock file; no worries!

**Pull request merged**
