### PR TITLE
feat: make installation message a bit more verbose and informative

### PR DESCRIPTION
**Pull request by wookayin**
- Display the URL of parser being downloaded (includes parser revision)
- Display the temporary directory for extracting archive files

These should be informative information for troubleshooting and
debugging TS parsers being installed.

### Example output

```
│[nvim-treesitter] [0/1] Downloading tree-sitter-gitcommit (7e3ad5fdc61cd701e146ef78e4fc6dcdf6dbca0e) ...
│[nvim-treesitter] [0/1] Creating temporary directory: $HOME/.local/share/nvim/tree-sitter-gitcommit-tmp
│[nvim-treesitter] [0/1] Extracting tree-sitter-gitcommit ...
│[nvim-treesitter] [0/1] Compiling...
│[nvim-treesitter] [1/1] Treesitter parser for gitcommit has been installed
```

### CODE REVIEW

**Comment by wookayin** [comment]
Example output:
```
│[nvim-treesitter] [0/1] Downloading tree-sitter-gitcommit (7e3ad5fdc61cd701e146ef78e4fc6dcdf6dbca0e) ...
│[nvim-treesitter] [0/1] Creating temporary directory: $HOME/.local/share/nvim/tree-sitter-gitcommit-tmp
│[nvim-treesitter] [0/1] Extracting tree-sitter-gitcommit ...
│[nvim-treesitter] [0/1] Compiling...
│[nvim-treesitter] [1/1] Treesitter parser for gitcommit has been installed
```

**Comment by clason** [comment]
Thank you, but the `master` branch is essentially frozen, as far as infrastructure goes. This whole code has been rewritten from scratch on the `main` branch that will become the default after the Nvim 0.10 release, and I don't want to introduce rebase conflicts.

Further improvements to the `main` branch are welcome, though!

**Comment by wookayin** [comment]
I see. When do we plan to start migrating to `main`? Can I start using the main branch as an early-bird user, provided that nightly neovim is used?

**Comment by lucario387** [comment]
> I see. When do we plan to start migrating to `main`? 

Whenever 0.10 arrives, that's when the switch happens


> Can I start using the main branch as an early-bird user, provided that nightly neovim is used?

Yes and not yet. Remember to disable vim-matchup's ts integration, nvim-treesitter-textobjects, and other plugins that have nvim-treesitter as its dependency. If not you're good to go :D

**Comment by clason** [comment]
> I see. When do we plan to start migrating to main? Can I start using the main branch as an early-bird user, provided that nightly neovim is used?

Yes (that's what I do). But be aware that this will break plugins that depend on nvim-treesitter (like tree-sitter-textobjects), which need to be refactored. Help on this is always appreciated ;)

**Pull request closed without merging**
