### PR TITLE
bump js & ts

### PR DESCRIPTION
**Pull request by amaanq**

### CODE REVIEW

**Comment by lucario387** [comment]
The good old js dependency hell, now in treesitter form

**Comment by amaanq** [comment]
I say we remove the inherits from qmljs till its updated

**Comment by lucario387** [comment]
Go ahead

**Comment by amaanq** [comment]
hm `macos-latest, clang` seems to never start, even after a force push (@clason)

**Comment by clason** [comment]
You need to rebase.

**Comment by amaanq** [comment]
It's rebased on master already..(last commit is your switching to M1 macs for actions)

Maybe it's something to do with "required" actions needing to succeed in the repo settings?

**Comment by clason** [comment]
Yes, exactly.

**Review by lucario387 — APPROVED** [review]
Hope not that many people uses qmljs

**Comment by amaanq** [comment]
I left a note on the grammar repo, hopefully the author updates it soon :sweat_smile:

**Comment by incerta** [comment]
Today I updated the dependency and broke my .ts file syntax highlighting. Got through `git bisect` and found out that this commit did it.

```lua
    {
      'nvim-treesitter/nvim-treesitter',
      -- commit = "364b86ec8ea88e4a77ba676b93fb10829d6a9cb3" -- good (good for ts, bad for js)
      -- commit = "6da205148fb43eb4fa70888fd6ac46a32f1fc3f2" -- bad (good for js, bad for ts)
      commit = "a3ca2e60563064cea008555d0b7d031430305b09" -- recent bad (good for ts, bad for js)
    },

```

My issue was eventually resoved by the commands:

```
:TSInstall typescript
```

and 

```
:TSInstall tsx
```

Just reinstall problematic languages. Learning the hard way 😅

**Pull request merged**
