### PR TITLE
chore: update cmake

### PR DESCRIPTION
**Pull request by uyha**
Fix crashes when opening CMake files

### CODE REVIEW

**Comment by amaanq** [comment]
Is that so? do you have a file i can try on?

**Comment by uyha** [comment]
let me try to create some file that I can share

**Comment by uyha** [comment]
actually, just open an empty cmake file, type # and it crashes nvim immediately

**Comment by amaanq** [comment]
caught it, I forgot advance/skip need to be static...

**Comment by amaanq** [comment]
https://github.com/uyha/tree-sitter-cmake/pull/16

**Review by amaanq — APPROVED** [review]

**Pull request merged**
