### PR TITLE
injections(lua): add various vim api highlights

### LINKED ISSUE #5399: Also inject syntax highlighting in `nvim_create_autocmd`'s `command`
**Is your feature request related to a problem? Please describe.**

#1922 added VimScript injection to `vim.cmd`/`nvim_command`/`nvim_exec`. The `command` field in the `opts` dictionary passed to `:h nvim_create_autocmd` is also VimScript, but doesn't currently get VimScript injected.

```lua
vim.api.nvim_create_autocmd({"BufEnter", "BufWinEnter"}, {
  pattern = {"*.c", "*.h"},
  command = "echo 'Entering a C or C++ file'", -- Doesn't currently get syntax highlighting
})
```

```lua
vim.api.nvim_create_autocmd({"BufEnter", "BufWinEnter"}, {
  pattern = {"*.c", "*.h"},
  callback = function()
    vim.cmd "echo 'Entering a C or C++ file'" -- Does get syntax highlighting
  end
})
```

**Describe the solution you'd like**

The string that the `command` field passed to `nvim_create_autocmd` gets set to should also get VimScript injected.

### PR DESCRIPTION
**Pull request by lucario387**
Closes #5399

### CODE REVIEW

**Comment by clason** [comment]
oof, that's a bit of a monster ;)

Can you also do `nvim_buf_set_keymap` (`vim.keymap.set` is probably not doable) and maybe `nvim_create_user_command`?

**Comment by lucario387** [comment]
I find `nvim_buf_set_keymap` highlightings to be a bit misleading

```lua
vim.api.nvim_buf_set_keymap(0, "n", "abc", "xyz", {})
--                                          ^ keyword.vim
```

Will probably limit the content to capitalized words only or something else

**Comment by clason** [comment]
Yeah, if it is not (easily) possible, just omit it. We can always point here if someone requests it.

**Comment by lucario387** [comment]
Kindof scared to be pinged on lua files getting much slower so I will just narrow them as much as possible.

Downsides are these queries won't get its highlight until the final argument is given

```lua
vim.api.nvim_create_user_command("Foo", "echo 'Bar'")
--                                       ^ string
vim.api.nvim_create_user_command("Foo", "echo 'Bar'", {})
--                                       ^ keyword.vim
```

**Comment by clason** [comment]
Yeah, I'd recommend leaving complicated queries for user configs. Maybe we can just comment them out, so that they're there for users to copy and uncomment?

**Comment by lucario387** [comment]
I will still keep the narrowed down queries for `nvim_create_user_command`, as that can be used to signal users that they're not having enough arguments for that function

**Review by clason — APPROVED** [review]

**Comment by clason** [comment]
I assume you did a test-drive and didn't notice any performance regression ;)

**Comment by lucario387** [comment]
> I assume you did a test-drive and didn't notice any performance regression ;)

Which was the reason for the query narrowing :'). 

It's similar before and after this while editing `runtime/lua/util.lua` so I'll assume there isn't too much performance cost

**Pull request merged**
