### PR TITLE
Add support for *.hjson

### PR DESCRIPTION
**Pull request by winston0410**
This PR tries to add support for `hjson` by adding the queries and the link to my repo for `hjson` support.

### CODE REVIEW

**Comment by winston0410** [comment]
I have just tried `:checkhealth`, and I got the following error:

```
The following errors have been detected:
  - ERROR: hjson(highlights): ...d-master/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 160
 ```

And it seems like my parser is not working on highlight yet:

```
## Parser/Features H L F I J
  - c              ✓ ✓ ✓ ✓ ✓ 
  - r              ✓ ✓ . . . 
  - hjson          x ✓ ✓ ✓ ✓ 
```

What do I need to add in to enable highlight? Is there any example that I can follow?

**Comment by theHamsta** [comment]
Is your comment node really called `(comment)` in your language? Otherwise it would be an invalid node.

**Comment by stsewd** [comment]
@winston0410 since you have jsonc as a dependency, you need to set this option https://github.com/nvim-treesitter/nvim-treesitter/blob/f96c409e3d2b5c4f8fe76f3e049958a293f13167/lua/nvim-treesitter/parsers.lua#L416

**Comment by winston0410** [comment]
@stsewd thanks for the tips. I have added in `generate_requires_npm = true`, yet I am still getting the error. Where should I look for the error?

I have checked the query, and I found out that one of a node that I have inherited from json doesn't exist in my grammar. I commented it out and test again, yet I am getting the same error.

https://github.com/winston0410/nvim-treesitter/commit/04c0a34291d560288ff235bf92665c01a94e08b3#diff-31a2b82acd96a08a76fc5ef46888015ca29ac3d9b757c1a9a5cefabb4c3bbed5R8

**Comment by stsewd** [comment]
@winston0410 please use the master branch as your base branch, for the other error, I think you can try the playground with the query linter https://github.com/nvim-treesitter/playground#query-linter

**Comment by winston0410** [comment]
@

**Comment by winston0410** [comment]
@stsewd with query linter, I am able to spot the invalid node, and it is this line: https://github.com/nvim-treesitter/nvim-treesitter/pull/1657/commits/4324722c6ecbdbb4435eebfae4279f8f892c3704

But I don't get it, why is comma an invalid node? Is it because I haven't specify it as a token in my grammar?

**Comment by winston0410** [comment]
@stsewd This is really helpful, thank you so much. I think I removed that as comma can be omitted in `hjson`, and I have just copy and pasted everything from the original query of `json`, thats why.

**Pull request closed without merging**
