### PR TITLE
feat(sql): json operator highlights

### PR DESCRIPTION
**Pull request by dmfay**
ref https://github.com/DerekStride/tree-sitter-sql/pull/170

### CODE REVIEW

**Comment by amaanq** [comment]
this should target master

**Comment by matthias-Q** [comment]
Nope, we have the release version on a separate branch. Since it is not merged yet, we do not know the commit hash for the lockfile. This is why it is a draft at the moment.

**Comment by amaanq** [comment]
I assumed it was merged

**Comment by matthias-Q** [comment]
It is merged, yes but we keep the parser.c in a separate branch to avoid merge conflicts. The relevant artifact is in the branch gh-pages

**Comment by amaanq** [comment]
Ah - so is this just waiting for the workflow then? I thought main had a different branch for sql, but if that's the case master should be targeted for the pr then

**Comment by dmfay** [comment]
oh that's worse, will reopen

**Pull request closed without merging**
