### PR TITLE
Recognize and highlight vimscript and lua in help files

### PR DESCRIPTION
**Pull request by otherJL0**
Before:
Screen Shot 2022-06-17 at 11 34 25

After:
Screen Shot 2022-06-17 at 11 34 52

### CODE REVIEW

**Comment by clason** [comment]
I don't think this works properly -- look at the `playground` tree; you'll see a lot of Lua codeblocks parsed as `vim`.

(You'd also need to add an `offset` directive to remove the `>` markers -- which are however not mandatory.)

At the current state of things, injections for vimhelp are just not feasible, I'm afraid...

**Comment by theHamsta** [comment]
We would need to add some logic to disambiguate the injection. Easiest would be to just switch to the other alternative language once the first yields errors. It's challenging to do this test not to often, maybe cache the decision for the language for the individual blocks?

**Comment by stsewd** [comment]
We could also try to introduce a convention around blockquotes, like

```
> 
  -- vim:ft=lua
  print("My lua block")
<
```

(in the first or last line)

Or maybe propose upstream an alternative syntax for blockquotes, like


```
> lua
  print("My lua block")
<
```

**Comment by clason** [comment]
Good luck getting Bram to do this in all the Vim help files, and then porting the changes manually...

_If_ we (Neovim) rewrite the whole documentation and diverge from upstream, we might as well use a different file format that is easier to parse (in particular, has no ambiguities).

**Comment by stsewd** [comment]
Opened https://github.com/vim/vim/issues/10597

**Comment by otherJL0** [comment]
Updated the query to match on a much more restricted pattern with no errors showing up in TSPlayground

**Comment by otherJL0** [comment]
It's definitely a lot more neutered. I found a handful of other places this pattern will work:

provider.txt
usr_43.txt
starting.txt
syntax.txt
map.txt

These all have at least one code block prefixed by some `FILENAME.vim:`. The majority of code blocks are ignored unfortunately.

**Comment by clason** [comment]
Yeah... Let me be blunt here: At the current state, it is just _impossible_ to correctly highlight code blocks in help files. (Believe me; I spent some time on that!) And I strongly believe that partial highlighting is worse than no highlighting, because
1. it is inconsistent,
2. it sets wrong expectations ("code highlighting is broken! it doesn't work in this case, but it works in another case, so it should work, right??")

So I'm afraid we need to park this here until there are changes in the documentation (format) itself that allow doing this consistently and correctly.

**Comment by clason** [comment]
This is now being tracked upstream: https://github.com/neovim/neovim/issues/20912

**Pull request closed without merging**
