### PR TITLE
chore: add github sponsors to FUNDING.yml

### LINKED ISSUE #2879: Github Sponsor
**Is your feature request related to a problem? Please describe.**
There's only a link to the open-collective sponsor page.

**Describe the solution you'd like**
A link to the github-sponsor page.

**Describe alternatives you've considered**
Ehm...

**Additional context**
I prefer the github sponsor ship because otherwise I'd have to create a new account on that page. Would that be possible?

### PR DESCRIPTION
**Pull request by kyazdani42**
fixes #2879

### CODE REVIEW

**Review by theHamsta — APPROVED** [review]
Is everything set up for this?

**Comment by kyazdani42** [comment]
very lightly https://github.com/sponsors/nvim-treesitter

**Comment by TornaxO7** [comment]
Thank you for addding the link!

**Review by vigoux — APPROVED** [review]

**Comment by vigoux** [comment]
We'll need to add things to the sponsors page, but most of it is already set up

**Pull request merged**
