### PR TITLE
highlights(lua): add variable attribute for Lua 5.4

### PR DESCRIPTION
**Pull request by MunifTanjim**
Depends on: https://github.com/MunifTanjim/tree-sitter-lua/tree/v0.0.14

### CODE REVIEW

**Comment by clason** [comment]
Feel free to bump the parser along with the queries. (In fact, I would very much prefer if people did that rather than rely on the lockfile update action...)

**Comment by clason** [comment]
By the way, it would be great if your repo also tracked the queries -- this makes sure that there's always a source of truth for a working parser+query combination.

**Review by clason — APPROVED** [review]

**Comment by MunifTanjim** [comment]
> By the way, it would be great if your repo also tracked the queries -- this makes sure that there's always a source of truth for a working parser+query combination.

👍🏼 Good to know. I'll add those.

**Comment by clason** [comment]
Tests are failing -- can you check if they pass locally? Might be the same issue with conflicting bundled parser as with vimdoc.

**Comment by MunifTanjim** [comment]
> Tests are failing -- can you check if they pass locally? Might be the same issue with conflicting bundled parser as with vimdoc.

I've installed it locally and this is the result:

```lua
local c <const>, x <const> = 42
local f <close> = io.open('/file.lua')
```

```
local_declaration: variable_declaration [17, 0] - [17, 31]
  "local" [17, 0] - [17, 5]
  assignment_statement [17, 6] - [17, 31]
    variable_list [17, 6] - [17, 26]
      name: identifier [17, 6] - [17, 7]
      attribute: attribute [17, 8] - [17, 15]
        "<" [17, 8] - [17, 9]
        identifier [17, 9] - [17, 14]
        ">" [17, 14] - [17, 15]
      "," [17, 15] - [17, 16]
      name: identifier [17, 17] - [17, 18]
      attribute: attribute [17, 19] - [17, 26]
        "<" [17, 19] - [17, 20]
        identifier [17, 20] - [17, 25]
        ">" [17, 25] - [17, 26]
    "=" [17, 27] - [17, 28]
    expression_list [17, 29] - [17, 31]
      value: number [17, 29] - [17, 31]
local_declaration: variable_declaration [18, 0] - [18, 38]
  "local" [18, 0] - [18, 5]
  assignment_statement [18, 6] - [18, 38]
    variable_list [18, 6] - [18, 15]
      name: identifier [18, 6] - [18, 7]
      attribute: attribute [18, 8] - [18, 15]
        "<" [18, 8] - [18, 9]
        identifier [18, 9] - [18, 14]
        ">" [18, 14] - [18, 15]
    "=" [18, 16] - [18, 17]
    expression_list [18, 18] - [18, 38]
      value: function_call [18, 18] - [18, 38]
        name: dot_index_expression [18, 18] - [18, 25]
          table: identifier [18, 18] - [18, 20]
          "." [18, 20] - [18, 21]
          field: identifier [18, 21] - [18, 25]
        arguments: arguments [18, 25] - [18, 38]
          "(" [18, 25] - [18, 26]
          string [18, 26] - [18, 37]
            start: "string_start" [18, 26] - [18, 27]
            content: "string_content" [18, 27] - [18, 36]
            end: "string_end" [18, 36] - [18, 37]
          ")" [18, 37] - [18, 38]
```

Highlight is working as well:

image

image

**Comment by clason** [comment]
Hmm. Can you rebase on master and try again? (I just bumped the parser, maybe that updates the caches.)

**Comment by clason** [comment]
> No luck. Can it be because the tests are somehow using the parser bundled with Neovim core?

Yes, that is exactly what I believe is happening -- possibly because of how the scripts add the plugin dir to `rtp` (wrong way around from normal use).

**Comment by clason** [comment]
Included in #3754, thanks!

**Pull request closed without merging**
