### PR TITLE
main

### PR DESCRIPTION
**Pull request by lewis6991**
- feat!: drop modules, general refactor and cleanup
- feat!: refactor `locals.lua` into standalone
- refactor: use vim.fs.joinpath
- refactor: rewrite installation using jobs and async
- ci: remove update-lockfile shell script
- fix tests
- fix: install dependencies
- refactor: use `vim.uv`
- feat: drop `TSInstallInfo` in favor of better `checkhealth`
- fix: expand tiers in ignore_install
- refactor: use vim.system (#4923)
- feat!: drop makefile support, norg parser
- feat: add parser tiers
- fix: filter languages through parser.configs
- fix: check queries in needs_update()
- fix: check if config has install_info in filter
- fix: make locals work again
- fix: always normalize paths
- fix: remove upstreamed directives
- fix: add stricter cc options (#5063)
- injections(nix): add nixosTest.testScript + home-manager nvim config
- tests(nix): nix injections
- style: apply lisp-style to nix injections
- fix: cleanup diagnostics
- tests: remove set ft
- feat(locals)!: switch to upstream captures
- feat: remove obsolete directives
- docs(readme): document 'location' key
- feat(c-family): inherit injections
- feat(injections): add printf format strings
- fix!: indents now rely on treesitter highlight
- feat: allow a custom revision in install_info

### CODE REVIEW

**Comment by clason** [comment]
👀

**Comment by lewis6991** [comment]
Targeted master by accident

**Comment by clason** [comment]
`gh pr create -B main`

**Comment by lewis6991** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/pull/5375

**Pull request closed without merging**
