### PR TITLE
Node movement selection

### PR DESCRIPTION
**Pull request by theHamsta**
Add function to select current node in `node_movement` this plays nicely with `incremental_selection` since you can grow the selection afterwards.

### CODE REVIEW

**Comment by vigoux** [comment]
The way `incremental_selection` works is that is selects the current node you are on when called for the first time. Correct me if I'm wrong but I think that the `select_current_node` thing is already implemented.

**Comment by theHamsta** [comment]
Actually, yes. It's aleady implemented. This is why the added function only has 3 lines. I was only missing the normal mode binding to get your first visual selection. `incremental_selection` can not know the depth you're currently at after cursor movement.

**Comment by theHamsta** [comment]
Maybe you're right and I should just add a normal mode mapping for `incremental_selection.increasing_node`. `incremental_selection` already has mappings `operator_pending` and `visual_mode`.

**Comment by vigoux** [comment]
I did a bit of testing and it seems that `node_movement.current_node` has only one key, which is `0`. 
It might be an error, and you may want to check if `buf == 0` you should maybe get `nvim_get_current_buf()` instead. I don't really know for now but you may want to investigate.

**Comment by kyazdani42** [comment]
@vigoux  @theHamsta i think this PR will be useless after i merged the refactoring (i can basically do a 2 line function for this thing). I'm closing this

**Pull request closed without merging**
