### PR TITLE
We can update the new minimal requirement to 0.5

### PR DESCRIPTION
**Pull request by theHamsta**
Let's wait a week or so until most people have 0.5 or newer.

TODO: add CI job for 0.5 stable

### CODE REVIEW

**Comment by stsewd** [comment]
I'm not sure about the state of the treesitter api in neovim, but if there are changes, this will be out of date soon as users will require nightly again.

**Comment by shadmansaleh** [comment]
> I'm not sure about the state of the treesitter api in neovim, but if there are changes, this will be out of date soon as users will require nightly again.

I think treesitter was left experimental because api changes are expected .

How about a separate branch on nvim-treesitter for devlopment requireing nightly.

And have non breaking changes on master .

Later breaking changes can be merged with neovim release.

**Comment by David-Else** [comment]
Please make the main branch continue to work with 0.5 stable and not require nightly. It might be worth making another branch for user who would like to continue testing Neovim nightly.

I know treesitter is 'experimental', but it works 100% here with Neovim 0.5 and it would be great to keep it that way :)

**Comment by theHamsta** [comment]
I was also thinking about making a separate branch but I don't think it's worth the effort. It would be possible to freeze the current state to a separate branch but at the moment I would think that it would be more effective maintain  stability until we need to do the first breaking change and then just create a dev branch.

I think that the core of our repos are the queries, I would expect them to be fairly stable as long as tree-sitter maintains ABI.  I'd expect quite a few bug fixes from new users jumping onto 0.5 until we freeze a 0.5 tag.

**Comment by shadmansaleh** [comment]
Freezing current state makes sense .

In the frozen branch parsers should be frozen too I think . So `TSInstall` and `TSUpdate` doesn't pull incompatable changes from parser side.

**Comment by theHamsta** [comment]
@shadmansaleh when the repo is frozen `lockfile.json` stays the same. So each git commit will only install compatible revisions.

**Comment by shadmansaleh** [comment]
Right . I didn't see the lockfile :P . I was looking at parsers.lua and thought they are pulled right from repo master . My bad 😂

**Pull request closed without merging**
