### PR TITLE
do not highlight jsx_text as normal

### PR DESCRIPTION
**Pull request by kyazdani42**
highlighting with `@Normal` is conflicting with other groups, because normal also highlights the background color.
What happens then is that the CursorLine don't get properly highlighted on nodes where `@Normal` is applied.

### CODE REVIEW

**Comment by theHamsta** [comment]
Couldn't you create a new highlight group for resetting on some things. Python also uses `@Normal`

**Comment by kyazdani42** [comment]
i guess that would be ideal, not sure what name to give it though. Something like none would work ?

**Review by steelsojka — APPROVED** [review]
👍

**Comment by theHamsta** [comment]
You need to document your query to make CI pass.

**Review by theHamsta — APPROVED** [review]

**Review by theHamsta — CHANGES_REQUESTED** [review]
could you also use it for Python?

**Review by vigoux — APPROVED** [review]

**Review by stsewd — COMMENTED** [review]
We should document this in CONTRIBUITING.md

**Review by theHamsta — APPROVED** [review]

**Comment by kyazdani42** [comment]
@theHamsta I'll leave you handle the python side, i'm not too sure on which node i should apply this group.

**Review by stsewd — APPROVED** [review]

**Comment by theHamsta** [comment]
@kyazdani42 the one that is `@Normal`

```scheme
; Reset highlighing in f-string interpolations
(interpolation) @Normal
```

**Comment by theHamsta** [comment]
Thanks!

**Pull request merged**
