### PR TITLE
fix(haskell): highlight exp_name as function in infix operations

### PR DESCRIPTION
**Pull request by kyazdani42**
fixes https://github.com/nvim-treesitter/nvim-treesitter/issues/3056, although i'm not very confident this is the right change

### CODE REVIEW

**Review by theHamsta — APPROVED** [review]

**Comment by theHamsta** [comment]
I'm not very confident to judge about this either do you want to ask for a third opinion or just merge?

**Comment by clason** [comment]
YOLO

**Comment by clason** [comment]
(Haskell is listed as "unmaintained", so it's clearly a best effort by rank amateurs. People will be sure to let us know if we got it wrong...)

**Comment by kyazdani42** [comment]
Okay then :)

**Pull request merged**
