### PR TITLE
chore(fish): update test command highlight query

### PR DESCRIPTION
**Pull request by ram02z**
Updated `highlights.scm` to reflect breaking changes from https://github.com/ram02z/tree-sitter-fish/pull/19

### CODE REVIEW

**Comment by clason** [comment]
Please always include the parser update in a breaking query change. (If the parser update has not been merged yet and you are opening this PR in advance, mark it as draft.)

**Comment by ram02z** [comment]
Strange, I merged https://github.com/ram02z/tree-sitter-fish/pull/19 before opening this PR.

**Comment by clason** [comment]
Yes, but you need to update the `lockfile.json` to point to the new revision; this doesn't happen magically and instantly, you know ;)

**Comment by ObserverOfTime** [comment]
The lockfile was updated but the node still exists in one other capture.

**Comment by clason** [comment]
> The lockfile was updated but the node still exists in one other capture.

No it was not; the PR was only merged 3 hours ago.

**Comment by ram02z** [comment]
> Yes, but you need to update the `lockfile.json` to point to the new revision; this doesn't happen magically and instantly, you know ;)

I do know that, thats why I updated the `lockfile.json` with the new revision before I opened the PR ;)

> The lockfile was updated but the node still exists in one other capture.

Thanks! I forgot one of the removed nodes from `highlights.scm`. This should be fixed now.

**Review by ObserverOfTime — APPROVED** [review]

**Comment by clason** [comment]
Sorry about that, then! I should have looked more closely. (We had a number of  PRs, so I was a bit on autopilot.)

**Comment by ram02z** [comment]
> Sorry about that, then! I should have looked more closely. (We had a number of  PRs, so I was a bit on autopilot.)

No worries :)

**Pull request merged**
