### PR TITLE
feat(locals)!: switch to upstream captures

### PR DESCRIPTION
**Pull request by clason**
https://tree-sitter.github.io/tree-sitter/syntax-highlighting#local-variables

but keep the more detailed subcaptures for definitions

@TheLeoP

### CODE REVIEW

**Comment by lucario387** [comment]
isn't it `local.*` according to upstream's docs?

**Comment by clason** [comment]
whoops...!

**Comment by clason** [comment]
@TheLeoP @theHamsta any objections to this change? Did I break `locals.lua` (again)?

**Comment by clason** [comment]
Pulling the trigger on this; if I broke something, I'm sure someone will let me know.

**Comment by eelcocramer** [comment]
@clason it seems to have broken `get_definitions`, at least I'm now getting this error when I'm trying to lookup references to a `Go` field.

```
Error executing vim.schedule lua callback: ...nvim/lazy/nvim-treesitter/lua/nvim-treesitter/locals.lua:44: attempt to index field 'local' (a nil value)                                      
stack traceback:                                                                                                                                                                             
        ...nvim/lazy/nvim-treesitter/lua/nvim-treesitter/locals.lua:44: in function 'get_definitions'                                                                                        
        ...nvim/lazy/nvim-treesitter/lua/nvim-treesitter/locals.lua:165: in function 'fn'                                                                                                    
        ...im/lazy/nvim-treesitter/lua/nvim-treesitter/ts_utils.lua:380: in function 'get_definitions_lookup_table'                                                                          
        ...nvim/lazy/nvim-treesitter/lua/nvim-treesitter/locals.lua:225: in function 'find_definition'                                                                                       
        ...are/nvim/lazy/navigator.lua/lua/navigator/treesitter.lua:97: in function 'ts_def'                                                                                                 
        ...are/nvim/lazy/navigator.lua/lua/navigator/lspwrapper.lua:241: in function 'ts_definition'                                                                                         
        ...are/nvim/lazy/navigator.lua/lua/navigator/lspwrapper.lua:378: in function 'locations_to_items'                                                                                    
        ...hare/nvim/lazy/navigator.lua/lua/navigator/reference.lua:102: in function 'ref_view'                                                                                              
        ...hare/nvim/lazy/navigator.lua/lua/navigator/reference.lua:180: in function ''                                                                                                      
        vim/_editor.lua: in function <vim/_editor.lua:0>           
```

**Comment by clason** [comment]
Please open a dedicated (reproducible) issue -- after making sure you're at the latest commit. (There were already fixes to this function.)

**Pull request merged**
