### PR TITLE
fix(dart): indentation for class function body is incorrect

### LINKED ISSUE #4642: Dart: Expanding curly on function argument is indenting incorrectly
### Describe the bug

See example below

```dart
class Something {
  final int number;
  final Function(int) write;

  Something(this.number, this.write);
}

void test() {
  Something(
    1,
    (int number) {}, <--- put cursor inside the curly and add a new line
  );
}

```

```dart
class Something {
  final int number;
  final Function(int) write;

  Something(this.number, this.write);
}

void test() {
  Something(
    1,
    (int number) {
  }, <--- curly is here
    } <---- but should be indented this much
  );
}

```

### To Reproduce

1. Create a new dart file
2. paste the following

```dart
class Something {
  final int number;
  final Function(int) write;

  Something(this.number, this.write);
}

void test() {
  Something(
    1,
    (int number) {}, // <--- put cursor inside the curly and add a new line
  );
}
```

### Expected behavior

Should result in this indentation

```dart
class Something {
  final int number;
  final Function(int) write;

  Something(this.number, this.write);
}

void test() {
  Something(
    1,
    (int number) {
    },
  );
}
```

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v16.19.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 14.0.3 (clang-1403.0.22.14.1)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "22.4.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - dart                ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - prisma              ✓ . . . .
  - query               ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.0-dev-1+g1b57a0296
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -I/Users/robertbrunhage/neovim/.deps/usr/include/luajit-2.1 -I/opt/homebrew/opt/gettext/include -I/Users/robertbrunhage/neovim/.deps/usr/include -I/Users/robertbrunhage/neovim/build/src/nvim/auto -I/Users/robertbrunhage/neovim/build/include -I/Users/robertbrunhage/neovim/build/cmake.config -I/Users/robertbrunhage/neovim/src -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include -I/Users/robertbrunhage/neovim/.deps/usr/include -I/Users/robertbrunhage/neovim/.deps/usr/include -I/Users/robertbrunhage/neovim/.deps/usr/include -I/Users/robertbrunhage/neovim/.deps/usr/include -I/Users/robertbrunhage/neovim/.deps/usr/include -I/Users/robertbrunhage/neovim/.deps/usr/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by RobertBrunhage**
fixes #4642

Didn't know how to add the test case where it puts the cursor at a specific place and adds a new line. So just added the normal code for now in the test. Let me know what I can do to add it to the actual test!

**Actually, looking at the test this was not the correct approach. Any help would be appreciated!**

### CODE REVIEW

**Comment by lucario387** [comment]
So this introduces the one in https://github.com/nvim-treesitter/nvim-treesitter/pull/4638 again, Will this cause issue with the one added in https://github.com/nvim-treesitter/nvim-treesitter/pull/4638?

**Comment by lucario387** [comment]
To do tests for a cursor, the current (only?) way is to have the line above be `something() {`
then do `run:new_line({ text="}"}...)` to check if the curly brace has the correct indent or not

**Comment by lucario387** [comment]
The failed test is probably related to the queries added in #4638 being `@indent.branch` and not `@indent.dedent`

The intended use case for `@indent.branch` is to be a one-off for the current line (at least from my understandings), while `@indent.dedent` is for dedenting the whole body of a code block, but not the  first line itself

**Comment by RobertBrunhage** [comment]
@lucario387 Adding that capture again resulted in double indent for this case
image

Not sure how to get `@indent.dedent` to work correctly, as if I use that I don't get any of the indenting in this case

**Comment by RobertBrunhage** [comment]
@lucario387 added a wip commit that kinda just reverts https://github.com/nvim-treesitter/nvim-treesitter/issues/4637. Not sure how to get both of the approaches to work though

**Comment by RobertBrunhage** [comment]
Created a revert of https://github.com/nvim-treesitter/nvim-treesitter/pull/4644 for now

**Comment by RobertBrunhage** [comment]
I will close this one, as it seems to stem from https://github.com/nvim-treesitter/nvim-treesitter/pull/4644

**Comment by lucario387** [comment]
> There seems to be no difference of these two callbacks, so not sure of the approach to handle indenting differently for them?
> 
> image
> 
> 

You can always target the second argument and beyond that, but that just sounds buggy ig

**Comment by lucario387** [comment]
image
Helix also suffers from the queries

**Comment by lucario387** [comment]
@RobertBrunhage 

C cascading if-else also suffers from this

The code below is an example of how to resolve it (Note that this still fails on multiline conditionals, will need to try more on that)

https://github.com/nvim-treesitter/nvim-treesitter/blob/9161093fc7e13b12aa5bc86c641768c049d43a26/queries/c/indents.scm#L39-L96

**Pull request closed without merging**
