### PR TITLE
fix: readme typo, removing deprecated docs

### PR DESCRIPTION
**Pull request by carlosala**
The title is descriptive, thanks for the work!

### CODE REVIEW

**Comment by clason** [comment]
Are you sure that this is the change you intended? This reverts _intentional_ changes.

**Comment by carlosala** [comment]
These are the docs I expect to have after #2471. `used_by` is deprecated, so removing its docs would be nice. And the other two lines are typos.

**Comment by clason** [comment]
No, please check the diff again. I don't think you intended this: you're removing

* a rename to a doc snippet to match the corresponding rename in the code
* a new(!) doc snippet to show how you can use parsers with other filetypes now that `used_by` is removed.

**Comment by carlosala** [comment]
I think that I don't understand something.
  - I removed a snippet explaining how to use `used_by`, which now does nothing, just reports an error.
  - I fixed new snippet, because `nvim-treesitter.parser` does not exist and is not using the local variable defined the previous line.

**Review by kyazdani42 — APPROVED** [review]
@clason that was my fault, i introduced typos indeed, this PR is good.
@carlosala can you also update the doc file please ?

**Comment by carlosala** [comment]
Sure!

**Comment by clason** [comment]
> @clason that was my fault, i introduced typos indeed, this PR is good.

Are you sure? I agree on 1., I confused that with a different snippet in the docs (sorry!), but the `ft_to_parser.someft` doesn't look correct -- you renamed that to `filetype_to_parsername` in that PR, didn't you?

**Comment by clason** [comment]
Sorry, I indeed failed to read this correctly. I apologize!

**Comment by carlosala** [comment]
@kyazdani42 I don't see where should I change something in the doc file, I don't find anything related to this. Could you please give me some hint?

**Review by theHamsta — APPROVED** [review]

**Comment by kyazdani42** [comment]
@carlosala cannot find the reference to the doc i wrote earlier :confused: lets merge this. thanks for the patch :)

**Pull request merged**
