### PR TITLE
update(phpdoc) Add scanner.c

### PR DESCRIPTION
**Pull request by mikehaertl**
* Add `scanner.c` 
 * Move phpdoc config down to injected parsers

### CODE REVIEW

**Review by clason — APPROVED** [review]

**Review by theHamsta — APPROVED** [review]

**Comment by mikehaertl** [comment]
@theHamsta Weird, but if I run `TSUpdate! phpdoc` I get a warning:

```
nvim-treesitter[phpdoc]: Error during compilation                                                                                                     
cc: error: src/scanner.c: Datei oder Verzeichnis nicht gefunden
```

But the file exists in the repo: https://github.com/claytonrcarter/tree-sitter-phpdoc/blob/master/src/scanner.c

Is the revision of tree-sitter-phpdoc maybe locked somewhere?

**Comment by clason** [comment]
> Is the revision of tree-sitter-phpdoc maybe locked somewhere?

Yes, in the aptly-named `lockfile.json`.

(There's an automated PR running as we speak that bumps these, but it's always good to include such necessary changes manually in a relevant PR.)

**Comment by mikehaertl** [comment]
@clason Oh, I see. Thanks. Would I put the revision there manually? Or is there some command to update it automatically?

**Comment by clason** [comment]
Yes, you would put it there manually. (There is a script that updates all parsers automatically, but best leave that for the CI job -- for a single parser, just put the commit hash you know is needed. It need not be the latest; further updates are automated, as long as they pass CI.)

**Comment by clason** [comment]
Try again now!

**Comment by mikehaertl** [comment]
> Try again now!

Yup, all good now. Thanks again.

**Pull request merged**
