### PR TITLE
Update indents for Ruby

### PR DESCRIPTION
**Pull request by CKolkey**
Add `rescue` and `ensure` as a `@branch` captures for ruby

Standard formatting for `rescue` and `ensure` are as follows:

```ruby
def foo
  # ...
rescue StandardError
  # ...
ensure
  # ...
end
```
https://ruby-doc.org/docs/ruby-doc-bundle/UsersGuide/rg/ensure.html

### CODE REVIEW

**Comment by lucario387** [comment]
think you should add tests

**Comment by CKolkey** [comment]
Sure... I get this when I try to run `scripts/run_tests.sh` (which I presume is the way to run the tests)

```
Error detected while processing command line:
E492: Not an editor command: PlenaryBustedDirectory tests/ { minimal_init = './scripts/minimal_init.lua' }
```

**Comment by CKolkey** [comment]
Alright, figured out I could just run `:lua require('plenary.test_harness').test_directory(vim.fn.expand("%:p"))` from in the spec file with my normal config. Seems like the script included expects `plenary` to be source-able, but doesn't ship it.

**Review by theHamsta — APPROVED** [review]
Thank you!

**Pull request merged**
