### PR TITLE
parsers: Add MDeiml/tree-sitter-markdown as markdown parser

### LINKED ISSUE #872: Add Markdown parser
**Language information**

There is a Markdown parser for treesitter: https://github.com/ikatyang/tree-sitter-markdown

As I understand it, this was already in this repository, but has been removed due to #602. Afaik, this issue has been resolved about a week ago, see https://github.com/ikatyang/tree-sitter-markdown/pull/17, so I would assume that it can be added back in as a default parser, right?

### PR DESCRIPTION
**Pull request by theHamsta**
Fixes #872

TODOs

- [x] Fuzz parser to detect possible SEGFAULTs (already ran 3h, looks ok so far)

### CODE REVIEW

**Comment by MDeiml** [comment]
Could you share your fuzzing setup? It would be nice to include it in the repo.

**Comment by theHamsta** [comment]
I explained it here: https://github.com/ikatyang/tree-sitter-markdown/issues/14

**Review by vigoux — APPROVED** [review]

**Comment by runiq** [comment]
Does this… does this mean we have an actual, honest-to-god Treesitter markdown parser easily available now? One that could (down the line, ostensibly) be used in LSP docs etc. too?

**Comment by MDeiml** [comment]
As I said in #872 this parser is not yet fully to spec. Also, because of the way that tree-sitter handles its "conflicts" this will never be 100% correct for deeply nested emphasis and the like. But other than that yes!

**Comment by lewis6991** [comment]
Found a pretty major problem with the injections using this.

Just open a markdown file with the contents:
```
```{

```
(with a newline) at the end.

Gives a heap of `E220: Missing }.` errors. Tried to fix in this [PR](https://github.com/neovim/neovim/pull/16668)

**Pull request merged**
