### PR TITLE
fix(go): apply indents in a communication case in a select statement

### LINKED ISSUE #4248: golang: indentation problems with `switch/select { case }`
### Describe the bug

See https://github.com/nvim-treesitter/nvim-treesitter/issues/3288#issuecomment-1236843453
```go
ctx := context.TODO()
select {
case <-ctx.Done():
fmt.Println("indentation")  // wrong indention
default:
}

switch a {
case "b":
fmt.Println("indentation")  // wrong indention
}
```

### To Reproduce

 Copy the golang code from [Describe the bug](#describe-the-bug) section.

### Expected behavior

```go
ctx := context.TODO()
select {
case <-ctx.Done():
        fmt.Println("indentation")
default:
}

switch a {
case "b":
        fmt.Println("indentation")
}
```

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v19.4.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 14.0.0 (clang-1400.0.29.202)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "x86_64",
  release = "22.2.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000"
}

## Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - git_rebase          ✓ . . . ✓
  - gomod               ✓ . . . ✓
  - gowork              ✓ . . . ✓
  - json5               ✓ . . . ✓
  - make                ✓ . ✓ . ✓
  - sql                 ✓ . . . ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - help                ✓ . . . ✓
  - bash                ✓ ✓ ✓ . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ . ✓
  - rst                 ✓ ✓ . . ✓
  - hcl                 ✓ . ✓ ✓ ✓
  - fish                ✓ ✓ ✓ ✓ ✓
  - proto               ✓ . ✓ . .
  - java                ✓ ✓ . ✓ ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - diff                ✓ . . . .
  - toml                ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - vim                 ✓ ✓ ✓ . ✓
  - gitignore           ✓ . . . .
  - dockerfile          ✓ . . . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - gitcommit           ✓ . . . ✓
  - cmake               ✓ . ✓ . .

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```
```


### Output of `nvim --version`

```text
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.8.0/share/nvim"

Run :checkhealth for more info
```
```


### Additional context

_No response_

### PR DESCRIPTION
**Pull request by amaanq**
Closes #4248 

Thanks

### CODE REVIEW

**Comment by theHamsta** [comment]
Can you add a test case for the problem this change fixes?

**Comment by theHamsta** [comment]
@damnever

**Comment by amaanq** [comment]
> Can you add a test case for the problem this change fixes?

Where do these test cases go? I've only written test in tree-sitter-* repos before

**Comment by amaanq** [comment]
@theHamsta is that good?

**Review by theHamsta — APPROVED** [review]

**Pull request merged**
