### PR TITLE
Fix highlight query tests

### PR DESCRIPTION
**Pull request by theHamsta**

### CODE REVIEW

**Comment by theHamsta** [comment]
@antosha417 your test was failing because `days` was actually highlighted as `@string` instead of `@keyword`. What is the correct highlight?

**Comment by theHamsta** [comment]
This fixes the tests. Should have listened to `@MDeiml` comments about the quick fix that disabled some of the markdown parens. We didn't require branches to be up-to-date so tests where not performed on a fully rebased branch.

**Review by clason — APPROVED** [review]
yep, let's go with that for now!

**Comment by antosha417** [comment]
I modified the grammar to parse units as keyword. So days should parse as keyword. @theHamsta you should TSupdate hocon to run tests locally.

**Pull request merged**
