### PR TITLE
parsers: add tree-sitter-gitignore

### PR DESCRIPTION
**Pull request by theHamsta**
Not feeling too confident about the captures yet. Any feedback welcome!

@andy2mrqz 

Addresses https://github.com/nvim-treesitter/nvim-treesitter/issues/2282#issuecomment-1215780654

### CODE REVIEW

**Comment by theHamsta** [comment]
Please note that `gitignore` is not a known filetype to vim. You need to add something like
```
augroup filetypedetect
    au! BufRead,BufNewFile .gitignore set filetype=gitignore
augroup end
```
to your init.vim. Support for the filetype should be contributed to github.com/vim/vim

**Comment by shunsambongi** [comment]
@theHamsta I was planning on contributing this parser eventually, but I had become a little busy, so I appreciate this PR. I don't know if it would help you at all, but I was playing around with some highlight queries in https://github.com/shunsambongi/gitignore.nvim/blob/0b8108524dbc0d15a34b6e1ca5bbd75b04a5ddfb/queries/gitignore/highlights.scm

**Comment by shunsambongi** [comment]
> Please note that `gitignore` is not a known filetype to vim. You need to add something like
> 
> ```
> augroup filetypedetect
>     au! BufRead,BufNewFile .gitignore set filetype=gitignore
> augroup end
> ```
> 
> to your init.vim. Support for the filetype should be contributed to github.com/vim/vim

I also just wanted to point out that there are a bunch of tools that use ignore files that can be highlighted using the parser being added in this PR. For example, [sharkdp/fd](https://github.com/sharkdp/fd)  (.fdignore), [BurntSushi/ripgrep](https://github.com/BurntSushi/ripgrep) (.rgignore), [prettier](https://prettier.io/docs/en/ignore.html) (.prettierignore), etc. So you would just need to modify the autocmd to support these files.

**Comment by theHamsta** [comment]
Commited your changes

**Review by stsewd — APPROVED** [review]

**Pull request merged**
