### PR TITLE
feat(python): support typed (kw)args

### LINKED ISSUE #5874: Python: support typed (kw)args (PEP 484)
### Describe the highlighting problem

Functions with typed args or kwargs (supported since [PEP 484](https://peps.python.org/pep-0484/#arbitrary-argument-lists-and-default-argument-values)) are not highlighted correctly. The args and kwargs are highlighted as variables rather than parameters.

### Example snippet that causes the problem

```python
def test_func(
    first_argument: str,
    *args: int,
    **kwargs: list[str],
):
    pass
```

### Tree-sitter parsing result

I'm not sure if I managed to toggle the injected languages, apologies if not. I think the args and kwargs are identified correctly, it's just the styling which is wrong (they get styled as variables rather than as parameters, I suspect [these lines](https://github.com/nvim-treesitter/nvim-treesitter/blob/8cd2b230174efbf7b5d9f49fe2f90bda6b5eb16e/queries/python/highlights.scm#L133) have to change to support type versions of variadic parameters)

```
(function_definition) ; [1:1 - 6:8] python
 "def" ; [1:1 - 3] python
 name: (identifier) ; [1:5 - 13] python
 parameters: (parameters) ; [1:14 - 5:1] python
  "(" ; [1:14 - 14] python
  (typed_parameter) ; [2:5 - 23] python
   (identifier) ; [2:5 - 18] python
   ":" ; [2:19 - 19] python
   type: (type) ; [2:21 - 23] python
    (identifier) ; [2:21 - 23] python
  "," ; [2:24 - 24] python
  (typed_parameter) ; [3:5 - 14] python
   (list_splat_pattern) ; [3:5 - 9] python
    "*" ; [3:5 - 5] python
    (identifier) ; [3:6 - 9] python
   ":" ; [3:10 - 10] python
   type: (type) ; [3:12 - 14] python
    (identifier) ; [3:12 - 14] python
  "," ; [3:15 - 15] python
  (typed_parameter) ; [4:5 - 23] python
   (dictionary_splat_pattern) ; [4:5 - 12] python
    "**" ; [4:5 - 6] python
    (identifier) ; [4:7 - 12] python
   ":" ; [4:13 - 13] python
   type: (type) ; [4:15 - 23] python
    (generic_type) ; [4:15 - 23] python
     (identifier) ; [4:15 - 18] python
     (type_parameter) ; [4:19 - 23] python
      "[" ; [4:19 - 19] python
      (type) ; [4:20 - 22] python
       (identifier) ; [4:20 - 22] python
      "]" ; [4:23 - 23] python
  "," ; [4:24 - 24] python
  ")" ; [5:1 - 1] python
 ":" ; [5:2 - 2] python
 body: (block) ; [6:5 - 8] python
  (pass_statement) ; [6:5 - 8] python
   "pass" ; [6:5 - 8] python
```

### Example screenshot

colour scheme: dracula

Installation instructions here: https://github.com/Mofiqul/dracula.nvim

Although I hope this is simple enough that colour scheme isn't the issue... (particularly given that other arguments are highlighting correctly, it's just args and kwargs that are the issue)

image

### Expected behavior

I guess it makes most sense to highlight args and kwargs like they are when there are no type hints i.e. like the below

image

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- WARNING `node` executable not found (only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 13.1.6 (clang-1316.0.21.2.5)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "21.5.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 21.5.0: Tue Apr 26 20:57:23 PDT 2022; root:xnu-8020.121.3~2/RELEASE_ARM64_T8110"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cmake               ✓ . ✓ ✓ .
  - dockerfile          ✓ . . . ✓
  - fortran             ✓ . ✓ ✓ .
  - gitignore           ✓ . . . .
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
(yes, not latest master, but I don't think that matters for this...)

NVIM v0.9.4
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.4/share/nvim"

Run :checkhealth for more info
```

### Additional context

This is obviously not a massive issue. I'm also very help with a PR if you think the identified bug is correct and the solution is to just tweak the styling.

### PR DESCRIPTION
**Pull request by znicholls**
Closes #5874

### CODE REVIEW

**Comment by clason** [comment]
Thank you! Just a small heads-up that `master` is currently frozen until we backport the (breaking) changes from `main` regarding new capture names and query formatting.

**Comment by znicholls** [comment]
All good. Do you want any CHANGELOG entries or anything (I read CONTRIBUTING, but quickly...)

For what it's worth, it seems to work and handles more complex [PEP692](https://peps.python.org/pep-0692/) stuff too

image

**Comment by lucario387** [comment]
Can lambdas also have types set to it :thinking:

**Comment by znicholls** [comment]
> Can lambdas also have types set to it

Ye I have no idea, I didn't bother go googling PEPs to find but happy to implement if you have an example

**Review by lucario387 — APPROVED** [review]
Lambdas can't have types assigned to it directly, so this is enough

**Comment by clason** [comment]
The backport PR has been merged; please **rebase on master** and note 1. the new list of valid capture names and 2. the mandatory query format (run `./scripts/format-queries.lua` on the new queries).

**Comment by znicholls** [comment]
> **EDIT** I just did that for you; will merge when CI passes.

Thanks!

**Pull request merged**
