### PR TITLE
fix(indent): return early if query doesn't exist

### LINKED ISSUE #4854: `get_indent()` cause `lua/nvim-treesitter/indent.lua:99: attempt to index local 'query' (a nil value)` error
### Describe the bug

I'm using indent-blankline.nvim and [it calls get_indent](https://github.com/lukas-reineke/indent-blankline.nvim/blob/86d1b71c5c26168c3a3a9ff5f69e833889a09c1d/lua/indent_blankline/init.lua#L475)

Since fa23ff4bd7d77370613ecb37e49edb3ec3e7a931, this sometimes cause the error below:

```
Error executing vim.schedule lua callback: ...m/plugged/nvim-treesitter/lua/nvim-treesitter/indent.lua:99: attempt to index local 'query' (a nil value)
stack traceback:
        ...m/plugged/nvim-treesitter/lua/nvim-treesitter/indent.lua:99: in function 'fn'
        ...m/plugged/nvim-treesitter/lua/nvim-treesitter/indent.lua:76: in function 'get_indents'
        ...m/plugged/nvim-treesitter/lua/nvim-treesitter/indent.lua:147: in function 'get_indent'
        ...gged/indent-blankline.nvim/lua/indent_blankline/init.lua:475: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

### To Reproduce

1. Save below as `mini.vim` (I'm using vim-plug)
    ```vim
    set runtimepath^=~/.vim runtimepath+=~/.vim/after
    let &packpath = &runtimepath

    call plug#begin('~/.vim/plugged')
    Plug 'nvim-treesitter/nvim-treesitter', { 'do': ':TSUpdate' }
    Plug 'lukas-reineke/indent-blankline.nvim'
    call plug#end()

    set nobackup
    set nowritebackup
    set cmdheight=2
    set updatetime=300

    set background=dark
    highlight Normal      ctermfg=223 ctermbg=NONE guifg=#ebdbb2 guibg=NONE
    highlight NormalFloat ctermfg=223 ctermbg=237  guifg=#ebdbb2 guibg=#45403d
    highlight Pmenu       ctermfg=223 ctermbg=237  guifg=#ebdbb2 guibg=#45403d

    lua <<EOF
    require('nvim-treesitter.configs').setup({
      ensure_installed = treesitter_parsers,
      highlight = {
        enable = true,
        additional_vim_regex_highlighting = false,
      },
    })
    EOF

    set list
    set listchars=tab:\ \ ,trail:-,nbsp:+
    highlight IndentBlanklineIndent1 guifg=#70363A gui=nocombine
    highlight IndentBlanklineIndent2 guifg=#72603E gui=nocombine
    highlight IndentBlanklineIndent3 guifg=#4C623C gui=nocombine
    highlight IndentBlanklineIndent4 guifg=#2B5B61 gui=nocombine
    highlight IndentBlanklineIndent5 guifg=#305878 gui=nocombine
    highlight IndentBlanklineIndent6 guifg=#633C6E gui=nocombine
    let g:indent_blankline_char_list = ['|', '¦', '┆', '┊']
    let g:indent_blankline_char_highlight_list = ['IndentBlanklineIndent1', 'IndentBlanklineIndent2', 'IndentBlanklineIndent3',
          \ 'IndentBlanklineIndent4', 'IndentBlanklineIndent5', 'IndentBlanklineIndent6']
    let g:indent_blankline_show_first_indent_level = v:false
    let g:indent_blankline_show_trailing_blankline_indent = v:false
    let g:indent_blankline_use_treesitter = v:true
    let g:indent_blankline_filetype_exclude = ['man', 'help', 'fugitive']
    let g:indent_blankline_buftype_exclude = ['terminal', 'quickfix', 'nowrite']
    let g:indent_blankline_max_indent_increase = 1
    let g:indent_blankline_indent_level = 8
    ```
2. Install the plugins and parsers
3. Save below file as `test.yml`
    ```yaml
    name: Build and Release

    on:
      pull_request:

    jobs:
      build-image:
        steps:
          - name: Run
            run: |
              set -ex

              BRANCH_TAG="$(echo "${GITHUB_HEAD_REF:-$GITHUB_REF}" | sed -e 's/refs\/heads\///' | sed -e 's/\//-/g')"
    ```
4. `nvim -u mini.vim test.yml`

### Expected behavior

No errors

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v20.2.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 14.0.3 (clang-1403.0.22.14.1)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "22.4.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cmake               ✓ . ✓ . .
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - dockerfile          ✓ . . . ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - gomod               ✓ . . . ✓
  - gowork              ✓ . . . ✓
  - haskell             ✓ . ✓ . ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - java                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - kotlin              ✓ ✓ ✓ . ✓
  - latex               ✓ . ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - make                ✓ . ✓ . ✓
  - php                 ✓ ✓ ✓ ✓ ✓
  - proto               ✓ . ✓ . .
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - ruby                ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - scala               ✓ ✓ ✓ . ✓
  - scss                ✓ . ✓ ✓ .
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - vue                 ✓ . ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.9.0/share/nvim"

Run :checkhealth for more info
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lucario387**
Should resolve #4854

### CODE REVIEW

**Review by clason — APPROVED** [review]

**Comment by lucario387** [comment]
Welp somehow lua parser is breaking, without any recent changes.

**Comment by clason** [comment]
Looks to have resolved itself?

**Comment by lucario387** [comment]
> Looks to have resolved itself?

Not really, I'm editing the workflow files directly to surpress/find the bad commit

**Comment by clason** [comment]
You can drop the workflow modification now.

**Comment by lucario387** [comment]
> You can drop the workflow modification now.

Just dropped it

**Pull request merged**
