### PR TITLE
indents(php): @auto on comment and ERROR

### LINKED ISSUE #2873: Wrong indentation in multiline comments with tree-sitter-php
### Describe the bug

Incorrect indentation is inserted to multiline phpdoc comment after installing 'php' extension. The initial indentation does not matter.
```
<?php

/**
*  no leading space here
 */
```

### To Reproduce

1. Open nvim with `nvim-treesitter` installed only and the following minimal config:

```lua
require'nvim-treesitter.configs'.setup {
  indent = {
    enable = true,
  },
}
```
2. Open `test.php` with
```
<?php

/**
 */
```
3. go to the line with `/**` then press `o` to insert some content inside the comment.
4. see that indentation is correct i.e. one leading space is inserted
```
<?php

/**
 *
 */
```
5. undo the change then run `TSInstall php` and repeat step 3. 
6. see no leading space as shown in the description. 

### Expected behavior

The correct amount of spaces is inserted inside the comment. 

In my real environment I have also `phpdoc` installed. Currently it does not support indentation. On the other side it both does not cause this bug and does not fix it. Probably the problem is on nvim-treesitter or treesitter-php side. 

While the bug exists I would like to disable indentation inside PHP comments. I found https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/php/indents.scm#L17-L19 
```
[
  (comment)
] @ignore
```
What does it mean if not what I expect? I am beginner in tree-sitter domain. 

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (ccd6bf554d922596ce905730d98a77af368bba5c) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v17.9.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.                                                                                                        
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Debian 11.3.0-1) 11.3.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - php            ✓ ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```
```


### Output of `nvim --version`

```text
NVIM v0.8.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -ffile-prefix-map=/home/test/dev/external/neovim-launchpad/neovim-0.7.0~ubuntu1+git202204211627-28fb40b16-dd05b3569=. -fstack-protector-strong -Wformat -Werror=format-security -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/test/dev/external/neovim-launchpad/neovim-0.7.0~ubuntu1+git202204211627-28fb40b16-dd05b3569/build/config -I/home/test/dev/external/neovim-launchpad/neovim-0.7.0~ubuntu1+git202204211627-28fb40b16-dd05b3569/src -I/home/test/dev/external/neovim-launchpad/neovim-0.7.0~ubuntu1+git202204211627-28fb40b16-dd05b3569/.deps/usr/include -I/usr/include -I/home/test/dev/external/neovim-launchpad/neovim-0.7.0~ubuntu1+git202204211627-28fb40b16-dd05b3569/build/src/nvim/auto -I/home/test/dev/external/neovim-launchpad/neovim-0.7.0~ubuntu1+git202204211627-28fb40b16-dd05b3569/build/include            
Compiled by test@wc  

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
```


### Additional context

_No response_

### PR DESCRIPTION
**Pull request by przepompownia**
Currently with
```vim
setlocal autoindent
setlocal smartindent
```
in `after/indent/php.vim` it allows correct indentation
inside PHP docblocks.

Closes #2873

### CODE REVIEW

**Review by theHamsta — APPROVED** [review]

**Comment by theHamsta** [comment]
You fixed a failing test. Can you remove the annotation that this test was failing before https://github.com/theHamsta/nvim-treesitter/blob/e2b4e9af48b7008b50f43eaccabe95def0c11288/tests/indent/php_spec.lua#L27 `,  just remove `"shouldn't be 0", XFAIL`

**Review by theHamsta — APPROVED** [review]

**Comment by theHamsta** [comment]
Sorry, I read the test results wrong. Apparently, the failing test is the same as before but `issue-2497.php` is now broken.

**Comment by przepompownia** [comment]
On `unfinished-call.php` both on the test and with vim autoindent + smartindent the actual indentation is `0`.

**Comment by przepompownia** [comment]
I needed a while to read some test internals and ensure what need to be changed. On the other side I tried 
```sh
/usr/bin/nvim --headless --noplugin --cmd 'set rtp+=../plenary.nvim' -u scripts/minimal_init.lua  -c "PlenaryBustedDirectory 'tests/' { minimal_init = './scripts/minimal_init.lua' }"
```
to reproduce CI behavior on my local env but still with no result. On the third side the first PR does not automatically trigger CI tests.

**Comment by theHamsta** [comment]
Here you can set options
https://github.com/theHamsta/nvim-treesitter/blob/934409208d9f0014d43396d64666051361a02743/tests/indent/php_spec.lua#L8-L5 . The following init.lua is used in case you need to adapt the config for php https://github.com/theHamsta/nvim-treesitter/blob/934409208d9f0014d43396d64666051361a02743/scripts/minimal_init.lua#L1

**Comment by theHamsta** [comment]
Apparently it's fixed now. Is it ready to be merged? Thank you for your patience!

**Review by theHamsta — APPROVED** [review]

**Comment by przepompownia** [comment]
@theHamsta thank you for support! From my side it is ready. 

The separate issue can be ability to not disable (auto|smart)indent for specific filetype in the user configuration.

**Pull request merged**
