### PR TITLE
Dedent on end in ruby files

### LINKED ISSUE #2554: Indent is persisting outside node
### Describe the bug

In Ruby a method is defined as follows:

```ruby
def foo
  puts "bar"
end
```

Indenting works correctly creating this method but once you press enter after typing the `d` in `end` the cursor remains indented like inside the method. Instead, the cursor should be dedented back out to the same column as `def` and `end`. 

### To Reproduce

1. Create a ruby file
2. Type `def foo<enter>end<enter>`

### Expected behavior

_No response_

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.1 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v14.17.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 13.0.0 (clang-1300.0.29.3)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - json           ✓ ✓ ✓ ✓ . 
  - markdown       ✓ . ✓ . ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - regex          ✓ . . . . 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - vim            ✓ ✓ . . ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - comment        ✓ . . . . 
  - css            ✓ . ✓ ✓ ✓ 
  - hcl            ✓ . ✓ ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - scss           ✓ . . ✓ . 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - embedded_template✓ . . . ✓ 
  - dockerfile     ✓ . . . ✓ 
  - ruby           ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - python         x x ✓ ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: python(highlights): ...im/0.6.1/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 5423
    python(highlights) is concatenated from the following files:
    | [ERROR]:"/Users/nick/.local/share/nvim/plugged/nvim-treesitter/queries/python/highlights.scm", failed to load: ...im/0.6.1/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 5423
  - ERROR: python(locals): ...im/0.6.1/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 2418
    python(locals) is concatenated from the following files:
    | [ERROR]:"/Users/nick/.local/share/nvim/plugged/nvim-treesitter/queries/python/locals.scm", failed to load: ...im/0.6.1/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 2418
```

### Output of `nvim --version`

```text
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.6.1/share/nvim"

Run :checkhealth for more info
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by npezza93**
Looks like other files have this indent_end that was missing in ruby files. 

Fixes #2554

### CODE REVIEW

**Comment by theHamsta** [comment]
Can you add tests for this? There are a lot of changes to `indent.lua` and your fixes shouldn't be accidentally be broken in future.

**Comment by npezza93** [comment]
Is there any docs around creating indent tests or could you point me to an example PR?

**Comment by theHamsta** [comment]
It's essentially copying this file and rename it to ruby_spec.lua (and all other occurrences of Lua  https://github.com/theHamsta/nvim-treesitter/blob/933c84cb3086413ded0faf443c6c2f97d249f1c9/tests/indent/lua_spec.lua#L1-L16 Then, you can just put files correctly indented files in a `ruby` subfolder. The part with the `runner:new_line` is optional and just describes how much a text should be indented when the mentioned text is added to the file.

Run via `./scripts/run_tests.sh indent/ruby_spec.lua` (you need plenary https://github.com/nvim-lua/plenary.nvim)

**Comment by theHamsta** [comment]
@npezza93 are you planning to add some tests or should we merge?

**Comment by npezza93** [comment]
@theHamsta Yea sorry. I'll work on those tests this week

**Comment by theHamsta** [comment]
Ana updates here? Should we already merge?

**Comment by npezza93** [comment]
Yea feel free too merge. I can work on the tests in a separate PR

**Review by theHamsta — APPROVED** [review]

**Pull request merged**
