### PR TITLE
Update lockfile and parser queries

### PR DESCRIPTION
**Pull request by theHamsta**
This is #531

### CODE REVIEW

**Comment by theHamsta** [comment]
We need to wait for AppImage to build with new runtime.

**Review by vigoux — APPROVED** [review]

**Review by vigoux — APPROVED** [review]

**Comment by vigoux** [comment]
Awesome, are we good then ?

**Comment by theHamsta** [comment]
If it's green, it's green. Was red before :smile:

**Comment by theHamsta** [comment]
Now it should be fine.

**Comment by theHamsta** [comment]
Users need now newest nightly. Or they gonna have a bad time.

**Pull request merged**
