### PR TITLE
fix erratic highlighting of python function arguments

### PR DESCRIPTION
**Pull request by zachliu**
This PR fixed my https://github.com/nvim-treesitter/nvim-treesitter/issues/871#issuecomment-920319185 without other complications so far.

### CODE REVIEW

**Comment by stsewd** [comment]
Unfortunately this isn't a solution, the problem is that the predicate from.the query is getting ignored, this should be solved by https://github.com/neovim/neovim/pull/15316.

**Comment by zachliu** [comment]
> Unfortunately this isn't a solution, the problem is that the predicate from.the query is getting ignored, this should be solved by [neovim/neovim#15316](https://github.com/neovim/neovim/pull/15316).

could you tell me what this query does?

**Comment by stsewd** [comment]
> > Unfortunately this isn't a solution, the problem is that the predicate from.the query is getting ignored, this should be solved by [neovim/neovim#15316](https://github.com/neovim/neovim/pull/15316).
> 
> could you tell me what this query does?

Do you mean the query you are removing? That's to highlight the second argument of `isinstance` as a class. `is isinstance(foo, bar)` here `bar` will be highlighted as a class. The query is fine, but there is a bug on neovim where sometimes the `eq isinstance` part is ignored and that leads to highlight other things as a class.

**Comment by zachliu** [comment]
> > > Unfortunately this isn't a solution, the problem is that the predicate from.the query is getting ignored, this should be solved by [neovim/neovim#15316](https://github.com/neovim/neovim/pull/15316).
> > 
> > 
> > could you tell me what this query does?
> 
> Do you mean the query you are removing? That's to highlight the second argument of `isinstance` as a class. `is isinstance(foo, bar)` here `bar` will be highlighted as a class. The query is fine, but there is a bug on neovim where sometimes the `eq isinstance` part is ignored and that leads to highlight other things as a class.

gotcha! `bar` should be highlighted, this is not the solution :joy_cat:

**Pull request closed without merging**
