### PR TITLE
feat(rust): injections comment in rust

### PR DESCRIPTION
**Pull request by Decodetalkers**
This will highlight code in commend line
image

### CODE REVIEW

**Comment by theHamsta** [comment]
It would be nicer to inject markdown and properly exclude the leading `//!` from the injection ranges but our current code seems to not be able to due this due to bugs in the implementation

**Comment by ObserverOfTime** [comment]
Injecting markdown would not inject rust in unlabelled code blocks.

**Comment by amaanq** [comment]
rust-analyzer does this (albeit at a much higher resource cost than tree-sitter), so I'll mark this as draft until we can exclude the leading //[!/] in every line

**Comment by valpackett** [comment]
> Injecting markdown would not inject rust in unlabelled code blocks.

What would be really great to solve this is an ability to query **into** injected languages' parse trees, so *Rust* injection queries could drill down into Markdown and specify that fenced code blocks without any language name should have Rust injected back into them.

I have a similar use case for this feature in a different context currently, looks like this:

```hcl
code {
  lang = "yaml"
  content = <<-EOT
    this:
    - is
    - yaml: true
      because: "another variable outside of the heredoc says yaml"
      but: {{ templated | with(some: 'template_language') | that_is(always_used_for_strings) }}
  EOT
}
```

and it's sad that I can't write a query in the *host* language that captures the `"yaml"` as an `injection.language` to be used for `(text)` nodes **inside** of the parsed **templating** language.

**Comment by clason** [comment]
Isn't that what `injection.parent` is for?

**Comment by clason** [comment]
> It would be nicer to inject markdown and properly exclude the leading `//!` from the injection ranges but our current code seems to not be able to due this due to bugs in the implementation

This ☝️ is the way to go here (using `injection.parent`).

**Pull request closed without merging**
