### PR TITLE
feat: add Objective-C

### PR DESCRIPTION
**Pull request by amaanq**
All I can say is I see why this was deprecated in favor of Swift

Objective-C++ is another hell to endure after this :grin:

### CODE REVIEW

**Review by lucario387 — COMMENTED** [review]
Reading through the introduction, I can already see why this is hell.

Doesn't think it will be fully compatible with C-style indents though

**Comment by amaanq** [comment]
it's not but most indents stem from compound statements

**Review by lucario387 — APPROVED** [review]
I trust my C indents to not break, I hope

**Comment by ObserverOfTime** [comment]
> Objective-C++ is another hell to endure after this

Does anyone even use Objective-C++?

**Review by ObserverOfTime — APPROVED** [review]

**Comment by amaanq** [comment]
> > Objective-C++ is another hell to endure after this
> 
> Does anyone even use Objective-C++?

I'm sure one random archaic apple dev does, it's quite literally Objective-C and C++ combined :laughing:

**Pull request merged**
