### PR TITLE
feat(cpp): simplify namespace query rules now that parser is a bit more consistent

### PR DESCRIPTION
**Pull request by jdrouhard**
Most recent parser version [0b6d0eb9abdf7cea31961cd903eeed5bbd0aae74](https://github.com/tree-sitter/tree-sitter-cpp/commit/0b6d0eb9abdf7cea31961cd903eeed5bbd0aae74) improves the node tree related to namespaces. This deprecates the need for extra rules to try to get @namespace applied to the right nodes.

also, `namespace_identifier` can't name a constant since it only names things guaranteed to be namespaces, or type/enums when in a qualified identifier as part of scope resolution.

### CODE REVIEW

**Comment by amaanq** [comment]
update the lockfile to point to that revision

**Comment by jdrouhard** [comment]
> update the lockfile to point to that revision

Should say that this query will work just fine with the current version, it just won't look quite as nice until that other commit. Required was maybe too forceful. I don't mind waiting on the github action to update it in the normal course of things.

**Comment by amaanq** [comment]
Kotlin is breaking the lockfile update but I'll probably hotfix that shortly, up to you

**Review by amaanq — APPROVED** [review]

**Comment by amaanq** [comment]
query test is failing

**Comment by jdrouhard** [comment]
Cuda and hlsl need to be updated as well, I guess?

**Comment by amaanq** [comment]
> Cuda and hlsl need to be updated as well, I guess?

not familiar with these, but probably...

@theHamsta

**Comment by theHamsta** [comment]
I have a cron workflow updating cuda and half for CPP updates. I've already updated cuda.  Hlsl only has a 24h cadence so I will trigger manually now. Should be fine to also update them in a few minutes to their newest version

**Comment by amaanq** [comment]
Arduino needs an update as well

@ObserverOfTime

**Pull request merged**
