### PR TITLE
injections(query): add `#gsub!` pattern

### PR DESCRIPTION
**Pull request by lucario387**
Example: 

image

### CODE REVIEW

**Comment by clason** [comment]
I'm always a bit concerned about the performance of these complex injections; could you say something about that?

**Comment by lucario387** [comment]
I cannot really say anything, how exactly should/can I even perf these queries, though?

**Comment by clason** [comment]
We need benchmarks... But for now, just anecdotal evidence ("I tested editing a reasonably large query before and after and didn't notice any lag") is sufficient.

**Review by theHamsta — APPROVED** [review]

**Comment by clason** [comment]
@lucario387 a number of indentation tests are failing on the branch (unrelated to this PR) -- could you take a look at those when you have time?

**Comment by amaanq** [comment]
I don't think performance would be an issue, is anyone writing thousand line query files with many potential injection candidates? ;) on a related note, a good consistent benchmarking ci tool would be nice...

**Pull request merged**
