### PR TITLE
lint(locals): use `#set!` to keep query linter happy

### PR DESCRIPTION
**Pull request by clason**

### CODE REVIEW

**Review by amaanq — APPROVED** [review]

**Comment by clason** [comment]
Wait, that can't be it -- the other local queries also have `set!`, and the query check still fails locally.

**Comment by clason** [comment]
Looks like these two are breaking (locally on main, so probably due to the refactor):
```lisp
(namespace_definition
  name: (namespace_identifier) @definition.namespace
  body: (_) @scope)

(namespace_definition
  name: (nested_namespace_specifier) @definition.namespace
  body: (_) @scope)
```

**Comment by clason** [comment]
@ObserverOfTime

**Comment by ObserverOfTime** [comment]
Works on my machine. :thinking: 

```
$ nvim -l scripts/check-queries.lua 
::group::Check parsers
Checking arduino highlights (131.52ms)
Checking arduino locals (34.48ms)
Checking arduino folds (10.35ms)
Checking arduino indents (19.01ms)
Checking arduino injections (6.30ms)
```

**Pull request merged**
