### PR TITLE
feat: Add Robot Framework parser and highlights

### PR DESCRIPTION
**Pull request by ema2159**
Added a parser and syntax highlighting for Robot Framework files.
The parser seems to be very basic, but sufficient, as it was added to Helix not so long ago [here](https://github.com/helix-editor/helix/pull/6611).

Let me know if anything else is needed.

### CODE REVIEW

**Comment by amaanq** [comment]
Need an entry in lockfile.json

**Comment by ema2159** [comment]
Hello @amaanq. Would you point me out where should I generate that or what should I put into it? Thanks.

**Comment by lucario387** [comment]
It's in `lockfile.json` @ema2159. You can generate the file by having `jq` and using `scripts/write-lockfile.lua` in this repo.

For the queries, please reverse the order of the captures, as all captures defined in the file will be applied, so the one defined last wins.

**Comment by clason** [comment]
Please don't change unrelated lock file entries. Those changes could be (and I this case in fact are) are breaking and cannot be merged.

**Comment by ema2159** [comment]
Hello @lucario387. Thanks a lot for your feedback. Regarding the locker file, I did as you stated (thanks @clason for the heads up). As per the order of the captures I don't quite understand (my apologies, I'm new to Treesitter). Do you want me to set the queries as follows?

``` scheme
(argument (dictionary_variable) @string.special)
(argument (list_variable) @string.special)
(argument (scalar_variable) @string.special)
(argument (text_chunk) @string)

(keyword_invocation (keyword) @function)

(test_case_definition (name) @property)

(keyword_definition (body (keyword_setting) @keyword))
(keyword_definition (name) @function)

(variable_definition (variable_name) @variable)

(setting_statement) @keyword

(extra_text) @comment
(section_header) @keyword

(ellipses) @punctuation.delimiter
(comment) @comment
```

**Comment by lucario387** [comment]
Yes, basically the order of the captures should be reversed like how you commented

**Comment by ema2159** [comment]
@lucario387 done. Anything else please just let me know and I will gladly collaborate.

**Review by lucario387 — APPROVED** [review]

**Comment by lucario387** [comment]
I'm personally fine with these changes

**Comment by clason** [comment]
Do you want to add injections, indents, or folds?

**Comment by ema2159** [comment]
@clason Not at the moment. I can look into it later on but at the moment I think is good to at least have syntax highlighting support for the language.

**Pull request merged**
