### PR TITLE
cpp: fix for breaking changes in tree-sitter-cpp

### PR DESCRIPTION
**Pull request by jdrouhard**
These are fixes for the breaking changes in tree-sitter/tree-sitter-cpp#133

### CODE REVIEW

**Comment by theHamsta** [comment]
Can you change the lockfile.json so that the CI passes?

**Comment by theHamsta** [comment]
Sorry, I still need to update the cuda parser. I will update the SHA as soon as it is ready!

**Comment by theHamsta** [comment]
Do we have to change something for the user-defined literals PR?

**Comment by jdrouhard** [comment]
> 
> 
> Do we have to change something for the user-defined literals PR?

No, that one shouldn't have had any breaking changes. You can add highlights for the new identifiers if you want, but I'm not sure what groups they'd be assigned to.

**Comment by jdrouhard** [comment]
CI seems to be unable to find the nightly neovim release? Did neovim stop publishing nightlies?

**Comment by theHamsta** [comment]
The CI to publish the nightlies fails from time to time. It should be back again tomorrow

**Comment by maxbrunsfeld** [comment]
⚡ nice work on this @jdrouhard

**Review by theHamsta — APPROVED** [review]

**Pull request merged**
