### PR TITLE
feat(mergify): delay mergify merging by one day

### PR DESCRIPTION
**Pull request by vigoux**
This will avoid merging too rapidly.

### CODE REVIEW

**Comment by vigoux** [comment]
Actually delay by 2 hours, to avoid blocking things unnecessarily.

**Comment by vigoux** [comment]
@theHamsta what do you think about that ?

**Review by theHamsta — COMMENTED** [review]
I guess with two approvals we can merge immediately. With only one approval I would have a longer delay. I'm fine both strategies

**Comment by vigoux** [comment]
How much delay do you want?

**Comment by vigoux** [comment]
So the new rule for auto-merge is the the following (with those two, add the classic "not a draft and no pending reviews").
- If there is two approvals, merge immediately
- If there is only one approval, comment now that the PR will be merged soon, and merge one day after that

**Review by theHamsta — APPROVED** [review]

**Pull request merged**
