### PR TITLE
add rescript in ftdetect

### PR DESCRIPTION
**Pull request by ri7nz**

### CODE REVIEW

**Comment by theHamsta** [comment]
See #2259

**Comment by theHamsta** [comment]
Do we even have a rescript parser?

**Comment by ri7nz** [comment]
@theHamsta  I'm use with this https://github.com/nkrkv/tree-sitter-rescript/commits/main

**Comment by theHamsta** [comment]
Can you create a PR for vim to recognize this file type and and a PR here to support the parser?

**Comment by ri7nz** [comment]
Okay 👍  Where's the repository for PR to vim ? 

For the parser, I'm new in `treesitter` stuff, could you give me some resource such a docs for me to read?

**Comment by theHamsta** [comment]
@ri7nz GitHub.com/vim/vim. Just have a look at parsers.lua. It should be apparent from the other entries which meta data is necessary to install the parser. Infos about queries are in contributing.md but queries can be a separate PR.

**Comment by ri7nz** [comment]
@theHamsta  I will make a PR later, thank you for insight.

**Pull request closed without merging**
