### PR TITLE
feat(markdown_inline): add queries for wiki links and tags

### PR DESCRIPTION
**Pull request by musjj**
Still new to treesitter queries, feedback would be appreciated.
image

### CODE REVIEW

**Comment by amaanq** [comment]
this will fail ci as we don't compile with these options on, but you're free to add these in your own config extending nvim ts

**Comment by musjj** [comment]
Alright.
I added them to my `~/.config/nvim/after/queries/highlights.scm` instead but it doesn't seem to work. I ran `vim.api.nvim_get_runtime_file("queries/*/*.scm", true)` and my path was listed there, but the highlights doesn't seem to be working.

**Comment by amaanq** [comment]
First thing I noticed is that it should be in `queries/markdown/highlights.scm`, and if that doesn't fix it then did you add `; extends` at the top of the file? Lastly, not sure if it needs to be in after but that should work either way I'd guess

**Comment by musjj** [comment]
The `; extends` did the trick, thanks!

**Pull request closed without merging**
