### PR TITLE
Add method reference operator

### PR DESCRIPTION
**Pull request by PitcherTear22**

### CODE REVIEW

**Comment by PitcherTear22** [comment]
huh

**Comment by PitcherTear22** [comment]
whats wrong

**Comment by theHamsta** [comment]
It's best for a PR that you create a branch for it.

To get back to current master:
```bash
git remote add upstream git@github.com:nvim-treesitter/nvim-treesitter.git
git fetch upstream
git checkout master && git reset upstream/master
```

**Comment by PitcherTear22** [comment]
Thanks!

**Comment by theHamsta** [comment]
Thanks for your contributions!

**Pull request closed without merging**
