### PR TITLE
fix(windows): fix invalid powershell separator during install

### PR DESCRIPTION
**Pull request by adam-wolski**
Fixes nvim installation on vim configuration that use powershell.

Fixes https://github.com/nvim-treesitter/nvim-treesitter/issues/3316 
Maybe fixes https://github.com/nvim-treesitter/nvim-treesitter/issues/1965

There's a similar pull request here https://github.com/nvim-treesitter/nvim-treesitter/pull/4365 but [has potential problems](https://github.com/nvim-treesitter/nvim-treesitter/pull/4365#issuecomment-1445416964)

### CODE REVIEW

**Comment by theHamsta** [comment]
This is kind of a duplicate for https://github.com/nvim-treesitter/nvim-treesitter/pull/4365. Main problem is that shell == `powershell` or `shell==cmd` is not reliable. shell ==cmd is better as it is the default. But `powershell` can be `powershell` for Windows `powershell` or `pwsh` if user installed or a complete path to `pwsh` if it hasn't been added to path. Preferably, `cwd` would be implemented by just using always either `cmd` or `powershell` or some other trick to ensure the working directory of the current command.

The original form of https://github.com/nvim-treesitter/nvim-treesitter/pull/4365 was `if shell == "cmd"` which I think we could merge as it is at least more reliable than `if shell = "powershell"` (I personally use `pwsh`).

**Comment by adam-wolski** [comment]
> This is kind of a duplicate for #4365. Main problem is that shell == `powershell` or `shell==cmd` is not reliable. shell ==cmd is better as it is the default. But `powershell` can be `powershell` for Windows `powershell` or `pwsh` if user installed or a complete path to `pwsh` if it hasn't been added to path. Preferably, `cwd` would be implemented by just using always either `cmd` or `powershell` or some other trick to ensure the working directory of the current command.
> 
> The original form of #4365 was `if shell == "cmd"` which I think we could merge as it is at least more reliable than `if shell = "powershell"` (I personally use `pwsh`).
> 
> EDIT: you have `pwsh` in your check. Could we change that to that the last path segment contains either of the two? So it would also work with `pwsh.exe` or `C:\foo\path\to\pwsh.exe`

We could check for `shell==cmd` and if not then we do powershell way.

**Review by theHamsta — APPROVED** [review]
Ok, not perfect. Maybe we can merge this as a quick fix. @amaanq  what do you think is `vim.o.shell = "cmd"` reliable enough or will there be people with shell == `"cmd.exe"`

**Comment by amaanq** [comment]
I don't use windows, but maybe just checking if it starts with cmd would work?

**Comment by adam-wolski** [comment]
I've changed it to finding `cmd` in the shell variable.

**Comment by amaanq** [comment]
The plights of windows..thanks for your contribution!

**Pull request merged**
