### PR TITLE
[cmake] add highlights for `add_custom_target` and `add_custom_command`

### PR DESCRIPTION
**Pull request by uyha**

### CODE REVIEW

**Review by theHamsta — APPROVED** [review]

**Comment by uyha** [comment]
oops, I misclicked auto merge, @theHamsta can you enable that again?

**Comment by stsewd** [comment]
@uyha looks like there are some conflicts you need to resolve before we can merge this

**Comment by theHamsta** [comment]
Can you please try to resolve the new conflicts?

**Comment by uyha** [comment]
I just push a commit to resolve them, can you have a look again?

**Comment by theHamsta** [comment]
It still says it has conflicts. Can you really try to rebase on newest master (not merge)?

**Comment by uyha** [comment]
Ok, i will try

**Comment by theHamsta** [comment]
Now it worked! :tada:

**Pull request merged**
