### PR TITLE
refactor: remove support for 0.8 for indents

### PR DESCRIPTION
**Pull request by lucario387**
The minimum supported version is already 0.9, no need to keep the compatibility functions anymore

### CODE REVIEW

**Comment by clason** [comment]
I have actually not planned to make any changes in this regard, since it will make rebasing `main` (the _real_ "drop obsolete code" refactor) quite a bit harder...

**Comment by lucario387** [comment]
I will close this then.

**Comment by clason** [comment]
But if this code is actually harmful (and not just esthetically displeasing), that would be a different issue!

**Comment by lucario387** [comment]
I don't see how it's harmful (yet).

**Pull request closed without merging**
