### PR TITLE
fix: check if invalidate_query_cache[lang] is set before invalidating

### LINKED ISSUE #1444: Healthcheck error
**Describe the bug**

Whenever `checkhealth` is run the second time it shows the following error. I guess this started happening after 90024c24aaef98065579173a75acf59c8f132af8

image

**To Reproduce**

1. Open nvim 
2. Type `:checkhealth`
3. Close the health tab
4. Type `:checkhealth` again
5. See error

**Expected behavior**
Health checks should be displayed

<details>
<code>
 
 health#nvim_treesitter#check
  ========================================================================
    - ERROR: Failed to run healthcheck for "nvim_treesitter" plugin. Exception:
      function health#check[21]..health#nvim_treesitter#check, line 1
      Vim(lua):E5108: Error executing lua ...packer/opt/nvim-treesitter/lua/nvim-treesitter/query.lua:104: attempt to index a nil value

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

NVIM v0.5.0-dev+1451-g785dcff90
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/home/elric/workspace/repos/neovim/build/config -I/home/elric/workspace/repos/neovim/src -I/home/elric/workspace/repos/neovim/.deps/usr/include -I/usr/include -I/home/elric/workspace/repos/neovim/build/src/nvim/auto -I/home/elric/workspace/repos/neovim/build/include
Compiled by root

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info

</code>
</details>

**Additional context**

### PR DESCRIPTION
**Pull request by folke**
Check for `nil` is needed

Fixes #1444

### CODE REVIEW

**Review by stsewd — APPROVED** [review]

**Comment by stsewd** [comment]
I think the CI error is because builds from mac are falling. @vigoux may be able to merge this with his admin powers. We could also implement the workaround from https://github.com/neovim/neovim/pull/14915#issuecomment-869802740

**Comment by folke** [comment]
@stsewd yeah, it is https://github.com/nvim-treesitter/nvim-treesitter/blob/fe47dbe02bc243315ee185e9dc9c68b4e9dc70b2/scripts/ci-install-macos-latest.sh#L3

That could probably be replaced by the following, until homebrew fixes it:

```
brew tap jason0x43/homebrew-neovim-nightly
brew install --cask neovim-nightly
``

**Comment by theHamsta** [comment]
Merged this as a hot fix even with Homebew CI failing.

**Comment by folke** [comment]
@theHamsta awesome, thanks!

**Pull request merged**
