### PR TITLE
feat: add asciidoc parser

### PR DESCRIPTION
**Pull request by ObserverOfTime**
The [parser](https://github.com/cathaysia/tree-sitter-asciidoc) is still a WIP and the [fork](https://github.com/cpkio/tree-sitter-asciidoc) is…worse.
Just leaving this here for later since I gave it a try.

### CODE REVIEW

**Comment by clason** [comment]
@ObserverOfTime what's the current state? Is this worth keeping open?

**Comment by ObserverOfTime** [comment]
The WIP master branch hasn't been updated in 7 months, the WIP rewrite in the adoc branch hasn't been updated in 2 months, and the WIP fork hasn't been updated in 5 months. None of them are currently usable.

**Comment by cpkio** [comment]
I'm the developer of this parser. Totally rewriting in now in C, it is already in decent state. Will PR when ready and feature complete.

The format is complex and convoluted. I would love if community could provide lots of test cases.

Also, I still would like some user input regarding highligher groups and other stuff.

**Comment by clason** [comment]
There's not much user input; the captures to use are fully documented in CONTRIBUTING.md; using these (as indicated) is mandatory for a language to be included here. Feel free to ask specific questions on your PR (and you will get feedback anyway).

**Pull request closed without merging**
