### PR TITLE
feat(query): highlight parameters as `@parameter`

### PR DESCRIPTION
**Pull request by Akmadan23**
I feel like this just makes sense, and it's something that was missing.

### CODE REVIEW

**Comment by clason** [comment]
How so? There's more targeted captures for the components of  this node.

**Comment by Akmadan23** [comment]
Well, the only query that involves parameters highlights them only if they are numbers, whereas in something like `(#set! conceal "whatever")` the parameter (`conceal`) is not captured.

**Comment by clason** [comment]
Please show a concrete example that currently is not correctly highlighted.

**Comment by clason** [comment]
OK, but this specific example shouldn't be a `@parameter` -- it's an `identifier` (which usually isn't highlighted specifically).

**Comment by Akmadan23** [comment]
> it's an `identifier` (which usually isn't highlighted specifically)

Exactly, I probably said it wrong, but the fact is that identifiers inside a `parameters` group are not highlighted unless they're numbers.

> OK, but this specific example shouldn't be a `@parameter`

Why tho? How would you highlight it?

**Comment by clason** [comment]
Not at all, or `@identifier`. Parameter is simply wrong.

**Comment by Akmadan23** [comment]
Alright, so if I replace `@parameter` with `@identifier` it should be ok, right?

**Comment by clason** [comment]
`@variable`, if anything. Still not convinced that this is a good idea, though.

**Comment by lucario387** [comment]
This is capturing only `(identifier)` though. But still, I'm also not convinced. This capture, from what I can tell, is only the `(#set! identifier identifier ...)`. But this can either be a string, a number, or a named node. And there is zero way to distinguish named nodes and strings from the parser's view, so I don't see how highlighting a string in a different color helps

**Comment by Akmadan23** [comment]
Ok, I didn't consider the ambiguity of the various `(identifier)`s here. Sorry for the inconvenience

**Comment by amaanq** [comment]
You can always extend ts queries to have it in your own config

**Comment by Akmadan23** [comment]
> You can always extend ts queries to have it in your own config

Yeah, that's exactly what I was doing and continue to do.

**Pull request closed without merging**
