### PR TITLE
injections(lua): highlight string as `query` if starts with `;; query`

### PR DESCRIPTION
**Pull request by numToStr**
Before and After

image

### CODE REVIEW

**Comment by savq** [comment]
Should this allow any number of leading semi-colons? ~Scheme~ the query language only requires one semi-colon for comments. Is there any reason in particular 2 should be preferred for this?

**Comment by numToStr** [comment]
> Is there any reason in particular 2 should be preferred for this?

Nope no particular reason.

> Should this allow any number of leading semi-colons? the query language only requires one semi-colon for comments.

Yeah, I could change this to accept multiple leading semi colons.

**Comment by numToStr** [comment]
@savq I changed it to accepts one or more leading `;`

**Review by theHamsta — APPROVED** [review]
We had some performance problems with regexes. But strings are probably not that frequent and Lua regexes generally fast (I hope this not for usage for `set_query`. I think we failed at some point when you want to write longer queries in Lua vs dedicated files. We need to improve the query-runtimepath experience )

**Pull request merged**
