### PR TITLE
Feature: Add Surface language and integrate with Elixir

### PR DESCRIPTION
**Pull request by connorlay**
[Surface](https://surface-ui.org/) is a template language and component library for Elixir and Phoenix LiveView. The syntax is like JSX, but for Elixir!

I created a new Surface [grammar](https://github.com/connorlay/tree-sitter-surface) and and I am happy with the results so far. This PR adds the necessary integration and queries to support using the grammar with NeoVim.

The grammar does not call any external scanners and it should be fairly stable at this point, save for any upstream changes to the language itself. I based the highlights and other queries on the existing work for Elixir, HTML, and JSX.

Additionally, I added ftdetect files for Elixir and Surface, and fixed a small bug with how Elixir highlights function call identifiers when the remote is a variable.

This is my first time authoring a Tree-sitter grammar, any feedback is greatly appreciated 😄

### CODE REVIEW

**Comment by theHamsta** [comment]
@nifoc

**Review by theHamsta — COMMENTED** [review]
Looks good to me! Thanks for your contribution! Let's wait for @nifoc 's opinion as he is our elixir expert

**Comment by theHamsta** [comment]
Is it possible that all the Node parsers are failing due to the added node action? But there all the parsers compiled...

**Comment by nifoc** [comment]
The Elixir changes LGTM ❤️ 

(I don't use Surface, so I can't comment on that)

**Review by theHamsta — APPROVED** [review]

**Comment by stsewd** [comment]
> Maybe only do this check on Ubuntu @stsewd ?

sorry, little late replying here, now the other PR makes more sense ha. @connorlay looks like you only need to merge/rebase with master and tests should pass.

We could also get the list of parsers that are declared and not only the ones installed to check for injections.

**Comment by connorlay** [comment]
@stsewd Done! 

> We could also get the list of parsers that are declared and not only the ones installed to check for injections.

I don't follow... are you referring to CI or something specific with this PR?

**Comment by stsewd** [comment]
> I don't follow... are you referring to CI or something specific with this PR?

to our CI, I think https://github.com/nvim-treesitter/nvim-treesitter/pull/1651 should make the tests pass

**Comment by stsewd** [comment]
@connorlay sorry for pinning you again, but I think merging master should make the CI happy again

**Pull request merged**
