### PR TITLE
Fix language injection for markdown code blocks

### PR DESCRIPTION
**Pull request by MDeiml**
Related to https://github.com/MDeiml/tree-sitter-markdown/issues/14. I introduced a new node in my grammar which is only the language part of the info string. We need to change the injection query to use this new node.

I'm not familiar with how nvim-treesitter chooses the commit from which to install a language. I think the node is not part of the commit that is currently used. Is it safe to reference it in the query files like this? Or do I need to trigger some other process first, so the newest commit of the parser gets used?

### CODE REVIEW

**Comment by theHamsta** [comment]
It chooses the version in `lockfile.json` so you would need to bump it. Normally, after every commit to master to our repo a PR is created which contains all the updated revisions from the parser repo.

**Comment by stsewd** [comment]
From the example and description of https://github.com/MDeiml/tree-sitter-markdown/issues/14

> Only the first word of the info string should be treated as a language

I think that part should be managed by nvim-treesitter rather than your parser, this is finding the language inside the captured node instead of taking it literally. But if it's part of the spec that always the first part is the language name, then it should be on the parser.

**Comment by MDeiml** [comment]
It is actually part of the markdown spec (see https://github.github.com/gfm/#example-113), but maybe it still makes sense for nvim-treesitter to try and extract a valid language. This would also have prevented problems with https://github.com/neovim/neovim/pull/16668 where neovim didn't handle invalid languages properly.

**Comment by MDeiml** [comment]
The tests should now pass. I understand I need approval to rerun them?

**Review by theHamsta — APPROVED** [review]

**Pull request merged**
