### PR TITLE
feat(query)!: upstream changes

### PR DESCRIPTION
**Pull request by amaanq**
pending https://github.com/tree-sitter-grammars/tree-sitter-query/pull/36

### CODE REVIEW

**Comment by lucario387** [comment]
Oh this will be a lot...

**Comment by amaanq** [comment]
lint fails because it uses neovim w/ the bundled parser I think

**Comment by clason** [comment]
And now you see why I'm so hesitant to make breaking changes to that parser...

**Comment by clason** [comment]
I guess we need to add a `:TSInstallSync query` step to the lint workflow.

**Comment by clason** [comment]
Not sure how to do this on `main`, though. I'll make a tree-sitter-query release and bump the parser in Neovim (nightly and release).

**Pull request merged**
