### PR TITLE
feat(swift): add init/deinit indents

### PR DESCRIPTION
**Pull request by lucario387**

### CODE REVIEW

**Comment by lucario387** [comment]
Wing just keep failing :angry: 

@clason This already fixes the indent tests for swift but wing just says no

**Review by clason — APPROVED** [review]

**Comment by clason** [comment]
Why is the wing test suddenly failing?

**Comment by lucario387** [comment]
I don't know :) 
It just happens to fail across PRs

**Comment by clason** [comment]
It's a tree-sitter error:
```
Error processing rule _escape_sequence
Caused by:
    regex parse error:
        u{[0-9a-fA-F]+}
          ^
    error: repetition quantifier expects a valid decimal
Error detected while processing command line:
Error during "tree-sitter generate"
```
(I _hate_ that the compile step never reports failures!)

**Comment by lucario387** [comment]
Can we do a dumb counting of "list of uninstalled parsers" and use it as exit code? 🤔

**Comment by clason** [comment]
We'd probably need to adapt this every time we add parsers?

I think it's better to abort(?) or at least keep track of a bool if the exit code is nonzero (or just sum the exit code of each job).

**Pull request merged**
