### PR TITLE
chore: remove most ftdetect plugins

### PR DESCRIPTION
**Pull request by theHamsta**
Native support for Neovim will be added in https://github.com/neovim/neovim/pull/17180
Most other filetypes are added in https://github.com/neovim/neovim/pull/17182

Should we remove the ftplugin now or just collect them in this PR and merge on release of the Neovim stable?

Fixes https://github.com/nvim-treesitter/nvim-treesitter/issues/2342
Fixes https://github.com/nvim-treesitter/nvim-treesitter/issues/2259

### CODE REVIEW

**Comment by dundargoc** [comment]
You should collect them and merge when I'm done porting them to vim and neovim, which is soon.

**Review by stsewd — APPROVED** [review]

**Comment by dundargoc** [comment]
All ftdetects are included in this pr: https://github.com/neovim/neovim/pull/17182 except for

- `query.vim` which has vimscript which I can't read.
- parts of `hcl.vim`. There's already another filetype ending with  ".ts" so Bram suggested one need to parse the file to determine what file it is. That requires vimscript which I can't read.

If anyone wanna take care of those two you're more than welcome to.

**Comment by theHamsta** [comment]
Still need to decide whether to merge that immediately or when Neovim 0.7.0 gets released.

**Comment by clason** [comment]
I think `query.vim` is just `.*/queries/.*%.scm` (i.e., any scheme file under `*/queries`, right?

I don't think this is relevant to Vim, so I'd just put this into our `filetype.lua`.

The `terraform` check needs someone familiar with that filetype (and the TF mud client -- good luck with that...)

Arguably, we could just make the change in filetype.lua and live with the divergence.

I'd open a separate PR for that and tag gpanders.

**Comment by dundargoc** [comment]
Aha, so the `query.vim` is unique to nvim-treesitter then? Maybe we should just leave it be in `ftdetect` since it's a filetype unique to nvim-treesitter and not a "real" filetype?

> The `terraform` check needs someone familiar with that filetype (and the TF mud client -- good luck with that...)
> Arguably, we could just make the change in filetype.lua and live with the divergence.

That is a question you and @gpanders is best qualified to answer. I'd be willing to spend a little bit of time researching TF mud client files and see if I can find an easy distinguisher if it helps you keep in sync with vim's filetype detection.

> I'd open a separate PR for those two and tag gpanders.

Agree.

**Comment by theHamsta** [comment]
We need to add the ftdetct the test config to let tests pass or wait for the new stable release

**Comment by clason** [comment]
I think this is done now.

**Pull request closed without merging**
