### PR TITLE
feat: add func

### PR DESCRIPTION
**Pull request by amaanq**
cc: @liketurbo since he first requested it in #2282 

This PR adds support for FunC: https://ton.org/docs/develop/func/overview

Unfortunately the original parser I forked from seems to be inactive, so for now I'll point to my fork until my PR fixing a bunch of issues is merged.

Thanks,
Amaan

### CODE REVIEW

**Comment by amaanq** [comment]
Unrelated, but I find the current parsers.lua to be a bit messy, it'd be nice to alphabetize them like in the README. If I fix that, would that PR be merged? Asking now so I don't waste time

**Comment by ObserverOfTime** [comment]
> Unrelated, but I find the current parsers.lua to be a bit messy, it'd be nice to alphabetize them like in the README. If I fix that, would that PR be merged? Asking now so I don't waste time

I was planning on doing that eventually but you can go ahead if you want.

**Review by ObserverOfTime — COMMENTED** [review]
I don't like tabs. :)

**Comment by amaanq** [comment]
> > Unrelated, but I find the current parsers.lua to be a bit messy, it'd be nice to alphabetize them like in the README. If I fix that, would that PR be merged? Asking now so I don't waste time
> 
> I was planning on doing that eventually but you can go ahead if you want.

sure, after this is merged I'll do that then :)

while we're at it, I don't really use tree-sitter folds or folds in general really, so I've never been able to quite figure out how they work. do I fold a grammar rule that begins and ends with brackets of sorts? or do I include any keywords/identifiers before that, 

e.g. which of the following rules should be `@fold`?

section Main {
    ....data....
}

or

Main {
    ....data....
}

or

    {
    ....data....
}

sorry for the ugly examples 😅

**Comment by amaanq** [comment]
> I don't like tabs. :)

Fixed

**Comment by ObserverOfTime** [comment]
> e.g. which of the following rules should be `@fold`?

Try them and see which one makes sense. ¯\\_(ツ)\_/¯

**Review by ObserverOfTime — APPROVED** [review]

**Comment by amaanq** [comment]
> > e.g. which of the following rules should be `@fold`?
> 
> Try them and see which one makes sense. ¯\\_(ツ)\_/¯

sure, I'll play around w/ it this weekend

**Pull request merged**
