### PR TITLE
feat: add swift indents

### PR DESCRIPTION
**Pull request by lucario387**
neovim/neovim#23465 :D 

@Saafo have a look and check

Argument list is actually not marked, so ignoring it for now

To have a better interactive experience while trying out this PR, I'd suggest adding `vim.opt_local.indentkeys:append({"0>", "0@"})` to `ftplugin/swift.lua`

### CODE REVIEW

**Comment by Saafo** [comment]
Sorry! I think I'm not qualified enough to check this lol since I'm not familiar with the scm and how the treesitter indent is working. Please involve someone more professional!

**Comment by clason** [comment]
You can at least try it out and see if the behavior is what you want!

**Comment by lucario387** [comment]
> Sorry! I think I'm not qualified enough to check this lol since I'm not familiar with the scm and how the treesitter indent is working. Please involve someone more professional!

You don't need to care about the queries itself, just checkout to the branch and see if the behavior is to your likings, and whether it conforms the convention of the language or not. I'd assume you are using it on the daily, you'd know more on what's right or wrong. I am only basing the queries from the example code on https://docs.swift.org

**Comment by Saafo** [comment]
Not sure the branch spelling mistake `switfer` matters 🤣

**Comment by lucario387** [comment]
> Not sure whether the branch spelling mistake `switfer` matters rofl

Maybe, maybe not :)

**Comment by lucario387** [comment]
@alex-pinkus Sorry for the interruption, but can you have a look at this PR? It'd be nice to have your opinions on this

**Comment by Saafo** [comment]
@lucario387 not sure whether we can achieve this(seems VSCode doesn't support it, only Xcode support):

```swift
func test3(test: Int, bb: Int) -> Int {
    return 0
}
```

when change a new line after `,`, before `bb`, in Xcode, the `bb` parameter will align with the first `test` parameter:

```swift
func test3(test: Int,
           bb: Int) -> Int {
    return 0
}
```

**Comment by lucario387** [comment]
Yes we can

**Comment by Saafo** [comment]
Another bad case I've found:

```swift
 1111 + 2222 + 3333
```

when change a new line after `2222`, in Xcode and VSCode:

```swift
1111 + 2222
+ 3333
```

current:

```swift
1111 + 2222
    + 3333
```

**Comment by lucario387** [comment]
Resolved all 3 cases above, probably

**Comment by Saafo** [comment]
Met more bugs editing SwiftUI(Swift DSL, i.e. Swift result builders) files:

expected:

```swift
Text("Hamlet")
    .font(.title)
```

current(just type in order, like `Hamlet`, `"`, `)`, `\n`, `.font`, you will find that the indent is wrong, however, when type `Hamlet").font(.title)` and then change a new line between `)` and `.font` works):

```swift
Text("Hamlet")
.font(.title)
```

and continue to change a new line after `.font(.title)`, the indent is:

```swift
Text("Hamlet")
.font(.title)
    //HERE
```

if I continue to call a funtion in the new line, the indent is correct, like:

```swift
Text("Hamlet")
.font(.title) // this line is wrong
    .italic() // this line is correct
```

However, if I add another Text:

```swift
Text("Hamlet")
.font(.title) // this line is wrong
    Text("another") // this line is also wrong
```

which is expected as:

```swift
Text("Hamlet")
    .font(.title)
Text("another")
```

**Comment by Saafo** [comment]
But I think it's ok with the result builder problem not solved if it's too difficult since normal people wouldn't edit SwiftUI files in normal editors.

**Comment by lucario387** [comment]
> Met more bugs editing SwiftUI(Swift DSL, i.e. [Swift result builders](https://www.swiftbysundell.com/articles/deep-dive-into-swift-function-builders/)) files:

This is kindof a rough case, ngl. Interactively, it's hard. Once it's structured then `=iB` should fix it back to the correct position

**Comment by Saafo** [comment]
> Another bug about generic:
> 
> expected:
> 
> ```swift
> struct Reg<
>     Output
> > {
>     var test = 1
> }
> ```
> 
> current:
> 
> ```swift
> struct Reg<
>     Output
>         > {
>     var test = 1
> }
> ```

If I input this in order, like: `Reg<`, `\n`, `Output`, `\n`, `> {`, `\n`, the `Output` is still incorrect:

current:

```swift
struct Reg<
Output // should indent here
> {
    var bbb = 2
}
```

expected:

```swift
struct Reg<
    Output
> {
    var bbb = 2
}
```

**Comment by Saafo** [comment]
> Edit: It can easily be skipped by adding `;` to the end of the method chain, and the function after will be correctly positioned

Well in swift we don't really use `;` 😂

**Comment by Saafo** [comment]
> @lucario387 not sure whether we can achieve this(seems VSCode doesn't support it, only Xcode support):
> 
> ```swift
> func test3(test: Int, bb: Int) -> Int {
>     return 0
> }
> ```
> 
> when change a new line after `,`, before `bb`, in Xcode, the `bb` parameter will align with the first `test` parameter:
> 
> ```swift
> func test3(test: Int,
>            bb: Int) -> Int {
>     return 0
> }
> ```

The bug remained as:

current:

```swift
func test3(test: Int,
           bb: Int) -> Int {
           return 0 // this line is wrong
}
```

expected:

```swift
func test3(test: Int,
           bb: Int) -> Int {
    return 0
}
```

**Comment by Saafo** [comment]
Another off-topic question :D : do we have ability to re-indent selected lines, which is supported in Xcode?

**Comment by lucario387** [comment]
> Another off-topic question :D : do we have ability to re-indent selected lines, which is supported in Xcode?

I dont know what this is, can you explain? It sounds like `V{motion}=` to me

**Comment by lucario387** [comment]
> > @lucario387 not sure whether we can achieve this(seems VSCode doesn't support it, only Xcode support):
> > ```swift
> > func test3(test: Int, bb: Int) -> Int {
> >     return 0
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > when change a new line after `,`, before `bb`, in Xcode, the `bb` parameter will align with the first `test` parameter:
> > ```swift
> > func test3(test: Int,
> >            bb: Int) -> Int {
> >     return 0
> > }
> > ```
> 
> The bug remained as:
> 
> current:
> 
> ```swift
> func test3(test: Int,
>            bb: Int) -> Int {
>            return 0 // this line is wrong
> }
> ```
> 
> expected:
> 
> ```swift
> func test3(test: Int,
>            bb: Int) -> Int {
>     return 0
> }
> ```

Sadly, this can't be supported then :( (If the parser updates one day to capture parameter lists, then maybe, but as of now I don't want to modify the parser just yet)

**Comment by lucario387** [comment]
> If I input this in order, like: Reg<, \n, Output, \n, > {, \n, the Output is still incorrect:

This is because neither `>`, `{`, or `\n` are part of `:h indentkeys`, add `vim.opt.indentkeys:append(">")` to your config and retry this

**Comment by Saafo** [comment]
> > Another off-topic question :D : do we have ability to re-indent selected lines, which is supported in Xcode?
> 
> I dont know what this is, can you explain? It sounds like `V{motion}=` to me

It means like if I select multi lines with incorrect indents, and re-indent, the selected lines will be formatted with correct indents(but only indents, no other changes)

**Comment by lucario387** [comment]
> It means like if I select multi lines with incorrect indents, and re-indent, the selected lines will be formatted with correct indents(but only indents, no other changes)

Yes, it's `:h =` in Vim. You visually select an area, press `=`, and it should re-indent all lines in those area to what the algorithm believes is the correct indentation level for them

**Comment by lucario387** [comment]
> I add this but it still doesn't work. But if I press = on that line in Visual mode, the indent will be corrected.

Weird, it works fine for me once I added ">" to indentkeys
[Screencast from 2023-05-04 21-06-12.webm](https://user-images.githubusercontent.com/29790821/236199138-f5861638-84f0-4918-a81d-5e721251a084.webm)

**Comment by Saafo** [comment]
I'm really sorry, after pull from the most recent commit, it works now when I set the indentkeys.

**Comment by Saafo** [comment]
Another bug about dict:

current:

```swift
let dict = [
    ]
```

expected:

```swift
let dict = [
]
```

**Comment by lucario387** [comment]
> Another bug about dict:

Fixed

**Comment by Saafo** [comment]
@lucario387 not completely fixed:

```swift
let dict = [111: 333]
```

change a new line between `333` and `]`:

current:

```swift
let dict = [111: 333
    ]
```

expected:

```swift
let dict = [111: 333
]
```

**Comment by lucario387** [comment]
> @lucario387 not completely fixed:

Should be fixed now, I was messing up dictionaries and arrays

**Comment by Saafo** [comment]
I've tested in my more complex swift file, and found these bugs:

1. `@unknown default`

current:

```swift
switch resource {
case .elephant:
    break
case .dog:
    break
    @unknown default: // indent error
    break
}
```

expected:

```swift
switch resource {
case .elephant:
    break
case .dog:
    break
@unknown default:
    break
}
```

2. guard (not sure whether it's like the parameter align problem)

current:

```swift
guard let aa = aa,
    let bb = bb else { return }
```

expected:

```swift
guard let aa = aa,
      let bb = bb else { return }
```

**Comment by Saafo** [comment]
3. else if

current:

```swift
if true {
    return
} else if false {
        return
    }
```

expected:

```swift
if true {
    return
} else if false {
    return
}
```

**Comment by lucario387** [comment]
> 3. else if

Oh no, here we go again, time to ~~copy paste my C if-else changes~~

**Comment by lucario387** [comment]
> 2. multiline guard or if condition (not sure whether it's like the parameter align problem)

The same situation with parameter align here

**Comment by Saafo** [comment]
> @Saafo Is it normal for if statements in Swift to not have curly braces? If it's not the norm, then it's easier to fix this cascading if-else

We must have curly braces for if statements in Swift.

**Comment by lucario387** [comment]
> We must have curly braces for if statements in Swift.

Oh, then it's easy then, just pushed the fix (I believe so)

**Comment by Saafo** [comment]
> Oh, then it's easy then, just pushed the fix (I believe so)

It's still not working 🤔

**Comment by lucario387** [comment]
> It's still not working thinking

Does it correctly align with `=aB` motion ? Interactive indents is only possible if the keywords also trigger indent algo (which by default, they aren't)

**Comment by Saafo** [comment]
> Does it correctly align with `=aB` motion ? Interactive indents is only possible if the keywords also trigger indent algo (which by default, they aren't)

I don't really get the meaning of `=aB` motion? I've tried both type and change new line in order, and select these lines and `=` in visual mode.

> Also, I forced push a few commits ago, so probably require a git pull -f :scared:

I've seen that. I'm using lazy.nvim and I do see I pulled the force pushed commits from the update log.

**Comment by lucario387** [comment]
Well, this is what it looks like from my end (latest commit)
[Screencast from 2023-05-05 20-59-32.webm](https://user-images.githubusercontent.com/29790821/236452208-90f04c5b-962d-4a8b-821c-46766e331c29.webm)

So i'm not sure why the behavior is different :thinking:

**Comment by bytesizelearning** [comment]
This solved the issue I was having thank you @lucario387 :)

**Comment by Saafo** [comment]
Really sorry! After restarting nvim, the `else if` problem has gone!

BTW, should I append `">"` to `indentkeys` even if this pr is merged?

**Comment by lucario387** [comment]
> BTW, should I append ">" to indentkeys even if this pr is merged?

I'd say that setting up a `ftplugin/swift.lua` and set `vim.opt_local:append(">")` would be better, as then it'll only affect swift files

**Comment by Saafo** [comment]
Found another problem about [`property wrapper`](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/properties#Property-Wrappers):

current:

```swift
@propertyWrapper
    struct Reg<
    Output
> {
    @Provider
        var test = 1
}
```

expected:

```swift
@propertyWrapper
struct Reg<
    Output
> {
    @Provider
    var test = 1
}
```

**Comment by Saafo** [comment]
And [`subscript`](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/subscripts#Subscript-Syntax)

current:

```swift
struct AlbumDetail {
    var album: Album
    subscript(index: Int) -> Int {

}
}
```

expected:

```swift
struct AlbumDetail {
    var album: Album
    subscript(index: Int) -> Int {

    }
}
```

**Comment by lucario387** [comment]
> Found another problem about [`property wrapper`](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/properties#Property-Wrappers):

Is this also the same for protocols, and functions? If yes then I'll push a fix for all three

**Comment by lucario387** [comment]
Should be fixed now? maybe

**Comment by Saafo** [comment]
I've found the [`Language Reference for Swift`](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/aboutthelanguagereference), maybe we can cover the cases in this, I think it's more comprehensive

**Comment by Saafo** [comment]
> Is this also the same for protocols, and functions? If yes then I'll push a fix for all three

Yes it is!

**Comment by lucario387** [comment]
It should be a bit better now, I believe

**Comment by Saafo** [comment]
`@available`

current:
```swift
@available(iOS 13, *)
    func test() {
    return
}
```

expected:

```swift
@available(iOS 13, *)
func test() {
    return
}
```

**Comment by lucario387** [comment]
> all [Attributes](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/attributes) have this problem, like dynamicCallable

It should be narrowed down now

**Comment by Saafo** [comment]
From my perspective, there's currently no problem if we'd covered the cases on [`Language Reference for Swift`](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/aboutthelanguagereference)

**Comment by lucario387** [comment]
@Saafo Is it okay for me to ignore multiline arguments for now? It is causing more issues more often than not

**Comment by Saafo** [comment]
> Is it okay for me to (somewhat) ignore multiline arguments for now? It is causing more issues more often than not.

Yes if it's too complicated or may causing more issues!

**Review by amaanq — APPROVED** [review]

**Comment by lucario387** [comment]
Don't merge just yet @amaanq, I'd like to have some more opinions (and/or approvals) from other swift users. And I haven't added the tests for the cases specified in this PR

**Comment by lucario387** [comment]
@Saafo @bytesizelearning have a look again, I've tried to compromise the most possible for the queries

For a better? interactive experience, I'd suggest adding `vim.opt_local.indentkeys:append({"0>", "0@"})` to `ftplugin/swift.lua` and have a try for it.

This should work fine for manual re-indentation through `=`, not that much for editing interactively

**Comment by Saafo** [comment]
> @Saafo @bytesizelearning have a look again, I've tried to compromise the most possible for the queries

Seems it works quite well!

> For a better? interactive experience, I'd suggest adding vim.opt_local.indentkeys:append({"0>", "0@"}) to ftplugin/swift.lua and have a try for it.

Can we make it automatically? Like there's a builtin ftplugin/swift.lua in Swift.vim. I think normal users would not add indent keys manually.

**Comment by lucario387** [comment]
> Can we make it automatically? Like there's a builtin ftplugin/swift.lua in Swift.vim. I think normal users would not add indent keys manually.

Sorry, that's out of scope for this PR/this repo. That has to be done to either
- Another plugin, hooking to provide the indent queries
- A plugin that provides the indent queries + indentexpr + indentkeys themselves
- Do it manually

The purpose of nvim-treesitter is (and will be) to provide parsers, and the queries that leverage those parsers.

**Comment by lucario387** [comment]
I'll merge this now. Tyvm @Saafo for the extensive help :D

**Comment by Saafo** [comment]
Another bad case:

```swift
switch quality {
case 0...100: return 1
default: return nil
    // current wrong indent
// expected indent
}

**Comment by lucario387** [comment]
> Another bad case:
> 
> 
> 
> ```swift
> 
> switch quality {
> 
> case 0...100: return 1
> 
> default: return nil
> 
>     // current wrong indent
> 
> // expected indent
> 
> }

This I can do nothing about it. 

It is manually adjusting the case/default lines after pressing ":"
The other enum case above is fixable, will push soon :

**Comment by Saafo** [comment]
hi @lucario387 I've found another bad case, should I open a new issue for it?

```swift
class Test {
    init() {
        print("")
    }
    deinit {
    print("") // wrong
} // wrong
}
```

**Comment by lucario387** [comment]
You can add this to your own `after/queries/swift/indents.scm` for the time being

```scheme
;; extends

(deinit_declaration) @indent.begin
```

I will do a PR some times after

**Comment by clason** [comment]
(not `after`, though, just `queries`)

**Pull request merged**
