### PR TITLE
Make module `locals` work again (main branch)

### PR DESCRIPTION
**Pull request by TheLeoP**
As stated on #4902, the `locals` module wasn't working after the rewrite. This PR solves this.

I'm using `root:id` to cache the memoized values (to avoid the problem mentioned on #4902).

Also, I modified the behaviour of `find_usages`. Before (and also on the main branch), it only found definitions, I think (Evaluating `kind == nil or def_node == node` on the definition of a node to decide whether or not to add a node to the list of return values will only be true if the node is a definition or if a definition couldn't be found, so the same node gets inserted). I couldn't figure out if the previous behaviour was intended or not, at lest the name `find_usages` suggested a different behaviour in my mind. If this is wrong or causes issues, I'll revert this change.

### CODE REVIEW

**Comment by lucario387** [comment]
You should `git pull --rebase` instead of fixing rebase like such

**Comment by TheLeoP** [comment]
@lucario387 I did exactly that. But, there was a mess of conflicts. I thought I had solved them when I finished the rebase,  but it turns out I didn't (?). This was my first time using rebase :c

**Comment by lucario387** [comment]
Then you should do a clean branch, `git pull upstream main --rebase --force` then re-apply the commits :D

**Comment by TheLeoP** [comment]
Yeah, that makes sense. Thanks @lucario387. Should I close this PR and open a new one doing that?

**Comment by lucario387** [comment]
You can do that on the same branch as well, just clear the commits, rebase, and then force-push back

**Comment by clason** [comment]
Warning: the `main` branch gets frequent rebases and force-pushes. The best way to deal with them is `git rebase -i main`, and then `drop` all commits except your own.

**Comment by clason** [comment]
Also, you should never make PRs from the base branch. Always `git branch fix/locals` first, then add commits there. Together with the merge, this PR is unusable for me unfortunately.

So please open a new PR from a feature branch (it's probably easiest to `git diff

**Pull request closed without merging**
