### PR TITLE
highlights(rust): support `doc_comment`

### PR DESCRIPTION
**Pull request by theHamsta**
https://github.com/tree-sitter/tree-sitter-rust/pull/99

### CODE REVIEW

**Review by vigoux — COMMENTED** [review]
Maybe we can add an markdown injection too?

**Comment by theHamsta** [comment]
The leading `//!` might be a bit of a problem. Maybe I have time to look at `@combined` injection at weekend

**Comment by theHamsta** [comment]
I don't know whether this is ready for markdown injection without the trimming.

**Comment by vigoux** [comment]
Then no markdown injection for now, but maybe add a To-do just so that we remember that.

**Review by vigoux — APPROVED** [review]

**Comment by vigoux** [comment]
You'll need to rebase that on master.

**Comment by theHamsta** [comment]
This commit got reverted in eeb0702ebdac504b97196577b1dac43c80913d7b in tree-sitter-rust

**Pull request closed without merging**
