### PR TITLE
injections(vue): Update injection queries

### PR DESCRIPTION
**Pull request by lucario387**
Follow up of #3981 
Update Vue injection queries with more queries to properly capture cases where it has no `lang` attribute

https://user-images.githubusercontent.com/29790821/209374232-63c1fa60-10ea-4a6b-8246-9d17a3df8079.mp4
It will still correctly capture even if we insert multiple spaces and newlines
https://user-images.githubusercontent.com/29790821/209374644-e178b5c5-8b49-407c-b2ec-1b609eacd173.mp4

### CODE REVIEW

**Comment by lucario387** [comment]
For performance concerns, at least for vue, 
- `<script>` tag has a maximum of 7 attributes + 1 tagname, making the loop inside my custom predicate runs 15 times,
- `<style>` tag has a maximum of 5 attributes + 1 tagname, so the total amount is 11 times
I am not sure whether traversing like that is the fastest way or not, but it is the most accurate capture that I've found working
image

**Comment by lucario387** [comment]
For js/ts injections, it is nigh-impossible for vues' files to capture script elements using `@language` and `@content` as the parser is named javascript and typescript, while the name in `lang` of vue script elements can only be `js` or `ts`

For css/scss, it is possible, but then will be missing `less`, `postcss` and `stylus` injections as there is no parser for those languages, so not really optimal too

**Comment by theHamsta** [comment]
Ah, now I understand. The vue parser already parses the style attribute. I thought you would need to parse the attribute itself. Then no custom predicate should be needed. It is simpler and more efficient when this. I thought you wanted to parse `raw_text` with `"style=css"`.

> For js/ts injections, it is nigh-impossible as of now for vues' files to capture script elements using @language and @content as the parser is named javascript and typescript, while the name in lang of vue script elements can only be js or ts

> For css/scss, it is possible, but then will be missing less, postcss and stylus injections as there is no parser for those languages, so not really optimal too

A missing language will not cause an error. It will automatically work once the language is added.

Yes, this is a known problem (see https://github.com/neovim/neovim/pull/18317, https://github.com/neovim/neovim/pull/17127)

It is strange that it does not extend the HTML parser.

**Comment by lucario387** [comment]
> Ah, now I understand. The vue parser already parses the style attribute. I thought you would need to parse the attribute itself. Then no custom predicate should be needed. It is simpler and more efficient when this. I thought you wanted to parse `raw_text` with `"style=css"`.

Updated to `not-eq?` checks

**Comment by lucario387** [comment]
ah but using `not-eq?` makes it so I cannot capture the tag at all
image

**Comment by theHamsta** [comment]
@lucario387 maybe I don't understand the full problem until now. When it's nicer with the custom predicate we can of course use it. But we had bad experience with predicates that were traversing the node tree. Let me have a look at it when I'm less tired. I don't use Vue and I'm a bit confused about what the queries need to do exactly

**Comment by lucario387** [comment]
> @lucario387 maybe I don't understand the full problem until now. When it's nicer with the custom predicate we can of course use it. But we had bad experience with predicates that were traversing the node tree. Let me have a look at it when I'm less tired. I don't use Vue and I'm a bit confused about what the queries need to do exactly

Ah, sorry for interrupting then,
Essentially, what my custom predicate does is to do an `eq?` check on the node pred[n] with pred[3], with its parent must be start_node, pred[4], pred[5], ..., pred[n-1]
So it cannot go through the entire tree and has to match case-by-case.

I thought that using `not-eq?` with the queries will have similar results to manual traversal through the tree but apparently it's not

**Comment by lucario387** [comment]
@theHamsta nvm, I managed to make it work now
it works exactly like my custom predicate of before

**Review by theHamsta — APPROVED** [review]

**Comment by theHamsta** [comment]
@lucario387 this looks great now! Can you check whether some of your ideas should also be applied to HTML? The grammar structure seems to be quite similar and HTML and vue should stay in sync in that case.

**Comment by lucario387** [comment]
> @lucario387 this looks great now! Can you check whether some of your ideas should also be applied to HTML? The grammar structure seems to be quite similar and HTML and vue should stay in sync in that case.

HTML syntax marks `lang` attribute for `style` and `script` tags as deprecated and is also warned against usage, so I don't think it should be moved there.

If any, I think the script `no_lang` part can be moved to `html_tags`, then I will add extra cases for script types there (As there are cases where the parts inside `script` can be typescript/vue/etc,...

Even then, I will wait on neovim@neovim#18317 for the syntax sync, it'll be much easier to manage then

**Comment by lucario387** [comment]
It certainly can be applied, but 
- I haven't done any research into possible MIME types of script and style tags for HTML, 
- I haven't tried out many cases for HTML typescript injections, so may lead to regressions to captures for HTML/Vue as a whole if I were to inherits HTML injections

**Comment by theHamsta** [comment]
Thank you!

**Pull request merged**
