### PR TITLE
Update Elm parser

### PR DESCRIPTION
**Pull request by theHamsta**
No new nodes only a fix for trailing spaces

### CODE REVIEW

**Comment by vigoux** [comment]
I think we should set the auto updater to update parsers with no changes and report parsers that need changes.
That would allow us to avoid doing updates one by one.

**Review by vigoux — APPROVED** [review]

**Comment by theHamsta** [comment]
It's automated as soon as we can update JS/TS parser.

**Comment by theHamsta** [comment]
I thought about doing one PR per parser but that would involve generating the workflow file to have a per language matrix. Would require additional engineering to find out how to do this.

**Comment by theHamsta** [comment]
We could have one PR for failing parsers and one PR for parsers without failing tests. This would be totally feasible.

**Pull request merged**
