### PR TITLE
feat(latex): improve hyperlinks

### PR DESCRIPTION
**Pull request by jdujava**
Use latest grammar after https://github.com/latex-lsp/tree-sitter-latex/commit/08d8b885a3fa67a6e8aa8edd8988eaa55db46ba4.

### CODE REVIEW

**Comment by clason** [comment]
You need to update the lockfile to point to the latest grammar commit.

**Comment by jdujava** [comment]
Updated the lockfile and runned the query linter. Thanks for pointers @clason.

This is my kind of first contribution, and I can't find anything in `CONTRIBUTING.md` which would instruct me to use corresponding scripts before the PR. Is this information somewhere available, or is it simply missing?

**Comment by clason** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md#formatting

**Comment by jdujava** [comment]
Oh my bad, missed it. But `update-lockfile` isn't there, right?

**Comment by clason** [comment]
No, that's just for CI; for a PR, you need to change this manually.

**Comment by jdujava** [comment]
Sure, thanks again!

I feel some kind of checklist "what to not forget before PR" would be helpful for new contributors.

**Pull request merged**
