### PR TITLE
chore!: remove ensure_installed='maintained'

### PR DESCRIPTION
**Pull request by clason**
Removes all support (and tests) for the parser category "maintained", as this is no longer a useful category.

Followup to deprecation in #2763 -- **do not merge before April 30, 2022**

BREAKING CHANGE: replace `ensure_installed='maintained'` by an explicit list of parsers, or use `'all'` (not recommended).

### CODE REVIEW

**Comment by milanglacier** [comment]
Could you please add descriptions (i.e `desc` key) to those autocmd and keymaps created by nvim_create_autocmd or vim.keymap.set?

Without `desc` key, `:Telescope autocommands` or `:Telescope keymaps`, or `:nmap <CR>`, or `:au filetype` (suppose CR is the map of incremental selection trigger key) will only show a `Lua function` which is not informative at all.

**Review by kyazdani42 — APPROVED** [review]
@theHamsta i think we can merge this now :)

**Comment by clason** [comment]
Well, brace for the incoming barrage of complaints...

**Comment by abdimk** [comment]
Error detected while processing /home/abdisa/.config/nvim/init.lua:
E5113: Error while calling lua chunk: ...are/nvim/site/pack/packer/start/alpha-nvim/lua/alpha.lua:650: attemp
t to call field 'nvim_create_user_command' (a nil value)
stack traceback:
        ...are/nvim/site/pack/packer/start/alpha-nvim/lua/alpha.lua:650: in function 'setup'
        /home/abdisa/.config/nvim/lua/user/alpha.lua:42: in main chunk
        [C]: in function 'require'
        /home/abdisa/.config/nvim/init.lua:19: in main chunk
Error detected while processing /home/abdisa/.local/share/nvim/site/pack/packer/start/cmp-buffer/after/plugin
/cmp_buffer.lua:
E5113: Error while calling lua chunk: ...pack/packer/start/cmp-buffer/after/plugin/cmp_buffer.lua:1: module '
cmp' not found:
        no field package.preload['cmp']
        no file './cmp.lua'
        no file '/usr/share/luajit-2.1.0-beta3/cmp.lua'
        no file '/usr/local/share/lua/5.1/cmp.lua'
        no file '/usr/local/share/lua/5.1/cmp/init.lua'
        no file '/usr/share/lua/5.1/cmp.lua'
        no file '/usr/share/lua/5.1/cmp/init.lua'
        no file '/home/abdisa/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/cmp.lua'
        no file '/home/abdisa/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/cmp/init.lua'
        no file '/home/abdisa/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/cmp.lua'
        no file '/home/abdisa/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/cmp/init.lua'
        no file './cmp.so'
        no file '/usr/local/lib/lua/5.1/cmp.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/cmp.so'
-- More --

**Pull request merged**
