### PR TITLE
update vimdoc parser and queries

### PR DESCRIPTION
**Pull request by clason**

### CODE REVIEW

**Review by vigoux — APPROVED** [review]

**Comment by clason** [comment]
Hmm, query check is failing -- @vigoux can you see what's wrong here?

**Comment by vigoux** [comment]
Seems not related to this change ? `typescript` something something...
Rerunning to be sure.

**Comment by melkster** [comment]
Not sure if this is the right place but the `help` change seems to have broken the syntax of helpdoc labels (are they called that?), making them always left-aligned when concealed.

hmm

**Comment by clason** [comment]
Yes, that is known. The parser isn't really meant primarily for syntax highlighting yet; the focus is more on doc generation. It's clearly something to be fixed, though.

**Comment by melkster** [comment]
Ok!

To anyone reading this, you can disable the syntax highlighting of help files by doing this:

```lua
require('nvim-treesitter.configs').setup({
  highlight = {
    enable = true,
    disable = { 'help' },
  },
})
```

**Pull request merged**
