### PR TITLE
fix: add stricter cc options

### PR DESCRIPTION
**Pull request by lewis6991**
I had `static_assert` compiled in as an unresolved symbol which caused nvim to exit (not crash) when opening a python file: https://github.com/tree-sitter/tree-sitter-python/blob/master/src/scanner.c#L474

Actual issue was my bad dev env, but we need to catch this stuff.

### CODE REVIEW

**Comment by clason** [comment]
Can you add to the PR description a situation where an unresolved symbol was compiled in?

**Comment by clason** [comment]
Nvim-treesitter issues are _full_ of bad dev envs, so having this concrete example is valuable!

**Review by amaanq — APPROVED** [review]

**Comment by lewis6991** [comment]
Is the test failure a problem?

**Comment by clason** [comment]
Nope, unrelated.

**Comment by lewis6991** [comment]
Ok thanks

**Pull request merged**
