### PR TITLE
Fix nix compilation

### PR DESCRIPTION
**Pull request by theHamsta**
This is the update-lockfile-pr

### CODE REVIEW

**Comment by theHamsta** [comment]
@leo60228 there might be more things that have changed in the nix parser. Most of them are just fixes and additional fields.

**Comment by leo60228** [comment]
It looks like `tree-sitter-highlight` queries were added upstream. Do we have some way to make use of those?

**Comment by theHamsta** [comment]
I had the idea that we could have a tag in the parser config to autoimport the queries. Other's had the opinion to host the nvim queries here to avoid confusion with other consumers of the parsers

**Review by vigoux — APPROVED** [review]

**Comment by cstrahan** [comment]
Feel free to send any change requests upstream! :slightly_smiling_face: 

I didn't realize anyone was using `tree-sitter-nix` yet -- hope the recent changes haven't caused too much trouble. Glad to see it's of use! I write `tree-sitter-nix` under the premise that it would enable others to do neat things, though I never had a particular use in mind (yet, anyway); as such, it's really important to me that `tree-sitter-nix` be suitable for everyone else's purposes -- it's you all that I wrote it for, after all :slightly_smiling_face:.

**Pull request merged**
