### PR TITLE
fix(c_indents): fix expression leaking indents

### LINKED ISSUE #4525: Error in C indentation triggered by multiple assignment and format macro constants
### Describe the bug

An error in C indentation logic is triggered by multiple assignment and format macro constants. Example below is illustrated.

```c
#include <stdint.h>
#include <inttypes.h>
#include <stdio.h>

static int a, b, c;
a = b = c = 0;
    // <-- Indentation on this (and every subsequent) line is 1 level too deep.

static int d = 0, e = 0, f = 0;
    // <-- Indentation on this (and every subsequent) line is 1 level too deep.

int main(void) {
    printf("%" PRIu64 "\n", (uint64_t)0);
        // <-- Indentation on this (and every subsequent) line is 1 level too deep.
        fflush(stdout);
        // <-- Indentation remains 1 level too deep.
}
```
The macro `PRIu64` is defined in <inttypes.h> as the following. The explicit expansion exhibits the same bug.
```c
#define PRIu64	__PRI64_PREFIX "u"
printf("%" __PRI64_PREFIX "u" "\n", (uint64_t)0);
```

### To Reproduce

Minimal reproducible .c file illustrated above in bug description.

### Expected behavior

_No response_

### Output of `:checkhealth nvim-treesitter`

```markdown
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v16.18.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "x86_64",
  release = "6.1.18-100.fc36.x86_64",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Sat Mar 11 16:46:48 UTC 2023"
}

## Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cmake               ✓ . ✓ . .
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - cuda                ✓ ✓ ✓ ✓ ✓
  - help                ✓ . . . ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - latex               ✓ . ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ . ✓
  - ninja               ✓ . ✓ ✓ .
  - python              ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - tlaplus             ✓ ✓ ✓ . ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓
  - zig                 ✓ . ✓ ✓ ✓
```

### Output of `nvim --version`

```text
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3

Features: +acl +iconv +tui
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lucario387**
Closes #4525 
@amaanq @scienceplease have a check

### CODE REVIEW

**Comment by amaanq** [comment]
I'm assuming this won't affect multiple statements on a single line (not that it would..) right? If so, looks good :slightly_smiling_face:

**Comment by lucario387** [comment]
Mind elaborating more on that? :)
I don't really understand the meaning of that

**Comment by amaanq** [comment]
```c
int main() {
    int a = 3; int b = 4; int c = 5;
}
```

Just being cautious but that probably won't change anything w/ that followed by a newline.. I hope

**Comment by lucario387** [comment]
> ```c
> int main() {
>     int a = 3; int b = 4; int c = 5;
> }
> ```
> 
> Just being cautious but that probably won't change anything w/ that followed by a newline.. I hope

Well that still works, but 
```c
a = 0; b = 0; c = 0;
```
on the same line will break this
So :bruh:

**Comment by amaanq** [comment]
Yeah I was maybe thinking dedenting by semicolon end isn't the right move for C imo, unless you *indent* that first, but that's also not the norm

**Comment by lucario387** [comment]
@amaanq one more try, this time I narrow it down to 2 cases
binary expressions (not really, this can only happen in C++ but im putting in C for easier refactor if #4524 is merged)

**Comment by amaanq** [comment]
Not sure I follow, are you indenting only binary expressions and assignments inside expression statements to properly handle dedenting ;? Or vice versa

**Comment by lucario387** [comment]
> Not sure I follow, are you indenting only binary expressions and assignments inside expression statements to properly handle dedenting ;? Or vice versa

C++ syntax of 
```cpp
cin >> 
cout <<
```
are considered as binary expression statements, 
And the tests expects it to be indented so I won't try to change those tests. I will just add a special case (for now) for that case

**Comment by amaanq** [comment]
Well it is a binary expression, and on newlines those should be indented I think (I don't use c++ all that much)

I hope you're not forgetting other potential cases of expression_statements that are expected to be indented as well..I'll take a look now

**Comment by lucario387** [comment]
> Well it is a binary expression, and on newlines those should be indented I think (I don't use c++ all that much)
> 
> I hope you're not forgetting other potential cases of expression_statements that are expected to be indented as well..I'll take a look now

Well from `tree-sitter-c` test queries, the ones I missed were
- `call_expression`, well this one im pretty sure is for indents inside `()`, and that is already handled by a query down below
- `number_literal`, `identifier` (1; true;). Will there be anyone coding like that :)
- `update_expression`, x++, x--: These should never need to be indented to begin with

**Comment by amaanq** [comment]
Yeah, I guess call_expression is handled by the parentheses anyways. What about conditional?

**Comment by lucario387** [comment]
Or another way out for this PR is to wait for #4524. I've been testing with it and the results were much better, with less changes needed.

**Comment by lucario387** [comment]
> Yeah, I guess call_expression is handled by the parentheses anyways. What about conditional (aka ternaries)?

Well that I did miss 
I blame the tests then

**Comment by amaanq** [comment]
That'd be fine as well, that PR def needs Hamsta's approval though :)

**Comment by lucario387** [comment]
This has to wait for #4524 as it's now a major, and breaking change and not just changes to aligned indent functionalities

**Comment by lucario387** [comment]
@scienceplease second try with different queries, can you have a look at it?

**Review by scienceplease — APPROVED** [review]

**Review by scienceplease — APPROVED** [review]
Apologies for the delay

**Review by theHamsta — APPROVED** [review]

**Comment by theHamsta** [comment]
Thank you!

**Pull request merged**
