### PR TITLE
feat: add nu parser

### PR DESCRIPTION
**Pull request by sei40kr**
Add [nu parser](https://github.com/nushell/tree-sitter-nu).

### CODE REVIEW

**Comment by lucario387** [comment]
These are helix captures. Please convert the captures to nvim-treesitter first, following `CONTRIBUTING.md`

**Comment by sei40kr** [comment]
@lucario387 
Sorry, I've changed the capture `@special` which is causing an error like these:

| | Before | After |
|--------|--------|--------|
| `o>`, `out>`, `e>`, `err>` , `e+o>`, `err+out>`, `o+e>`, `out+err>`| `@special` | `@operator` |
| `$nu`, `$in`, `$env`, `$nothing` | `@special` | `@variable.builtin` |

**Comment by ObserverOfTime** [comment]
Those aren't the only ones. See CONTRIBUTING.md.

**Comment by clason** [comment]
@sei40kr did @nushell agree to maintain **the queries in this repo** (i.e., answer questions and fix breaking queries in a timely fashion)?

**Comment by ObserverOfTime** [comment]
Still needs more specific captures (`@conditional`, `@keyword.operator`, etc.)

**Comment by clason** [comment]
Closing as stale. If people are interested in this, they are encouraged to make their own PR based on the current state of the parser and our contributing guidelines.

**Pull request closed without merging**
