### PR TITLE
Update ocamllex parser and highlights

### PR DESCRIPTION
**Pull request by undu**
Update ocamllex highlights

### CODE REVIEW

**Comment by clason** [comment]
You also need to include the update to the lockfile in your commit (best squashed).

**Comment by undu** [comment]
Now it should be autocontained with only the ocamllex changes

**Review by amaanq — APPROVED** [review]

**Review by amaanq — APPROVED** [review]

**Review by lucario387 — APPROVED** [review]

**Comment by glyh** [comment]
I'm experiencing wrong highlighted result. Does this have precedence over ocaml's parser? 
https://github.com/314eter/tree-sitter-ocamllex/issues/5
Or is extra config required? If so how?

**Comment by clason** [comment]
Yes, of course, the filetype needs to be set to `ocamllex`.

**Pull request merged**
