### PR TITLE
chore(issues): make bug_report an issue form

### PR DESCRIPTION
**Pull request by vigoux**
We got quite a lot of bug reports with invalid/missing information lately, which is a waste of time for both submitters and maintainers.

So switch to github issue forms to enforce following the rules of issue submission.

### CODE REVIEW

**Review by stsewd — APPROVED** [review]
We could also put in some place that additional to images of how code looks like in neovim, providing the code itself is also helpful to debug things.

**Comment by vigoux** [comment]
I am not sure I understand what you mean

**Comment by stsewd** [comment]
@vigoux when users report a problem they usually attach an image of the code, but they don't provide the code in plain text, so it's hard to replicate the problem without having to transcribe the code from the image manually.

**Comment by vigoux** [comment]
I think this can be done in the `textarea`, people can paste the code they want, and put images and such.

**Pull request merged**
