### PR TITLE
Python: include attribute in locals

### PR DESCRIPTION
**Pull request by stsewd**
Allow to highlight this

Screenshot from 2020-09-11 18-04-37

### CODE REVIEW

**Comment by theHamsta** [comment]
Why do you want to include the "self."? If it's only to distinguish it from locals we should add another mechanism that checks the type of definition/reference. The attribute can also be used on a concrete object and not only self.

In C++ I had the problem that the same identifier was defined both as a variable and namespace.

**Comment by stsewd** [comment]
It's to distinguish them from locals and also to be able to highlight the same attribute

Screenshot from 2020-09-12 11-12-43


btw, this doesn't affect the old highlights, it only works if the cursor is on the `.`.

Screenshot from 2020-09-12 11-14-18

**Comment by theHamsta** [comment]
Can we close this? I don't think it makes sense to make scoped names additional definitions. If we do we should add it to all languages and also for scoped imports like `import skimage.io` defining `skimage.io` but I fear that all those attempts would get very language specific.

**Comment by theHamsta** [comment]
@stsewd maybe you can ask the other maintainer whether this problem can be tackled some how. But I got the feeling that with this only Python would have those multiple definitions at one place while you can have similar concepts also in Rust/C++/Java.

**Pull request closed without merging**
