### PR TITLE
feat: add the php_only parser included in tree-sitter-php

### PR DESCRIPTION
**Pull request by tk-shirasaka**

### CODE REVIEW

**Comment by clason** [comment]
Thank you! We will have to park this until we backport the breaking changes from `main` regarding capture renaming and query formatting; otherwise this will conflict. (I'm hoping to do that this weekend.)

**Comment by tk-shirasaka** [comment]
Thank you for informing us.

This PR is just two separate parsers for the core programming language part and the embedding part into HTML.
As such, there are no new captures.

However, as the parser is separated, only the html injection part is left in the php parser.

Please let us know if there are any problems.
If nothing else, would be happy to have it merged.

**Review by clason — APPROVED** [review]

**Comment by clason** [comment]
note to self: needs `requires` entry on `main`.

**Comment by clason** [comment]
No, `master` is the correct base branch for all such pull requests. I'll rebase `main` on top of it regularly (making necessary changes, such as the one I mentioned).

**Review by ObserverOfTime — APPROVED** [review]

**Comment by clason** [comment]
Can you add a lockfile and README entry? (It's automated, but it'll be cleaner if it's added to this PR.)

**Comment by tk-shirasaka** [comment]
I am sorry for getting ahead of myself.
I have only added a note to the README and lockfile.json, so please check it?

**Comment by clason** [comment]
No worries, looks good. I'll merge after CI passes.

**Pull request merged**
