### PR TITLE
docs: fix typo

### PR DESCRIPTION
**Pull request by hezhizhen**

### CODE REVIEW

**Comment by amaanq** [comment]
The typo fix in solidity will not work, you can file an issue at parser's source repo to fix that

**Comment by hezhizhen** [comment]
> The typo fix in solidity's query files will not work, you can file an issue at parser's source repo to fix that

I see. So revert them first?

**Comment by hezhizhen** [comment]
@amaanq PTAL

**Review by amaanq — APPROVED** [review]

**Comment by amaanq** [comment]
Great, thanks!

**Pull request merged**
