### PR TITLE
injections(html, vue, svelte): Update injections

### PR DESCRIPTION
**Pull request by lucario387**
- A partial implementation for #4034 
- Update html_tags injections file so that vue/svelte parsers can inherit it without having a script/style tag being captured twice
- Update vue, svelte injections
- Add test file for html, svelte

Preview:

| Before | After |
| ------ | ----- |
| image | image |

### CODE REVIEW

**Comment by theHamsta** [comment]
@steelsojka, @WhyNotHugo @elianiva

**Review by theHamsta — APPROVED** [review]

**Comment by lucario387** [comment]
Very much unsure of what is the syntax of svelte/preprocessors of svelte. The only thing I can see from the docs is using `lang` as a markup for preprocessor, but I don't know what other custom preprocessors are used. So I won't fix it unless someone can guide me/lmk of the general use-case in real world

For vue, I'm using it for daily stuffs so I can be pretty sure of its real life usages

**Comment by theHamsta** [comment]
@lucario387 svelte is an extension of the HTML grammar, so everything fine for HTML should be also fine for svelte.

**Comment by lucario387** [comment]
@theHamsta Just used a very basic svelte file for test file, taken from images of prior svelte injections PR

**Pull request merged**
