### PR TITLE
Use stylua for autoformat code

### PR DESCRIPTION
**Pull request by stsewd**
Looks like https://github.com/Koihik/LuaFormatter is the most popular. I think we should keep most of the defaults, but I have changed 2 values from what I have seen more common things in our code base, especially 2 spaces for indentation, but happy to remove the `extra_sep_at_table_end` option.

Had to install luarocks from the source because the one from ubuntu is too old to use with luaformatter.

### CODE REVIEW

**Review by theHamsta — APPROVED** [review]

**Comment by theHamsta** [comment]
Maybe merge this after #1423? This could save us maybe some merge conflicts there if there a large changes like in this PR.

**Comment by stsewd** [comment]
> Maybe merge this after #1423? This could save us maybe some merge conflicts there if there a large changes like in this PR.

Sure!

**Comment by clason** [comment]
FYI, lspconfig is using stylua: https://github.com/neovim/nvim-lspconfig/pull/1029

As lspconfig is somewhat "semi-official", this can be seen as a first move for neovim itself. I know nvim-treesitter is its own project, but some alignment (where it makes sense) might be useful?

**Comment by theHamsta** [comment]
stylua also seems easier to install (cargo only or binary from GH releases), while luaformat requires luarocks. cmake, c++17

**Comment by stsewd** [comment]
Changed to use stylua instead :+1:

**Comment by theHamsta** [comment]
There are some conflicts. Please use `git reset --soft origin/master` instead of merging master to resolve the conflict. Ideally there are only two commits:

- add stylua job
- auto-format repo (on clean master so that no old version get introduced by mistake)

Feel free to merge once done

**Review by theHamsta — APPROVED** [review]

**Pull request merged**
