### PR TITLE
Highlight pointer asterisks as @type fix #3841

### LINKED ISSUE #3841: [C] the asterisk should be @type when used to mark pointer types
### Describe the highlighting problem

The asterisk has different meaning in C: when it's used for multiplication or dereference, it's correct to highlight it as `@operator`.

However, when it's used to define a pointer, it should be highlighted as `@type`.

The following `highlights.scm` query does exactly this:
```
(abstract_pointer_declarator
  ( "*" @type))
(pointer_declarator
  ( "*" @type))
```

### Example snippet that causes the problem

```c
int *p;                         // should be @type
extern int main(int, char **);  // should by @type
p = (int *)q;                   // should be @type
typedef int *intptr_t;          // should by @type
typedef int (*cb)(int data);    // should be @type

a = b * c;  // should be @operator
*p = 0;     // should be @operator
```

### Tree-sitter parsing result

```
declaration [1, 0] - [1, 7]
  type: primitive_type [1, 0] - [1, 3]
  declarator: pointer_declarator [1, 4] - [1, 6]
    "*" [1, 4] - [1, 5]
    declarator: identifier [1, 5] - [1, 6]
  ";" [1, 6] - [1, 7]
comment [1, 32] - [1, 50]
declaration [2, 0] - [2, 30]
  storage_class_specifier [2, 0] - [2, 6]
    "extern" [2, 0] - [2, 6]
  type: primitive_type [2, 7] - [2, 10]
  declarator: function_declarator [2, 11] - [2, 29]
    declarator: identifier [2, 11] - [2, 15]
    parameters: parameter_list [2, 15] - [2, 29]
      "(" [2, 15] - [2, 16]
      parameter_declaration [2, 16] - [2, 19]
        type: primitive_type [2, 16] - [2, 19]
      "," [2, 19] - [2, 20]
      parameter_declaration [2, 21] - [2, 28]
        type: primitive_type [2, 21] - [2, 25]
        declarator: abstract_pointer_declarator [2, 26] - [2, 28]
          "*" [2, 26] - [2, 27]
          declarator: abstract_pointer_declarator [2, 27] - [2, 28]
            "*" [2, 27] - [2, 28]
      ")" [2, 28] - [2, 29]
  ";" [2, 29] - [2, 30]
comment [2, 32] - [2, 50]
expression_statement [3, 0] - [3, 13]
  assignment_expression [3, 0] - [3, 12]
    left: identifier [3, 0] - [3, 1]
    operator: "=" [3, 2] - [3, 3]
    right: cast_expression [3, 4] - [3, 12]
      "(" [3, 4] - [3, 5]
      type: type_descriptor [3, 5] - [3, 10]
        type: primitive_type [3, 5] - [3, 8]
        declarator: abstract_pointer_declarator [3, 9] - [3, 10]
          "*" [3, 9] - [3, 10]
      ")" [3, 10] - [3, 11]
      value: identifier [3, 11] - [3, 12]
  ";" [3, 12] - [3, 13]
comment [3, 32] - [3, 50]
type_definition [4, 0] - [4, 22]
  "typedef" [4, 0] - [4, 7]
  type: primitive_type [4, 8] - [4, 11]
  declarator: pointer_declarator [4, 12] - [4, 21]
    "*" [4, 12] - [4, 13]
    declarator: type_identifier [4, 13] - [4, 21]
  ";" [4, 21] - [4, 22]
comment [4, 32] - [4, 50]
type_definition [5, 0] - [5, 28]
  "typedef" [5, 0] - [5, 7]
  type: primitive_type [5, 8] - [5, 11]
  declarator: function_declarator [5, 12] - [5, 27]
    declarator: parenthesized_declarator [5, 12] - [5, 17]
      "(" [5, 12] - [5, 13]
      pointer_declarator [5, 13] - [5, 16]
        "*" [5, 13] - [5, 14]
        declarator: type_identifier [5, 14] - [5, 16]
      ")" [5, 16] - [5, 17]
    parameters: parameter_list [5, 17] - [5, 27]
      "(" [5, 17] - [5, 18]
      parameter_declaration [5, 18] - [5, 26]
        type: primitive_type [5, 18] - [5, 21]
        declarator: identifier [5, 22] - [5, 26]
      ")" [5, 26] - [5, 27]
  ";" [5, 27] - [5, 28]
comment [5, 32] - [5, 50]
expression_statement [7, 0] - [7, 10]
  assignment_expression [7, 0] - [7, 9]
    left: identifier [7, 0] - [7, 1]
    operator: "=" [7, 2] - [7, 3]
    right: binary_expression [7, 4] - [7, 9]
      left: identifier [7, 4] - [7, 5]
      operator: "*" [7, 6] - [7, 7]
      right: identifier [7, 8] - [7, 9]
  ";" [7, 9] - [7, 10]
comment [7, 12] - [7, 34]
expression_statement [8, 0] - [8, 7]
  assignment_expression [8, 0] - [8, 6]
    left: pointer_expression [8, 0] - [8, 2]
      operator: "*" [8, 0] - [8, 1]
      argument: identifier [8, 1] - [8, 2]
    operator: "=" [8, 3] - [8, 4]
    right: number_literal [8, 5] - [8, 6]
  ";" [8, 6] - [8, 7]
comment [8, 12] - [8, 34]
```

### Example screenshot

image

### Expected behavior

image

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - WARNING: `node` executable not found (only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `git` executable found.
  - OK: `tcc` executable found. Selected from { "tcc", "cc", "gcc", "clang", "cl", "zig" }
    Version: tcc: error: invalid option -- '--version'
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - lua            ✓ ✓ ✓ ✓ ✓
  - c              ✓ ✓ ✓ ✓ ✓
  - help           ✓ . . . .
  - vim            ✓ ✓ ✓ . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.8.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az30-11

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mfc73**
Fixes #3841

### CODE REVIEW

**Comment by theHamsta** [comment]
I would prefer to leave it as-is? Can we hear more opinions please? Best to decide this democratic :slightly_smiling_face:

**Comment by ObserverOfTime** [comment]
I'm personally OK with this change but I'll nitpick about the formatting:

```scheme
(abstract_pointer_declarator "*" @type)
(pointer_declarator "*" @type)
```

**Comment by Isopod** [comment]
> I would prefer to leave it as-is? Can we hear more opinions please? Best to decide this democratic

Since you asked for opinions: As a random contributor and user of C, I would also prefer to keep it as-is.

**Comment by amaanq** [comment]
Closing as this is a matter of preference and you can extend it yourself

**Pull request closed without merging**
