### PR TITLE
Clear env when invoking git commands.

### PR DESCRIPTION
**Pull request by mathieulj**
If neovim is started during a git commit, the GIT environment variables will point to the host index and attempting git operations without clearing the environment can corrupt the parent index.

We weren't setting env on the git commands, setting them to an empty table instructs libuv to clear the environment.

Resolves https://github.com/nvim-treesitter/nvim-treesitter/issues/5353

### CODE REVIEW

**Comment by clason** [comment]
I'm afraid that this will simply break other uses that _rely_ on environment variables. Can you explain what the actual issue here is? I'm very inclined right now just to drop `git` support for 1.0 as this was never intended as a full alternative to `curl` and `tar`.

**Comment by mathieulj** [comment]
My apologies, I added more context [on the existing issue's comments](https://github.com/nvim-treesitter/nvim-treesitter/issues/5353#issuecomment-2156098296) but I should have added more here as well.

The root of the issue is that git will a) set environment variables when an editor is spawned to edit the commit message and b) override defaults when it sees those environment variables. When neovim was spawned by git, attempting to use git to download a plugin can corrupt the index of the repository being commited to. Since the environment variables are telling git to use that index while checking out the plugin's commit, it's effectively modifying the wrong index. Downloading the git plugin fails because the incorrect index doesn't contain the requested commit hash:

image


While we could make this change more focused, we should remove `GIT_INDEX_FILE` and `GIT_DIR`. Anything set by the parent process is guaranteed to be invalid for the plugin clone/checkout since we are executing git with the paths we intend in the arguments list (different from the parent directory).

> I'm very inclined right now just to drop git support for 1.0 as this was never intended as a full alternative to curl and tar.

Removing this feature entirely would indeed be an alternate path forward. I don't think it should remain in a broken state but I'd be happy with either path being taken.

**Comment by clason** [comment]
If there are a small handful of variables we can explicitly clear that would 1. fix this and 2. be sure not to break valid use, let's go with that for now.

**Comment by mathieulj** [comment]
I've updated the implementation to selectively exclude the git location environment variables since those are guaranteed to be invalid for the plugin fetch. 

Since libuv will clear environment variables when any are passed in, we have to actually map through and manually filter env variables if we want just a subset of the inherited variables.

**Comment by mathieulj** [comment]
Also, going back to you comment about a rewrite on `main` (rather than `master`). It looks like the same issue is still present there. I can put up another PR targeting main with these same changes if you decide to keep git fetching.

**Comment by clason** [comment]
Ok, that is more effort than I expected (and am comfortable with). Let me think about it; I'm leaning toward deprecating the git alternative.

**Comment by clason** [comment]
Going with deprecating  `git` (which is already done on `main` so will be gone with 1.0). Thanks, though!

**Pull request closed without merging**
