### PR TITLE
feat(perl): improve highlights

### PR DESCRIPTION
**Pull request by ObserverOfTime**
Mainly heredocs and builtin functions.

### CODE REVIEW

**Review by amaanq — APPROVED** [review]

**Comment by ObserverOfTime** [comment]
Halfway through this, I noticed that there's [another perl parser](https://github.com/tree-sitter-perl/tree-sitter-perl) which may or may not be better. :thinking:

**Comment by amaanq** [comment]
Interesting, it seems actively maintained and its scanner is in C

**Comment by ObserverOfTime** [comment]
I'm thinking we should keep using this parser until tree-sitter-perl/tree-sitter-perl#85 is merged.
That way we won't have to deal with a potentially breaking change soon after switching.

**Comment by amaanq** [comment]
Would be interesting to see if they're willing to upstream that parser

**Comment by clason** [comment]
Yes, @leonerd is actively working on an official(!) Perl parser. It's not easy going.

**Pull request merged**
