### PR TITLE
Fix Teal highlights

### PR DESCRIPTION
**Pull request by theHamsta**
@euclidianAce

### CODE REVIEW

**Comment by YaBoiBurner** [comment]
Did a quick test on my system and this does seem to fix the errors on teal highlights. I don't really see it causing any issues.

**Comment by euclidianAce** [comment]
Sorry, forgot to update these! I have a local version that I was testing with that I'll upload shortly!

**Comment by theHamsta** [comment]
@euclidianAce did you upgrade your parser to 0.19.X?

**Comment by euclidianAce** [comment]
@theHamsta Yes, I believe so. A the very least it works on my machine™

**Pull request closed without merging**
