### PR TITLE
chore: update formatting for stylua update

### PR DESCRIPTION
**Pull request by theHamsta**

### CODE REVIEW

**Comment by clason** [comment]
Might want to hold that for a day; Stylua 0.13.0 just got released and pushed to Homebrew (currently in the queue).

**Comment by theHamsta** [comment]
I'm just run it a few seconds too early. Try `cargo install stylua`. It's still building for me

**Comment by clason** [comment]
Nah, I'll wait for Homebrew, tomorrow is good enough for me ;)

I just meant that CI won't have it earlier and thus likely complain about your changes.

**Comment by theHamsta** [comment]
Don't know why it does use `.styluaignore`

**Comment by clason** [comment]
Yeah, it should. Maybe a regression?

**Comment by theHamsta** [comment]
Locally it uses the ignore file

**Comment by theHamsta** [comment]
Apparently, the release from crates.io and Github releases have diverged. Installing directly from repo works (probably also when downloading from GH releases link the action)

**Review by clason — APPROVED** [review]

**Pull request merged**
