### PR TITLE
Improved fortran highlighting

### PR DESCRIPTION
**Pull request by oponkork**

### CODE REVIEW

**Review by theHamsta — APPROVED** [review]

**Comment by theHamsta** [comment]
Couldn't `procedure` be also keyword.function?

**Comment by oponkork** [comment]
> Couldn't `procedure` be also keyword.function? Some conflicts need to be resolved to merge

Moved procedure to keyword.function. :)

What conflicts do we need to resolve?

**Comment by theHamsta** [comment]
@oponkork You have to find it out your self. Try a `git rebase origin/master` where origin is the upstream repo.

image

**Comment by theHamsta** [comment]
Fixed the conflicts but by mistake pushed the wrong commit to your master which automatically closed this PR. Sorry for that!

**Pull request closed without merging**
