### PR TITLE
feat(erlang): add keyword and operator suppored by otp25

### PR DESCRIPTION
**Pull request by haoxianhan**
update some new keyword highlights in Erlang otp25.

### CODE REVIEW

**Comment by amaanq** [comment]
Is there a reason the conditionals have a 95 priority?

**Review by amaanq — APPROVED** [review]

**Comment by haoxianhan** [comment]
I have no idea too. The `highlights.scm` here is quite different from the [source](https://github.com/WhatsApp/tree-sitter-erlang/blob/main/queries/highlights.scm). I need to take some time to understand. :)

**Comment by amaanq** [comment]
That's fine, our precedence is last wins. I'll add a suggestion to remove the priority, just apply it

**Comment by amaanq** [comment]
Couldn't since gh doesn't allow you to select above n lines of untouched code for suggestions...pushed it myself

**Pull request merged**
