### PR TITLE
feat(scala): add in local variables queries

### PR DESCRIPTION
**Pull request by ckipp01**
This syncs the queries that were updated in https://github.com/tree-sitter/tree-sitter-scala/pull/196.

### CODE REVIEW

**Comment by amaanq** [comment]
@ckipp01 I fixed it up, lmk if you want me to merge

**Comment by ckipp01** [comment]
> @ckipp01 I fixed it up, lmk if you want me to merge

O wow, thanks a lot for doing that. Just to be sure I understand, looking at the [docs](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#local-variables) I see:

> @local.scope - indicates that a syntax node introduces a new local scope.
> @local.definition - indicates that a syntax node contains the name of a definition within the current local scope.
> @local.reference - indicates that a syntax node contains the name which may refer to an earlier definition within some enclosing scope.

Are the `@local`s just not needed? Is that a Neovim specific thing, or should we also be changing those in our grammar queries?

**Comment by amaanq** [comment]
We do not exactly follow "upstream" treesitter convention for a couple reasons. One, the docs didn't exist when nvim-ts was created and two, the captures they "have" are sometimes not enough for us. Check contributing.md

**Comment by ckipp01** [comment]
> We do not exactly follow "upstream" treesitter convention for a couple reasons. One, the docs didn't exist when nvim-ts was created and two, the captures they "have" are sometimes not enough for us. Check contributing.md

Gotcha, yea I see the `locals` section, but didn't really see an explanation. Thanks for fix! and yes, fine to merge.

**Review by amaanq — APPROVED** [review]

**Pull request merged**
