### PR TITLE
feat: improve yuck highlighting

### PR DESCRIPTION
**Pull request by Philipp-M**
Improves yuck highlighting, see https://github.com/helix-editor/helix/pull/6242 how it looks like in helix

### CODE REVIEW

**Comment by amaanq** [comment]
Thanks! FYI: Helix will be moving to last wins like how we have it, as Max has also agreed it's better this way... :)

Relevant gist to our chats to help figure out where to coordinate our efforts if you're interested: https://gist.github.com/amaanq/ed0f3f80ea5307fd206b1d3b88b3220d

**Comment by Philipp-M** [comment]
> Why not just do
> 
> ```scheme
> (string) @string
> ```
> 
> ?

It's more explicit, it only matches what really is a string and nothing else. But if you want to have a fallback to string (e.g. because of non highlighted interpolation operators if the scope/id is not configured otherwise), I can do that, though I prefer only applying highlights when it makes sense.

**Comment by amaanq** [comment]
Hmm it's fine, I remember this made interpolations more defined which I liked, sorry for forgetting :sweat_smile: 

But generally, languages with interpolations *do* highlight the entirety of a string anyways

**Review by amaanq — APPROVED** [review]

**Comment by Philipp-M** [comment]
> But generally, languages with interpolations do highlight the entirety of a string anyways

Interesting, well it is completely highlighted, with the defined ids/scopes at least, but I understand that a fallback might be useful (though, since all the inner parts of the interpolation are highlighted, it looks weird IMHO when e.g. `@punctuation.special` is not defined as color, I'd rather leave it white/not highlighted, so as is)

**Comment by amaanq** [comment]
I'm w/ you on that, but not everyone might be :wink:

**Pull request merged**
