### PR TITLE
feat: add passwd

### PR DESCRIPTION
**Pull request by amaanq**
Pretty much just /etc/passwd in Linux

### CODE REVIEW

**Review by ObserverOfTime — CHANGES_REQUESTED** [review]
It might be worth differentiating `home` and `shell`.
Perhaps `@constant` and `@string.special` respectively?

**Comment by amaanq** [comment]
> It might be worth differentiating `home` and `shell`. Perhaps `@constant` and `@string.special` respectively?

I agree, how about `@variable` for home? It's not really a constant imo

**Comment by ObserverOfTime** [comment]
I mean, it shouldn't change so...

**Comment by amaanq** [comment]
> I mean, it shouldn't change so...

Yeah that's true, alright

**Comment by ObserverOfTime** [comment]
Does `@text.uri` overwrite the other highlights or does it just add an underline? I can't check at the moment.

**Comment by amaanq** [comment]
> Does `@text.uri` overwrite the other highlights or does it just add an underline? I can't check at the moment.

Underline, see:
image

**Comment by ObserverOfTime** [comment]
I see that overwrites them. 🤔

**Comment by amaanq** [comment]
> I see that overwrites them. 🤔

I didn't replace `home` with `@constant` in that screenshot yet, the blue is `@string.special`

**Comment by ObserverOfTime** [comment]
It seems that `@text.uri` has to be specified first, otherwise it overwrites the rest.

**Comment by amaanq** [comment]
> It seems that `@text.uri` has to be specified first, otherwise it overwrites the rest.

In what way? I don't notice that in my theme at least, but I'll change the order either way

**Comment by ObserverOfTime** [comment]
> In what way? I don't notice that in my theme at least, but I'll change the order either way

I'm assuming your theme only underlines `@text.uri`. It's coloured in mine.

**Review by ObserverOfTime — APPROVED** [review]

**Comment by amaanq** [comment]
> > In what way? I don't notice that in my theme at least, but I'll change the order either way
> 
> I'm assuming your theme only underlines `@text.uri`. It's coloured in mine.

ahhh thanks, didn't think about that

**Pull request merged**
