### PR TITLE
Removes link to missing highlight group docs in README

### PR DESCRIPTION
**Pull request by kovasap**

### CODE REVIEW

**Comment by clason** [comment]
Thank you, but that link is useful and needs to remain.

**Comment by kovasap** [comment]
But it's missing!  That help page no longer exists.

**Comment by kovasap** [comment]
Doesn't https://github.com/nvim-treesitter/nvim-treesitter/commit/42ab95d5e11f247c6f0c8f5181b02e816caa4a4f remove this help page?  On my `NVIM v0.7.2` I get a "Sorry, no help for treesitter-highlight-groups" message.

**Comment by clason** [comment]
Nvim-treesitter requires Nvim 0.8.0, which does have this tag.

**Pull request closed without merging**
