### PR TITLE
Update Slint highlight queries for grammar rewrite

### PR DESCRIPTION
**Pull request by jrmoulton**

### CODE REVIEW

**Comment by jrmoulton** [comment]
I did a fairly major rewrite of the Slint grammar and these are the updated highlight queries

**Comment by clason** [comment]
You need to wait until the updated parser is merged -- or, even better, you can update the parser by changing the [commit hash in `lockfile.json`](https://github.com/nvim-treesitter/nvim-treesitter/blob/a2d7e78b0714a0dc066416100b7398d3f0941c23/lockfile.json#L344-L346) in this PR.

**Comment by jrmoulton** [comment]
Awesome. I've just done that

**Comment by clason** [comment]
The tests are still failing; I think the injections need to be updated as well!

**Comment by theHamsta** [comment]
@jrmoulton the problem are the indent queries.

**Comment by clason** [comment]
Can we make this clearer in the test output? Right now, it's really confusing...

**Comment by theHamsta** [comment]
It should now print language and query type.

**Comment by clason** [comment]
Thanks, but wouldn't it be better to do this on the original error message?

**Review by theHamsta — APPROVED** [review]

**Comment by jrmoulton** [comment]
Thanks for the help!

**Pull request merged**
