### PR TITLE
Add rasi ftdetect

### PR DESCRIPTION
**Pull request by Fymyte**
I've added an `ftdetect` file for rasi config

Signed-off-by: Fymyte <pierguill@gmail.com>

### CODE REVIEW

**Comment by clason** [comment]
We're trying to get rid of `ftdetect` in this repo...

**Comment by theHamsta** [comment]
We're trying to remove ftdetect https://github.com/nvim-treesitter/nvim-treesitter/issues/2259 I've added rasi to the TODO list to upstream to Vim.

**Comment by theHamsta** [comment]
Leaving t

**Comment by Fymyte** [comment]
Thanks np I'll try to do that 👍

**Comment by clason** [comment]
Note that right now,

> upstream Vim or Neovim's new Lua ftdetect

is not really an _or_ -- filetype updates _must_ go through a Vim patch. (This may change in the future, but right now the first step is always a PR to Vim.)

**Pull request closed without merging**
