### PR TITLE
go: register `max` and `min` as new builtin functions

### PR DESCRIPTION
**Pull request by 110y**
The next version of Go (1.21) introduces new builtin functions: `max` and `min`:
https://github.com/golang/go/blob/a031f4ef83/src/builtin/builtin.go#L211-L221

### CODE REVIEW

**Review by amaanq — APPROVED** [review]

**Review by lucario387 — APPROVED** [review]

**Comment by lucario387** [comment]
Will wait till 1.21 goes out of rc :D

**Comment by 110y** [comment]
@lucario387 

Thank you for approving 👍 

Since my PR, which also adds a new builtin function introduced in 1.21, has already been merged, I think it's OK to merge this PR. What do you think about this...?
ref:  https://github.com/nvim-treesitter/nvim-treesitter/pull/4849

**Comment by lucario387** [comment]
I personally believe the amount of times people write their `max` and `min` func are significantly more than `clear`, so it may cause some confusion in highlights if it's  marked as a builtin func.

Holding this back until it becomes the default will cause less confusion and related issues to highlights imo

**Comment by 110y** [comment]
@lucario387 

> I personally believe the amount of times people write their max and min func are significantly more than clear, so it may cause some confusion in highlights if it's marked as a builtin func.

Got it 👍 
By the way, though I would agree with your concern regarding this PR, I think treesitter project should have a solid policy that defines when (nightly, release candidate, stable release etc.) we should follow language changes 😄

**Comment by ArtAndreev** [comment]
There is a mistake: these builtins are functions, not types.

**Comment by lucario387** [comment]
Agreed on that

**Comment by amaanq** [comment]
Go 1.21 is out now

**Pull request merged**
