### PR TITLE
feat(rust): improve indents

### PR DESCRIPTION
**Pull request by amaanq**

### CODE REVIEW

**Review by lucario387 — APPROVED** [review]

**Comment by lucario387** [comment]
Well time to kick it then :D 
I will remove it after a few hours

**Comment by clason** [comment]
The formatter? No, the formatter will stay. Either we change the format or learn to live with it.

(I strongly counsel everyone to develop some tolerance on formatting. Your professional live will be better for it.)

**Comment by amaanq** [comment]
I think (and would really hope) he meant to kick the newline node thing

**Comment by clason** [comment]
Better to be safe than sorry ;)

**Pull request merged**
