### PR TITLE
fix(swift): highlights

### PR DESCRIPTION
**Pull request by wojciech-kulik**
Improved highlighting for Swift

### CODE REVIEW

**Review by lucario387 — APPROVED** [review]

**Comment by clason** [comment]
@alex-pinkus

**Comment by clason** [comment]
I think we need to start looking for a new Swift maintainer...

**Comment by alex-pinkus** [comment]
@clason, I didn’t notice this because of all of the comments on the other thread…

**Comment by clason** [comment]
Sorry about that, then.

**Pull request merged**
