### PR TITLE
Ocaml: fix parser

### PR DESCRIPTION
**Pull request by stsewd**
Paths were changed https://github.com/tree-sitter/tree-sitter-ocaml/pull/41

### CODE REVIEW

**Comment by stsewd** [comment]
I'm not sure if this is going to work or if we need to add support for subpaths :) I'll test tomorrow...

**Comment by stsewd** [comment]
Nope, it didn't work, we need to adapt the code to work with subpaths.

**Comment by theHamsta** [comment]
Typescript works with subpaths.

**Comment by vigoux** [comment]
Closing this as fixed by #431

**Pull request closed without merging**
