### PR TITLE
chore(c): update queries from upstream

### PR DESCRIPTION
**Pull request by amaanq**
@lucario387 (indents)

### CODE REVIEW

**Comment by lucario387** [comment]
Do I just commit onto that branch directly?

**Comment by amaanq** [comment]
Yeah that works

**Comment by lucario387** [comment]
@amaanq I think it's fine now.
I only remove one if-else case of the 20 tested

**Comment by amaanq** [comment]
@fab4100 can you update ispc's C base to 0.20.3 and then update queries here

**Review by clason — APPROVED** [review]

**Comment by clason** [comment]
Is ispc still the blocker here? Maybe we should decouple (some) of the queries, at least temporarily.

**Comment by clason** [comment]
@amaanq yes, let's decouple the queries (at least for now) and mark `ispc` as Tier 4.

**Comment by lucario387** [comment]
cpp: 
> `invalid node type: else_clause`

So seems like the commit hash was incorrect

**Comment by fab4100** [comment]
@amaanq: The ISPC parser is updated, should I push changes/revert for the queries onto  `amaanq:update-c` ? (apologies for the delay, another task required priority)

**Comment by lucario387** [comment]
I'd say you should do the revert on this branch.

**Comment by lucario387** [comment]
Well whatever ispc did, it's not working ...

**Comment by clason** [comment]
Now only the (inherited) `indents` are failing.

**Comment by lucario387** [comment]
Most likely the same problem of `invalid node type: else_clause`

**Comment by clason** [comment]
Tests no longer pass, though...

**Comment by clason** [comment]
What's weird is that the failing languages _only_ inherit `cpp` and don't have any other queries themselves. And `cpp` itself is passing the tests.

**Comment by fab4100** [comment]
Failing indents for ISPC inherit from `c` and the file has additional queries, not just an `; inherits: c` statement.  It seems not only `cpp` inheritance fails.

**Comment by lucario387** [comment]
> Failing indents for ISPC inherit from `c` and the file has additional queries, not just an `; inherits: c` statement.  It seems not only `cpp` inheritance fails.

The problem is the same as tree-sitter-cpp a few days ago. It was bumped to 0.20.3, but 0.20.3 doesn't actually have the new else_clause node, only while using tree-sitter-c HEAD does such node appear

**Comment by clason** [comment]
So what you're saying is "tree-sitter-cpp needs another release" 😬

**Comment by lucario387** [comment]
> So what you're saying is "tree-sitter-cpp needs another release" 

Actually, `tree-sitter-c` is the one that needs to be bumped, which means cpp and all of its child :grimacing:

**Comment by clason** [comment]
All I'm hearing is "needs moar release"...

**Comment by lucario387** [comment]
Or "living on the edge" if we're to follow `tree-sitter-cpp`'s footstep (it references ts-c's head for grammar update)

**Comment by clason** [comment]
only arduino and ispc indents are still failing @ObserverOfTime @fab4100

**Comment by amaanq** [comment]
cpp hasn't been released (yet, maybe later today once jdrouhard reviews it)

**Comment by ObserverOfTime** [comment]
I'll wait for the release to avoid changing it back and forth.

**Comment by clason** [comment]
Makes sense; but there is some urgency here as this is blocking scheduled updates (and upstream Neovim bumps). At least ispc has no excuse for waiting ;)

**Comment by fab4100** [comment]
@clason I have re-generated the parser based on `tree-sitter-c 0.20.4`

**Comment by lucario387** [comment]
@amaanq tree-sitter-c 0.20.4 still doesn't have `else_clause` node ... or ispc somehow generates a non-else_clause parser

**Comment by clason** [comment]
Hmm, ispc indents are still breaking...

**Comment by lucario387** [comment]
The breaker is for sure still `else_clause` node not available. Targeting tree-sitter-c's `HEAD` and such node does appear though ...

**Comment by lucario387** [comment]
@clason I will just comment out all the if-else test for now, and only have if-else with braces to be supported

Once `else_clause` becomes available for a release again I will uncomment them

Let's not hold this longer

**Comment by amaanq** [comment]
> @amaanq tree-sitter-c 0.20.4 still doesn't have `else_clause` node ... or ispc somehow generates a non-else_clause parser

I just checked out v0.20.4 and can definitely see sym_else_clause

image

**Comment by lucario387** [comment]
Well the generated version with 0.20.4 of ispc doesn't have such node tho, that's very weird. Or is there something I'm missing here

**Comment by amaanq** [comment]
ISPC's grammar modifies if_statement

**Comment by lucario387** [comment]
well no wonder ...
Welp, @fab4100 You have to manually re-modify the if_statement then, or let's not inherit c for `indents.scm` for ispc anymore

**Comment by amaanq** [comment]
@fab4100 https://github.com/fab4100/tree-sitter-ispc/pull/2

**Comment by clason** [comment]
> @clason I will just comment out all the if-else test for now, and only have if-else with braces to be supported
> 
> Once `else_clause` becomes available for a release again I will uncomment them
> 
> Let's not hold this longer

To be clear: I'm talking about the query check, not the tests!

**Comment by clason** [comment]
@ObserverOfTime `cpp` has a new release now.

**Comment by ObserverOfTime** [comment]
Updated. (`3446bac828d5db2a6cf60ab31813c02ab53547a7`)

**Comment by clason** [comment]
Why is `ispc` indent query now failing again... 😭

**Comment by clason** [comment]
OK, that was painful. I'd be interested in a *post mortem* about what exactly got us into this mess, and how to _not_ get there again.

**Comment by amaanq** [comment]
finally.. :sweat_smile:

**Comment by lucario387** [comment]
How the addition of one syntax node breaks the entire ecosystem, part one:

**Comment by ObserverOfTime** [comment]
Clearly the solution is to remove C and its children. :^)

**Pull request merged**
