### PR TITLE
Removed pre installed parsers 

### PR DESCRIPTION
**Pull request by jpx40**
Hey, 
i removed changes introduced in https://github.com/nvim-treesitter/nvim-treesitter/commit/fe89bf17197fc5daead3878fb1328911b30fb022.

Reason:
It breaks nvim-treesitter with manually added parsers. I am using LazyVim as basis for my Config LazyVim adds most Parsers already, this commits breaks the manaual adding of Parsers. This is a little difficult if you using an distro.
I used Lazy.nvim to test Lazy.nvim to test it pre this Commit. My Config started to work again. It was tested on an clean Nvim build.

### CODE REVIEW

**Comment by lucario387** [comment]
It's already reverted.

**Comment by lucario387** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/commit/f197a15b0d1e8d555263af20add51450e5aaa1f0

**Comment by jpx40** [comment]
> It's already reverted.

it is? Cool man. i had an missunderstanding with one of maintainer, but this just brakes to much configs. Nvim-treesitter shoulden't dicide which parsers are installed.

**Comment by lucario387** [comment]
Well we received a lot of issues related to neovim bundled parsers not compatible with our queries. That was our way (although unsuccesfully) to resolve the root cause.

**Comment by jpx40** [comment]
> Well we received a lot of issues related to neovim bundled parsers not compatible with our queries. That was our way (although unsuccesfully) to resolve the root cause.

yeah, thanks for reverting this.

**Comment by jpx40** [comment]
> Well we received a lot of issues related to neovim bundled parsers not compatible with our queries. That was our way (although unsuccesfully) to resolve the root cause.

Pls test pushes to master in the future to prevent issues like this.

**Comment by lucario387** [comment]
Not that we don't test, we don't expect other consumers to call `setup()` multiple times (also lazyloading ...)

**Comment by jpx40** [comment]
> Not that we don't test, we don't expect other consumers to call `setup()` multiple times (also lazyloading ...)

my, fault woth lazy loading. my whole config is built around lazy.nvim.

**Comment by jpx40** [comment]
ok,  might try this

**Pull request closed without merging**
