### PR TITLE
ci: skip swift check on neovim stable

### PR DESCRIPTION
**Pull request by dundargoc**
This is meant as a temporary workaround until neovim 0.7 is released.

More context: https://github.com/nvim-treesitter/nvim-treesitter/issues/2313#issuecomment-1025258357

### CODE REVIEW

**Review by clason — APPROVED** [review]

**Comment by clason** [comment]
Screenshot 2022-01-31 at 22 52 33

I like those numbers... :D

**Comment by dundargoc** [comment]
I'll be honest, I'm not a great fan of this workaround because it's a bit ugly. But given that this is a temporary workaround and because I've given good context on what to remove and when I still think this could be worth it (especially considering the CI times are reduced by more than 5-7 times).

**Comment by clason** [comment]
Yeah, it's not great, but think of all the trees this is saving!

**Comment by dundargoc** [comment]
:evergreen_tree: :deciduous_tree: :christmas_tree: :tanabata_tree: :palm_tree:

**Review by theHamsta — APPROVED** [review]
yeah, I guess that's ok for a temporal thingy.

**Pull request merged**
