### PR TITLE
feat: add HCL file type detection

### PR DESCRIPTION
**Pull request by khuedoan**
HCL parser was added in https://github.com/nvim-treesitter/nvim-treesitter/pull/1445, but neovim does not set the correct filetype for `*.hcl`, `*.tf` and `*.tfvars` by default:

image

This PR adds a `ftdetect` rule for those files:

image

### CODE REVIEW

**Review by theHamsta — APPROVED** [review]

**Comment by gegoune** [comment]
Doesn't vim/nvim already set some filetype to *.tf files?

**Comment by khuedoan** [comment]
Look like the default is TinyFugue, I just notice the [vim-terraform plugin has an `ftdetect` config](https://github.com/hashivim/vim-terraform/blob/master/ftdetect/hcl.vim), what is the correct way to introduce that file to this project? The license is ISC License (functionally equivalent to the BSD 2-Clause and MIT licenses)

**Comment by gegoune** [comment]
Id be happy to have it set here. Could remove vim-terraform. 😀

**Comment by theHamsta** [comment]
@khuedoan best solution is always to ask the authors

**Comment by vigoux** [comment]
@Mergify refresh

**Pull request merged**
