### PR TITLE
highlights(beancount): update on latest updates

### PR DESCRIPTION
**Pull request by polarmutex**
changes to highlighting on the newest commit that will land on the next lock file update

### CODE REVIEW

**Comment by clason** [comment]
please include the lockfile update in your PR (this way, neither the lockfile update nor your PR can be merged as they fail the tests...)

**Review by clason — APPROVED** [review]

**Comment by clason** [comment]
Thanks! I'll merge once you mark it as ready.

**Comment by clason** [comment]
sigh.

**Comment by clason** [comment]
Looks like there was a merge race; could you please rebase on master? Sorry about that.

**Review by theHamsta — APPROVED** [review]
Thank you!

As @clason, mentioned. Apparently, I merged the lockfile update before this got merged. Sorry.

**Pull request merged**
