### PR TITLE
Styled components injection

### PR DESCRIPTION
**Pull request by stevenocchipinti**
Hi,

This is my first attempt at a contribution, any feedback welcome.
I've been monitoring #1111 and decided to try it myself.

I have more detailed messages in the commits, including which cases I've attempted to support.
I'm sure there are plenty of cases missing but I'm hoping this will be a good start.

If there is an easier, more generic way to handle more cases, please let me know.

### CODE REVIEW

**Review by kyazdani42 — APPROVED** [review]
LGTM, waiting for @steelsojka review because i've been away for quite a long time :)

**Comment by steelsojka** [comment]
I don't this will work. The problem is styled components are pure CSS. The CSS parser can't handle javascript string tempate literals. For example:

```css
.some-class {
  margin: ${someVar}
}
```

The css parser would fail at the variable. For this to be full supported we need a custom css parser that can handle the JS template variables.

**Comment by steelsojka** [comment]
If this is for partial support without any variables then this would work just fine.

**Comment by stevenocchipinti** [comment]
Yea, that also was mentioned in #1111 and I had no idea how to handle that 😅 
This is just for a few basic cases.

How would a custom parser work, would it be able to reuse the existing css parser but just add support for including `${}` and then reuse the existing javascript parser for inside the `${}`?

**Comment by stevenocchipinti** [comment]
Also, I've realised I can put a [`queries/ecma` directory in my config](https://github.com/stevenocchipinti/dotvim/tree/master/queries/ecma), so feel free to close this if you'd rather not have an incomplete solution merged in.

**Comment by theHamsta** [comment]
@stevenocchipinti you can easily create a grammar that extends CSS. Maybe a good resource is the JSONC parser that adds comments to JSON or the CUDA parser that adds CUDA's <<<...>>> call syntax to C++.

Find out in which grammatical position variable expansions can occur add replace the original rule with a `choice` between `original` and variable expansion

**Comment by theHamsta** [comment]
@steelsojka @kyazdani42 should we merge this? Or will incomplete CSS be annoying? I suppose that partial support should be ok as the CSS should be able to recover from JS injections. You are the React experts...

**Comment by kyazdani42** [comment]
i'm ok for partial support, would be better than having plain js strings anyway.

**Comment by sQVe** [comment]
Would it be possible to revert this?

It seems like the injection breaks very open, at least when working with `emotion`/`styled-components`, and then applies the `Error` highlight `gui` styling. This hurts readability by a large margin.

@theHamsta

**Comment by theHamsta** [comment]
@sQVe any reason why  you have the TSError highlighting enabled? I don't think it's useful in any  situation. Maybe one could quickly add a css-with-template-braces grammar

**Comment by sQVe** [comment]
@theHamsta No specific reason from my part. I'm just using this plugin and `gruvbox.nvim` and getting pretty bad highlighting.

Are you saying that TSError should be removed as a highlight?

**Comment by sQVe** [comment]
It seems like `TSError` is linked to `Error` somewhere, which is causing the issues for me. Setting the `TSError` highlight fixes things but... I don't know - this feels like something that should be handled by `nvim-treesitter`.

**Comment by theHamsta** [comment]
At least, the default from this plugin is not highlight it as it's mostly annoying when it applies to half finished text or parts of the document that the parser not fully supports. But I understand your complaint about adding an injection that almost certainly fail. I'll have a look whether it can be easily fixed (e.g. by having CSS with JS injections)

**Pull request merged**
