### PR TITLE
chore: show errors output during async installation

### PR DESCRIPTION
**Pull request by theHamsta**
Collect stdout/stderr of commands and only show them on command failure

Looks like this:
image

image

Screenshot_20210430_165907

I don't know why the users has to press `<cr>` an additional time after we show the error

Before:
image

Disclaimer: I have very little experience with `luv`

### CODE REVIEW

**Comment by kyazdani42** [comment]
is this ready ?

**Comment by theHamsta** [comment]
From my side yes. Maybe one could change the curl command to omit progress.

**Review by kyazdani42 — APPROVED** [review]
code looks allright to me, i could not test it's erroring output though

**Comment by theHamsta** [comment]
You can just insert an error in an url or install from a grammar.js with errors.

**Comment by theHamsta** [comment]
@kyazdani42 is the double "press enter" a blocker for this PR?

**Comment by kyazdani42** [comment]
@theHamsta i don't think so, go for it the errors are better than before :)

**Pull request merged**
