### PR TITLE
update R queries

### PR DESCRIPTION
**Pull request by kevinushey**
Related to recent updates to the R tree-sitter grammar: https://github.com/nvim-treesitter/nvim-treesitter/pull/3817

### CODE REVIEW

**Comment by clason** [comment]
Indentation test for R fail now. Could you take a look at it?

**Comment by kevinushey** [comment]
I see this when I try to run tests locally:

```
$ ./scripts/run_tests.sh
Error detected while processing command line:
E492: Not an editor command: PlenaryBustedDirectory tests/ { minimal_init = './scripts/minimal_init.lua' }
```

What's the right way for me to get `plenary.vim` installed for local testing?

**Comment by clason** [comment]
I can't help more than pointing to the test scripts (I don't think it matters as long as `plenary.nvim` is in runtimepath).

I personally just watch CI and then manually execute whatever the failing test does.

**Comment by kevinushey** [comment]
Looks like it gets installed on CI here:

https://github.com/kevinushey/nvim-treesitter/blob/6bf1950ada77bd411163ca071a46bb3552c3e1fa/.github/workflows/tests.yml#L33-L39

so I guess I have to run that locally first. Will give it a shot...

**Comment by clason** [comment]
You can use the trick from here in your local copy of the minimal init.lua (just replace packer by plenary):
https://github.com/nvim-lua/kickstart.nvim/blob/c8a140577832ed4f958f4964400b2591abea3825/init.lua#L1-L8

**Comment by kevinushey** [comment]
I can't figure out how to get neovim to use the local indentation query files when running tests. :-/

**Comment by clason** [comment]
just copy them to your local `.config/nvim/queries` directory

**Comment by kevinushey** [comment]
Doesn't work for me.

https://neovim.io/doc/user/treesitter.html#treesitter-query states that it looks for queries using `runtimepath`, but even with me making sure `"."` comes first in `runtimepath` the queries bundled in the repository aren't used.

I don't have the bandwidth to debug or contribute further so I'm just going to roll back the changes in the R grammar.

**Comment by clason** [comment]
Yeah, we really need a `make test ` to make it easier to test non-highlighting queries. I'll try to sort the indents out this weekend.

**Comment by clason** [comment]
Looks like you indeed reverted the grammar improvements, so this is moot for now. Feel free to reopen when you re-add (some of) them!

**Pull request closed without merging**
