### PR TITLE
feat: add qmldir

### PR DESCRIPTION
**Pull request by amaanq**
https://doc.qt.io/qt-6/qtqml-modules-qmldir.html

cc: @Decodetalkers

### CODE REVIEW

**Comment by Decodetalkers** [comment]
image
good

**Review by ObserverOfTime — APPROVED** [review]

**Comment by amaanq** [comment]
The occasionally-failing CIs are a bit annoying...

**Comment by Decodetalkers** [comment]
you foget to add the download link to repo..

**Comment by amaanq** [comment]
> you foget to add the download link to repo..
> 
> Emm, you foget the parsers.lua

Oh, good catch sorry!

**Comment by ObserverOfTime** [comment]
Oh, I didn't notice that either. Shouldn't be reviewing stuff when I just woke up.

**Comment by amaanq** [comment]
> Oh, I didn't notice that either. Shouldn't be reviewing stuff when I just woke up.

And I shouldn't be merging when I'm half asleep writing a paper :laughing:

**Pull request merged**
