### PR TITLE
fix(incremental-selection): second attempt at fixing command

### PR DESCRIPTION
**Pull request by MariaSolOs**
I was a bit too eager with #6001. As mentioned in there, the change doesn't fully fix the issue anyway (it does get rid of the error though) and it also seems to cause other problems (like https://github.com/nvim-treesitter/nvim-treesitter/pull/6001#issuecomment-1913719917).

This solution is the one proposed by @monkoose

### CODE REVIEW

**Comment by clason** [comment]
Sorry, we don't look back (sharks don't look back, because sharks don't have necks).

Is there no way to fix this? The whole `keymap` thing is sus, of course, but can't we export a Lua function that people on master can map directly and avoid the issue?

**Comment by MariaSolOs** [comment]
> Sorry, we don't look back (sharks don't look back, because sharks don't have necks).

Sad. They won't ever be able to enjoy a good neck massage.

> Is there no way to fix this? The whole `keymap` thing is sus, of course, but can't we export a Lua function that people on master can map directly and avoid the issue?

Unfortunately this surpasses my Treesitter knowledge.

**Comment by zeertzjq** [comment]
Does adding `<C-U>` after `:` not work?

**Comment by monkoose** [comment]
Is there a reason why getpos('v') isn't used instead of `'<` and `'>`? So hacks to enter command line could be dropped.

**Comment by clason** [comment]
It has nothing to do with treesitter, actually; it's just about the (horrible, _horrible_) way that nvim-treesitter customizes mappings.

(Which, to be fair, predated Nvim's API for mapping Lua functions directly by quite a bit. Unfortunately, the design was such that adapting it was infeasible.)

**Comment by clason** [comment]
> Is there a reason why `getpos('v')` isn't used instead of `'<` and `'>`? So hacks to enter command line could be dropped.

Worth a try. PR welcome!

**Comment by MariaSolOs** [comment]
As a shark, I'll close this PR for now.

**Comment by clason** [comment]
> Does adding `<C-U>` after `:` not work?

You could try this first, though?

**Comment by MariaSolOs** [comment]
> > Does adding `<C-U>` after `:` not work?
> 
> You could try this first, though?

True, it's worth a try :)

**Comment by MariaSolOs** [comment]
> Does adding <C-U> after : not work?

Okay no, it doesn't work. The error still appears, and the scope isn't correctly incremented.

**Comment by clason** [comment]
Ah, OK, pity. Are you game for more tests?

**Comment by MariaSolOs** [comment]
> Ah, OK, pity. Are you game for more tests?

Always ;)

**Comment by MariaSolOs** [comment]
> Then try @monkoose's suggestion:
> 
> 1. replace here
>    https://github.com/nvim-treesitter/nvim-treesitter/blob/5f950cdcb82d2cf74e6b30338897b3a4897f52b3/lua/nvim-treesitter/incremental_selection.lua#L26-L27
>    
>    `"'<"` and `"'>"` by `"v"` and `"."`, respectively (compare `range_from_selection` in `vim.lsp.buf`);
> 2. replace here  https://github.com/nvim-treesitter/nvim-treesitter/blob/5f950cdcb82d2cf74e6b30338897b3a4897f52b3/lua/nvim-treesitter/incremental_selection.lua#L151
>    
>    the `string.format(...)` by `M[funcname]`.

It worked!

**Comment by sp3ctum** [comment]
Nice!
Not sure about the shark stuff (feeling optimistic though) but this does seem to fix the issue for me. Thanks so much, this was driving me nuts. 😄

**Pull request merged**
