### PR TITLE
injections(lua): fix cdef injection

### LINKED ISSUE #1840: Highlighting of Lua `ffi.cdef` string is strange and inconsistent across different quoting types
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`

### Describe the bug

Highlighting of Lua `ffi.cdef` string is strange and inconsistent across different quoting types

### To Reproduce

Open a Lua file with `ffi.cdef`.

When single quotes are used, the first character of `ffi.cdef` string is highlighted as `TSString`:

Screenshot_20210920_074316

When double quotes are used, all of `ffi.cdef` string is highlighted as `TSString`:

Screenshot_20210920_074707

When double square brackets are used, the opening and closing square brackets have different highlighting, and the highlighting of the function definition is also wrong (`TSString` is used for types):

Screenshot_20210920_075035

### Expected behavior

Lua `ffi.cdef` string is always highlighted as C.

### Output of `:checkhealth nvim_treesitter`

```markdown
health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.0 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.9.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - python         ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.6.0-dev+311-ge61ea7772e
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-git/src/build/config -I/build/neovim-git/src/neovim-git/src -I/usr/include -I/build/neovim-git/src/build/src/nvim/auto -I/build/neovim-git/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### PR DESCRIPTION
**Pull request by theHamsta**
Fixes #1840

image

@zeertzjq

### CODE REVIEW

**Comment by zeertzjq** [comment]
I guess this won't work for Lua long brackets. I don't think anyone will use long brackets for `cdef` though.

**Review by stsewd — APPROVED** [review]
yeah, this would break for more than 3 brackets, but should cover most cases.

**Comment by stsewd** [comment]
@akinsho @ancientstraits you can try adding a query like this for viml injections in lua (dhttps://github.com/nvim-treesitter/nvim-treesitter/pull/1780/)

**Comment by akinsho** [comment]
@stsewd thanks for pointing me to this PR. I tried

```scheme
(
  (function_call
    (field_expression (property_identifier) @_cmd_identifier)
    (arguments (string) @vim)
  )
  (#eq? @_cmd_identifier "cmd")
  (#match? @vim "^[\"']")
  (#offset! @vim 0 1 0 -1)
)

(
  (function_call
    (field_expression (property_identifier) @_cmd_identifier)
    (arguments (string) @vim)
  )
  (#eq? @_cmd_identifier "cmd")
  (#match? @vim "^\\[\\[")
  (#offset! @vim 0 2 0 -2)
)
```

and the following highlights query
```scheme
(
  (function_call
    (field_expression (property_identifier) @_cmd_identifier)
    (arguments (string) @none)
  )
  (#eq? @_cmd_identifier "cmd")
)
```

This seems to work to remove the off by one issue I was finding but doesn't work if there are new lines for example 
```lua
vim.cmd [[autocmd BufEnter * echomsg 'Hello World']]
vim.cmd [[
 autocmd BufEnter * echomsg 'Hello World'
]]
```
the first is highlighted but the second isn't, so this doesn't work if there are new lines after the `[[` marker

**Comment by stsewd** [comment]
@akinsho looks like the match predicate doesn't work with multiline nodes :/

https://github.com/neovim/neovim/blob/ec4731d982031e363a59efd4566fc72234bb43c8/runtime/lua/vim/treesitter/query.lua#L243-L245

**Comment by stsewd** [comment]
another solution would be to change the lua grammar to identify the string start/end as separate nodes https://github.com/nvim-treesitter/tree-sitter-lua, similar to python https://github.com/tree-sitter/tree-sitter-python/blob/9b84b7fd9da1aa74c8a8afae58b7dcc4c109cda4/grammar.js#L869

**Comment by stsewd** [comment]
Went ahead and opened https://github.com/neovim/neovim/issues/15833

**Pull request merged**
