### PR TITLE
feat(markdown): conceal triple backticks and HTML entities

### PR DESCRIPTION
**Pull request by MariaSolOs**
Porting the queries that will be included in https://github.com/neovim/neovim/pull/25073.

### CODE REVIEW

**Review by clason — APPROVED** [review]

**Comment by adrian5** [comment]
Not to beat some dead horse, but has there been a change of mind regarding [codeblock conceal](https://github.com/nvim-treesitter/nvim-treesitter/issues/4801#issuecomment-1546845938) or is this unavoidable due to the wider neovim PR this is a part of?

**Comment by clason** [comment]
The latter.

**Comment by mawkler** [comment]
Is this supposed to work in Markdown files? Triple backticks still aren't concealed for me.

This is the config I'm using:

<details>
<summary><b>Click to expand</b></summary>

```lua
local root = vim.fn.fnamemodify(vim.fn.expand('$HOME') .. '/code-other/nvim-test-config', ':p')
for _, name in ipairs({ 'config', 'data', 'state', 'cache' }) do
  vim.env[('XDG_%s_HOME'):format(name:upper())] = root .. '/' .. name
end

-- bootstrap lazy.nvim
local lazypath = root .. '/plugins/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ 'git', 'clone', '--filter=blob:none', 'https://github.com/folke/lazy.nvim.git', lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

vim.g.mapleader = ' '

local plugins = {
  {
    'nvim-treesitter/nvim-treesitter',
    dependencies =  'nvim-treesitter/nvim-treesitter-textobjects',
    build = ':TSUpdate',
    opts = {
      ensure_installed = { 'markdown' },
      highlight = { enable = true },
    },
  },
}

vim.o.conceallevel = 2

require('lazy').setup(plugins, {
  root = root .. '/plugins',
})
```

</details>

Here's an example of a markdown file that I'm testing on:

    ```lua
    vim.o.conceallevel = 2
    ```

    ```
    foo bar
    ```

**Comment by mawkler** [comment]
@clason I'm testing with the config posted in my previous comment, which includes the line `vim.o.conceallevel = 2` :)

**Comment by lucario387** [comment]
Im having it concealed just fine, so not sure what's happening here

**Comment by mawkler** [comment]
Never mind, it was a misconfiguration on my part. I forgot that I can't use Lazy's `opts` for nvim-treesitter in my test config. I changed to the following, which works:

```lua
{
  'nvim-treesitter/nvim-treesitter',
  dependencies =  'nvim-treesitter/nvim-treesitter-textobjects',
  build = ':TSUpdate',
  config = function()
    require('nvim-treesitter.configs').setup({
      ensure_installed = { 'markdown' },
      highlight = { enable = true },
    })
  end
}
```

My guess is that the original problem was that I hadn't updated Neovim. Thanks for the help!

**Pull request merged**
