### PR TITLE
feat(parsers): Highlight wildcard imports

### PR DESCRIPTION
**Pull request by ValdezFOmar**

### CODE REVIEW

**Comment by ribru17** [comment]
Thank you, I think this is good. Would you mind also changing this for other languages that wildcards in imports, e.g. rust, java, etc.

**Comment by clason** [comment]
(Sorry to pile more work onto you, but consistency across languages is one of the primary project goals, and it helps to keep PRs/commits "atomic" in that sense.)

**Comment by ValdezFOmar** [comment]
No problem, it'll just take a bit of time since I'm not that familiar with all of those languages.

**Comment by ValdezFOmar** [comment]
I've added highlights for the languages I could find that allow wildcard imports, let me know if there's more missing. Captures for kotlin and groovy are missing because the parser exposes wildcard imports as a single anonymous node `".*"`, I'll open pull requests upstream to make it more convenient to highlight.

**Review by ribru17 — APPROVED** [review]

**Comment by ribru17** [comment]
Thank you!

**Comment by ValdezFOmar** [comment]
> I'll open pull requests upstream to make it more convenient to highlight.

- [ ] https://github.com/fwcd/tree-sitter-kotlin/pull/130#issue-2433253133

**Comment by clason** [comment]
Let's give it until the end of the week; if there's no upstream movement, I'd say we merge what we have and add a TODO for the remaining languages so we can pick this up in the future.

**Comment by clason** [comment]
@ValdezFOmar groovy parser has been updated, too; let me know when the queries are ready to be merged!

**Comment by ValdezFOmar** [comment]
@clason It should be good to go now

**Comment by clason** [comment]
Thanks!

**Pull request merged**
