### PR TITLE
feat(folds): add ts and js folds

### PR DESCRIPTION
**Pull request by steelsojka**

### CODE REVIEW

**Review by kyazdani42 — APPROVED** [review]
would typescript use javascript on this one too ? LGTM otherwise :)
PS: could you also add jsx :) ? would be great to fold groups of nested components !

**Comment by steelsojka** [comment]
There will inherit the JS folds. I'll add jsx to this as well

**Comment by steelsojka** [comment]
@kyazdani42 How does the jsx queries work? Are they just a part of the regular js files? I see a separate highlight file for jsx but I'm not sure how that is picked up.

**Review by vigoux — APPROVED** [review]

**Comment by kyazdani42** [comment]
@steelsojka i think there might result in bugs see #378

**Pull request merged**
