### PR TITLE
ci(tests): add optional workflow for generating grammars

### PR DESCRIPTION
**Pull request by clason**
run on PR by adding label `ci:generate` or manually via workflow dispatch

### CODE REVIEW

**Comment by clason** [comment]
Looks like CI can't handle the (memory) pressure:
* `ubuntu` gets OOM killed out of the gate, it looks like
* `macos` hangs but gets there eventually (1:40h)
* `windows` is... fine (surprisingly)? (0:30h) Let's see if it isn't a fluke.

**Comment by clason** [comment]
Also, @dlvandenberg @lucario387 indent tests fail for `angular` on the main branch (comments don't get indentented) -- does one of you see what's going on?

**Comment by dundargoc** [comment]
There's a significant overlap between `test-generate.yml` and `test-queries.yml`. I would just combine these two workflows into a single workflow or find a way to reuse the code parts.

**Comment by clason** [comment]
How would I do that? There's significant differences.

**Comment by clason** [comment]
The culprit is https://github.com/yuja/tree-sitter-qmljs (@yuja), which eats ~18Gb RAM on `tree-sitter generate src/grammar.json).

**Comment by clason** [comment]
Ok, things look better with tree-sitter 0.23.0 _but_:
* ubuntu still gets OOM-killed due to spawning multiple tree-sitter jobs in parallel
* macos still needs 1:40 because the runners are absolute potatoes (7 Gb -- thanks, Apple, I see you still believe in RAM austerity)
* windows is now done in 10min -- you go, girl!

**Comment by clason** [comment]
Setting the maximum number of jobs to 1 works but takes 20:15/18:30/22:30 -- okay for an optional test, but generating from grammar will become required eventually when `parser.c` is dropped from the repos.

**Comment by clason** [comment]
@dundargoc I think this is useful now -- if you have suggestions for improving the workflow(s) (in general), I'm all ears!

**Review by dundargoc — APPROVED** [review]

**Pull request merged**
