### PR TITLE
Add zig as compiler for parser

### PR DESCRIPTION
**Pull request by maxxnino**
From my feature request https://github.com/nvim-treesitter/nvim-treesitter/issues/1935

### CODE REVIEW

**Comment by ajitid** [comment]
> @maxxnino would using the zig compiler make stuff easier for Windows users?

Can confirm, it does!

Though I'm getting this error (on Windows) when running `:checkhealth`.

image

Any poiner to why it could be happening?

**Comment by maxxnino** [comment]
@ajitid It happen to me aswell, What is uv_dlsym btw
Untitled

**Comment by ajitid** [comment]
hey @maxxnino, I would suggest to install gcc via msys2 and add to path [using this way](https://www.devdungeon.com/content/install-gcc-compiler-windows-msys2-cc). I reinstalled treesitter and have got no errors now.

I don't know what caused this, but running healthcheck or opening any file crashes nvim in Windows Terminal (Powershell). Running Powershell app directly works fine.

**Comment by maxxnino** [comment]
@ajitid as i see some parser work, some don't. But luckly it work with my language. I already used gcc ( installed via scoop) in the past. I just don't want depend on gcc anymore.

**Comment by maxxnino** [comment]
@ajitid I just found out. Update to lastest nvim-treesitter and re install the parser. fix the prolem

- Example
```
:TSInstall css cpp json
```

**Pull request merged**
