### PR TITLE
Upgrade to tree-sitter-heex v0.4.0 and support slots

### PR DESCRIPTION
**Pull request by connorlay**
See https://github.com/connorlay/tree-sitter-heex/pull/10 for associated changes to tree-sitter-heex

This PR upgrades the lockfile to target tree-sitter-heex v0.4.0 and adds support for HEEx [Slots](https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html#module-slots).

### CODE REVIEW

**Review by theHamsta — APPROVED** [review]

**Comment by clason** [comment]
Lint failure is probably due to today's Stylua 0.12.0 update.

**Comment by theHamsta** [comment]
You can run the new stylua if you want or we merge with the failing test.

**Comment by clason** [comment]
Can we merge with the failing tests? I think we need to fix that (in a separate `chore: format with stylua 0.12.0` commit). There are minor changes to the config, anyway.

I'll do it once homebrew merges the update.

**Comment by clason** [comment]
Of course, could also simply manually apply these changes...

**Comment by theHamsta** [comment]
Of course I can.

**Comment by clason** [comment]
Then you are more powerful than I am :)

**Pull request merged**
