### PR TITLE
highlight(fish): dollar command substitution

### PR DESCRIPTION
**Pull request by ram02z**
Requires https://github.com/ram02z/tree-sitter-fish/pull/11

### CODE REVIEW

**Comment by ram02z** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/commit/16e3bad8b4e5129037f2b2fb873c0731b4ff0768 merged. Rerunning the CI should fix the failing checks.

**Comment by kyazdani42** [comment]
seems you query is still invalid, please rebase :)

**Review by theHamsta — CHANGES_REQUESTED** [review]
You probably just want to highlight the `$` and `(` `)` not the whole substitution

**Comment by ram02z** [comment]
> seems your query is still invalid, please rebase :)

Whoops, fixed.

**Comment by ram02z** [comment]
> You probably just want to highlight the `$` and `(` `)` not the whole substitution

`(command_substitution_dollar ["$" "(" ")"]) @punctuation.bracket` like this?

**Comment by theHamsta** [comment]
No more like `(command_substitution_dollar ["$" "(" ")"]  @punctuation.bracket)` or `(command_substitution_dollar "$"  @punctuation.bracket)` or  ` "$"  @punctuation.bracket`. I think you wanted to highlight the `$` sign

**Comment by ram02z** [comment]
>  think you wanted to highlight the `$` sign not the inside of the parenthesis

Ah yes, that is correct. Fixed now.

**Review by theHamsta — APPROVED** [review]

**Pull request merged**
