### PR TITLE
fix(utils): use pairs to iterate trees like upstream

### PR DESCRIPTION
**Pull request by Hippo0o**
not sure if it needs commit [feat(treesitter)!: incremental injection parsing ](https://github.com/neovim/neovim/commit/2ca076e45fb3f1c08f6a1a374834df0701b8d778) to work.

### CODE REVIEW

**Comment by clason** [comment]
What problem does this solve? Note that these functions will be removed in 1.0 (`main` branch) anyway.

**Comment by Hippo0o** [comment]
@clason i come a cross this issue when using incremental_selection
```
/usr/share/nvim/runtime/lua/vim/treesitter.lua:189: attempt to index local 'node_or_range' (a nil value)
stack traceback:
[string ":lua"]:4: in function '__index'
/usr/share/nvim/runtime/lua/vim/treesitter.lua:189: in function 'get_node_range'
...plugged/nvim-treesitter/lua/nvim-treesitter/ts_utils.lua:279: in function 'update_selection'
...treesitter/lua/nvim-treesitter/incremental_selection.lua:18: in function <...treesitter/lua/nvim-treesitter/incremental_selection.lua:14>
```
Because with incremental injections the response from :trees() can look something like that:
```
{ <userdata 1>, <userdata 2>, <userdata 3>,
  [51] = <userdata 4>,
  [52] = <userdata 5>,
  [53] = <userdata 6>
}
```
and ipairs iterates "up to the first absent index".

So the execution will land here:
https://github.com/nvim-treesitter/nvim-treesitter/blob/cb74c1c5aefd8b903f1b547d08d4df42be07aa2a/lua/nvim-treesitter/ts_utils.lua#L213-L214

**Comment by clason** [comment]
That function will also go away....

**Comment by Hippo0o** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/commit/58c868229044ac0892efeecee2d7706d7f6a00cb

**Pull request closed without merging**
