### PR TITLE
New stylua version

### PR DESCRIPTION
**Pull request by theHamsta**
Stylua has updated to a new version and the workflow also automatically updated. Should fix the version update

### CODE REVIEW

**Review by stsewd — COMMENTED** [review]
The indent test files shouldn't have been changed https://github.com/nvim-treesitter/nvim-treesitter/blob/master/.styluaignore

**Comment by stsewd** [comment]
you can just run `stylua .` from the root so the config file is taken into consideration.

**Comment by theHamsta** [comment]
But there is no reason why the tests should be excluded.

**Comment by stsewd** [comment]
> But there is no reason why the tests should be excluded.

Those files are testing how indentation behaves with the given inputs, but I haven't checked the tests to be honest

**Review by stsewd — APPROVED** [review]

**Pull request merged**
