### PR TITLE
refactor(queries): Remove quotes from properties in set! directive

### PR DESCRIPTION
**Pull request by ValdezFOmar**
follow-up from https://github.com/nvim-treesitter/nvim-treesitter/pull/6982

### CODE REVIEW

**Comment by ValdezFOmar** [comment]
@clason should this be done also in neovim? The docs use quoted properties:

https://github.com/neovim/neovim/blob/bdff50dee56ebf6de58d58315920abf2f8e262f7/runtime/doc/treesitter.txt#L340

**Comment by clason** [comment]
I would handle the docs when syncing the queries.

**Comment by ValdezFOmar** [comment]
Also, while doing this I notice this strange query, is this correct?

https://github.com/nvim-treesitter/nvim-treesitter/blob/f97e0de0053df1cb3b9f74b9b1239acced1b7d9a/queries/strace/injections.scm#L1-L2

**Comment by clason** [comment]
No, that's an obvious copypasta. A lot of queries are abandonware, unfortunately.

**Comment by clason** [comment]
Can you fix this (in a separate commit) while you're at it?

**Pull request merged**
