### PR TITLE
Update Capnp

### PR DESCRIPTION
**Pull request by amaanq**
Def gonna fail at first, indents are pain...

### CODE REVIEW

**Comment by lucario387** [comment]
My god looking at the indent file I can already see the horror :fearful: 

If you need some help then I can jump in

**Comment by amaanq** [comment]
> My god looking at the indent file I can already see the horror fearful
> 
> If you need some help then I can jump in

Yeah..I just pinged you on matrix abt that..slowly adding tests & reducing state counts for all my languages :laughing:

**Comment by lucario387** [comment]
I'm getting this error while running tests:
```
Fail	||	indent Cap'n Proto: new line: test.capnp[955]	
            ./tests/indent/common.lua:48: invalid option '%-105' to 'format'
            
            stack traceback:
            	./tests/indent/common.lua:48: in function 'fmt'
            	...te/pack/packer/start/plenary.nvim/lua/luassert/state.lua:90: in function 'format_argument'
            	...e/pack/packer/start/plenary.nvim/lua/luassert/assert.lua:125: in function 'format'
            	...e/pack/packer/start/plenary.nvim/lua/luassert/assert.lua:17: in function 'geterror'
            	...e/pack/packer/start/plenary.nvim/lua/luassert/assert.lua:50: in function 'same_indent'
            	./tests/indent/common.lua:80: in function 'compare_indent'
            	./tests/indent/common.lua:142: in function 'indent_new_line'
            	./tests/indent/common.lua:196: in function <./tests/indent/common.lua:194>
            	...
            	...cario387/dev/nvim-treesitter/tests/indent/capnp_spec.lua:28: in function <...cario387/dev/nvim-treesitter/tests/indent/capnp_spec.lua:16>
```
I suppose this is related to the queries

**Comment by amaanq** [comment]
> I'm getting this error while running tests:
> 
> ```
> Fail	||	indent Cap'n Proto: new line: test.capnp[955]	
>             ./tests/indent/common.lua:48: invalid option '%-105' to 'format'
>             
>             stack traceback:
>             	./tests/indent/common.lua:48: in function 'fmt'
>             	...te/pack/packer/start/plenary.nvim/lua/luassert/state.lua:90: in function 'format_argument'
>             	...e/pack/packer/start/plenary.nvim/lua/luassert/assert.lua:125: in function 'format'
>             	...e/pack/packer/start/plenary.nvim/lua/luassert/assert.lua:17: in function 'geterror'
>             	...e/pack/packer/start/plenary.nvim/lua/luassert/assert.lua:50: in function 'same_indent'
>             	./tests/indent/common.lua:80: in function 'compare_indent'
>             	./tests/indent/common.lua:142: in function 'indent_new_line'
>             	./tests/indent/common.lua:196: in function <./tests/indent/common.lua:194>
>             	...
>             	...cario387/dev/nvim-treesitter/tests/indent/capnp_spec.lua:28: in function <...cario387/dev/nvim-treesitter/tests/indent/capnp_spec.lua:16>
> ```
> 
> I suppose this is related to the queries

The queries are fine

**Review by lucario387 — APPROVED** [review]
I think it's fine, just need to fix the tests

**Comment by lucario387** [comment]
@amaanq Should I fix the tests and then merge this PR?

**Comment by amaanq** [comment]
go for it

**Comment by lucario387** [comment]
@amaanq just merged :+1:

**Pull request merged**
