### PR TITLE
Add extra language injections for latex

### PR DESCRIPTION
**Pull request by lnay**
Following a recent [pull request](https://github.com/latex-lsp/tree-sitter-latex/pull/89) to [the latex parser](https://github.com/latex-lsp/tree-sitter-latex/) treating environments defined by the `sagetex` latex package as "special". This pull request to `nvim-treesitter` is to enable Python language injections in these environments as they contain SageMath code (very similar to python, but there is no SageMath tree-sitter grammar available).

##### Minimal example:

```latex
\documentclass{article}
\usepackage{sagetex}

\begin{document}

\begin{sagesilent}
# python comment
print("Hello, SageTeX!")
\end{sagesilent}

\begin{sageblock}
# python comment
print("Hello, SageTeX!")
\end{sageblock}

\end{document}
```

### CODE REVIEW

**Review by clason — APPROVED** [review]

**Comment by clason** [comment]
Test failure is unrelated -- can you rebase on main?

**Comment by clason** [comment]
Rebase, not merge!

**Comment by lnay** [comment]
Sorry, I was hoping that the "update branch" button in github would give me the option, give me a minute.

**Comment by clason** [comment]
It doesn't; it's a trap ;)

Let's run the tests and see if they pass before doing anything else.

**Comment by clason** [comment]
Test failure is unrelated, so I'll just squash-merge.

**Comment by ForrestHilton** [comment]
It would also be desirable for the python treesitter to be applied to sage files by default like it does in helix.

**Comment by clason** [comment]
That's a different issue, and easily fixed using `vim.treesitter.language.register('latex', 'sage')`.

**Pull request merged**
