### PR TITLE
highlights(ocaml): add all builtin functions

### PR DESCRIPTION
**Pull request by Akmadan23**
I noticed that there were only 4 builtin functions listed, so I added all the others.

### CODE REVIEW

**Comment by amaanq** [comment]
@undu

**Comment by ObserverOfTime** [comment]
FWIW the current builtins seem more like `@exception` to me.

**Comment by XVilka** [comment]
I also should note that OCaml changes standard librar{y,ies} (compiler Stdlib, but also Base/Core as well) somewhat often, mostly by adding new functions though, but sometimes also deprecating.

**Comment by Akmadan23** [comment]
Ok, got it. I just thought that since they are in scope by default they could be considered builtin, but I totally see the reason why they are not. Sorry for the inconvenience.

**Comment by clason** [comment]
No worries. There could still be _some_ missing from the current list (if things change as often as they seem to do), so a PR adding only those might still be useful.

**Pull request closed without merging**
