### PR TITLE
fix: refactor after upstream refactor

### PR DESCRIPTION
**Pull request by vigoux**
Tiny tiny PR just to adapt to latest upstream/nvim changes.

### CODE REVIEW

**Comment by steelsojka** [comment]
Does this mean we can implement the `is?` predicate and it will work with the highlighter?!

**Comment by vigoux** [comment]
> Does this mean we can implement the `is?` predicate and it will work with the highlighter?!

Hehe... Yes ;-)

**Comment by vigoux** [comment]
I would like at least 2 reviews on this one, just to be sure nothing breaks, so let's wait for a while.

**Comment by steelsojka** [comment]
@theHamsta  The removed ones can be handled by the `immediate child operator`.

First `(function . (identfifier))`
Last `(function (identfier) .)`
Adjacent `((comment) . (function))`

It's completely undocumented, but we found it through a PR to treesitter back in feb.

**Comment by theHamsta** [comment]
A so you can to match conses. Nice! But then the PR should remove usages of `last?`

**Comment by steelsojka** [comment]
@theHamsta I didn't find any usages of `last?` in any queries. If we missed something, we can submit another PR to fix it.

**Comment by theHamsta** [comment]
Indeed, in the end we needed `has-ancestor?` instead of `last?`

**Comment by stsewd** [comment]
@steelsojka maybe we should send a PR upstream documenting them

**Pull request merged**
