### PR TITLE
Add tree-sitter-regex

### PR DESCRIPTION
**Pull request by theHamsta**
This might be interesting for injected highlighting. So we could wait for that to come.

### CODE REVIEW

**Comment by vigoux** [comment]
Oh that's nice !
Language injection is on our todo list, but it requires a bit of work on neovim's side, so we might want to dig into this first.

**Comment by vigoux** [comment]
Can we add this to the `README.md` too ?

**Comment by theHamsta** [comment]
You mean the name of the parser of that it may be useful for language injection?

**Comment by vigoux** [comment]
The name of the parser I think, but also you should add it to the `CONTRIBUTING.md` that one can use this parser for regexes

**Comment by theHamsta** [comment]
I didn't add it to `CONTRIBUTING.md` since I don't know how the language injection stuff works exactly. Maybe you can add a language injection section once your PR is merge in Neovim?

**Comment by vigoux** [comment]
Yep, I need to open it before though...

**Comment by vigoux** [comment]
@theHamsta would you like to be the maintainer of this language too ?

**Comment by theHamsta** [comment]
Would be ok with that.

**Pull request merged**
