### PR TITLE
fix(yaml): lower string priority for helm injections

### PR DESCRIPTION
**Pull request by qvalentin**
see also https://github.com/nvim-treesitter/nvim-treesitter/pull/6050

### CODE REVIEW

**Comment by kmoschcau** [comment]
You might want to change the priority to 99 instead to keep in line with the rest.

**Comment by clason** [comment]
No, 90 is the documented priority for captures that should give precedence to injections.

**Comment by kmoschcau** [comment]
Also if you want to make this really work, you'd need to lower ALL YAML highlights, because helm can appear anywhere in a YAML file.

**Comment by clason** [comment]
Let me close this until we have a proper issue describing what is and what should be happening.

**Comment by lucario387** [comment]
This is just another chain of events that happened, previous case was with PHP highlights, where there was no way to have HTML highlights without breaking PHP. Do note that this does work with old treesitter (first-win order).

**Pull request closed without merging**
