### PR TITLE
Try expr rust

### PR DESCRIPTION
**Pull request by theHamsta**

### CODE REVIEW

**Comment by vigoux** [comment]
Be, careful, most of the changes are unrelated here.

**Review by vigoux — APPROVED** [review]

**Comment by theHamsta** [comment]
Your were faster than I could rebase :open_mouth:

**Comment by theHamsta** [comment]
Your were faster than I could rebase :open_mouth:

**Comment by theHamsta** [comment]
Your were faster than I could rebase :open_mouth:

**Comment by vigoux** [comment]
Lol yeah, sorry for that :laughing:

**Comment by theHamsta** [comment]
No, need to feel sorry. Was just admiring how fast you are :+1:

and my internet is really slow. It even double posted here...

**Pull request merged**
