### PR TITLE
feat: allow a custom revision in install_info

### PR DESCRIPTION
**Pull request by lewis6991**
Haven't put much thought into the API for this, but I need this so I can do:

```lua
local c_info = require "nvim-treesitter.parsers".configs.c.install_info
c_info.url = 'https://github.com/neovim/tree-sitter-c'
c_info.revision = 'nvimc'
```

### CODE REVIEW

**Review by lucario387 — APPROVED** [review]

**Comment by clason** [comment]
@lewis6991 do you still need this now that the commits on that branch are upstreamed?

**Comment by lewis6991** [comment]
Yes, it's useful for development.

**Comment by clason** [comment]
But you're not setting revision in this snippet?

**Comment by clason** [comment]
(And honestly, while developing you should just add the parser repo to rtp.)

**Comment by clason** [comment]
It's part of a general clean-up, and a transition of this repo away from the single point of entry. With the upstream changes, the installation part of this repo is becoming less and less important, so I'm trying to minimize surface area and maintenance cost.

**Comment by clason** [comment]
You still haven't explained what you need the `revision` field for. But no matter, I can see where this is going and will step away.

**Comment by lewis6991** [comment]
I don't need it right now so I can't provide one.

**Pull request merged**
