### PR TITLE
fix(go): update queries from upstream

### PR DESCRIPTION
**Pull request by amaanq**

### CODE REVIEW

**Review by clason — APPROVED** [review]

**Comment by clason** [comment]
you also need to fix the languages inheriting from Go (`templ`).

**Comment by amaanq** [comment]
the grammar would have to update

**Comment by vrischmann** [comment]
> the grammar would have to update

Hi, I'm the maintainer of the templ grammar. Would you mind pointing me to the change in the go gramma so that I can take a look ?

**Comment by lucario387** [comment]
> > the grammar would have to update
> 
> 
> 
> Hi, I'm the maintainer of the templ grammar. Would you mind pointing me to the change in the go gramma so that I can take a look ? 

https://github.com/tree-sitter/tree-sitter-go/commit/b82ab803d887002a0af11f6ce63d72884580bf33

**Comment by vrischmann** [comment]
Thanks. Sorry I'm hijacking this PR but I'm confused about what's broken because the templ grammar doesn't use `method_spec`, and the templ queries don't reference them either. 
What am I missing ?

**Comment by clason** [comment]
You need to regenerate your parser from the `grammar.js` to pull in the changed go `grammar.js`. Since templ extends Go, any changes to the Go queries also affect templ. So if Go makes breaking changes, you need to follow suit and regenerate your parser immediately.

**Comment by clason** [comment]
I would appreciate being more proactive about this, since this blocks other updates until this is fixed. (And it _will_ happen again, so this is something maintainers should include in their workflow; consider automating this somehow -- look at the C derivations under tree-sitter-grammars such as `arduino`.)

**Comment by vrischmann** [comment]
> I would appreciate being more proactive about this, since this blocks other updates until this is fixed. (And it _will_ happen again, so this is something maintainers should include in their workflow; consider automating this somehow -- look at the C derivations under tree-sitter-grammars such as `arduino`.)

I understand, I'll see what I can do about being more proactive. Thanks for the pointers.

**Comment by clason** [comment]
Ideally, this is something that upstream will take (more) seriously and add (more) support for.

**Comment by vrischmann** [comment]
Hi again. I've updated tree-sitter-templ (https://github.com/vrischmann/tree-sitter-templ/commit/65fae2cb1d92c746d06d38df37f5ec148e2269b1)

**Comment by clason** [comment]
Thanks!

**Comment by michaeldakin** [comment]
Hey guys, not sure if this is isolated to me but after updating TS via Lazy I am not getting hit with `Invalid node type "method_elem"` when opening Go files.

Another user posted on the [parent commit](https://github.com/nvim-treesitter/nvim-treesitter/commit/d90e11756da30959da59eeb8888ecf16e877d86a#commitcomment-140807855) with a similar issue without logs. 

I have already removed/re-installed the Go parser and ran `:TSInstallFromGrammar go` with no luck.

```
Error in decoration provider treesitter/highlighter.win:
Error executing lua: ...-4c91194/share/nvim/runtime/lua/vim/treesitter/query.lua:248: Query error at 42:2. Invalid node type "method_elem":
(method_elem
 ^

stack traceback:
        [C]: in function '_ts_parse_query'
        ...-4c91194/share/nvim/runtime/lua/vim/treesitter/query.lua:248: in function 'fn'
        ...EAD-4c91194/share/nvim/runtime/lua/vim/func/_memoize.lua:54: in function 'fn'
        ...EAD-4c91194/share/nvim/runtime/lua/vim/func/_memoize.lua:54: in function 'get'
        ...94/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:28: in function 'new'
        ...94/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:240: in function 'get_query'
        ...94/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:187: in function 'fn'
        ...4/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:489: in function 'for_each_tree'
        ...94/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:174: in function 'prepare_highlight_states'
        ...94/share/nvim/runtime/lua/vim/treesitter/highlight
```

**Comment by michaeldakin** [comment]
> This means you have invalid queries in your runtimepath. Read the pinned issue about invalid nodes.

Cheers @clason, I completely forgot to check #3092 rtp as I have used it in the past.
Found .so files within `~/.local/share/nvim/site/parser/` - cleared these out and working perfectly.

**Pull request merged**
