### PR TITLE
feat(json): injection for scripts field in package.json

### PR DESCRIPTION
**Pull request by ValdezFOmar**
Before:

image

After:

image

### CODE REVIEW

**Comment by ObserverOfTime** [comment]
Some scripts are batch rather than bash.

**Comment by ValdezFOmar** [comment]
Strange, the [documentation](https://docs.npmjs.com/cli/v10/using-npm/scripts#exiting) only mentions `sh`:

> Scripts are run by passing the line as a script argument to sh.

**Comment by ObserverOfTime** [comment]
See [_this_](https://docs.npmjs.com/cli/v10/commands/npm-run-script#script-shell) documentation.

**Comment by ValdezFOmar** [comment]
Then I agree this might not be appropriate.

**Comment by clason** [comment]
I was thinking there might be a smarter injection we can use to distinguish that, but JSON files are (often) _huge_ so performance is a critical concern. So I on the whole I agree we should not do this. It was a good idea, though!

**Pull request closed without merging**
