### PR TITLE
fix(t32): update queries from upstream

### PR DESCRIPTION
**Pull request by xasc**
Adds support for new node type `elif_block`.

### CODE REVIEW

**Comment by clason** [comment]
Please run `scripts/format-queries.lua queries/t32`.

**Comment by xasc** [comment]
Autoformatter applied. Thanks for the tip.

**Review by clason — APPROVED** [review]

**Comment by clason** [comment]
@xasc I know this is a big ask, but would you consider setting up a Github mirror for tree-sitter-t32? We had issues with gitlab being flaky or inaccessible from, e.g., Brazil, and that would reduce significant friction on our end. (I know relying on one -- and arguably this -- codeforge is not great, but the automation requires high reliability which the other codeforges simply don't (yet) have.)

(t32 is one out of only four parsers we pull from gitlab, and the only maintained one, so this would make a big difference for us.)

**Comment by xasc** [comment]
@clason I fully understand your perspective. Thanks for letting me know. I guess then I will just have to bite the bullet.

**Comment by clason** [comment]
If it's not too much to ask, that would be appreciated (other codeberg-hosted parsers also have github mirrors so I thought it'd be easy to set up).

**Pull request merged**
