### PR TITLE
feat(php): php 8.4 support

### PR DESCRIPTION
**Pull request by calebdw**
Hello!

This PR:
- adds php 8.4 support
- updates the php queries to be compatible with the BCs in https://github.com/tree-sitter/tree-sitter-php/pull/247
- fixes import highlights

I added myself to the list of php maintainers seeing as I also help maintain the tree-sitter-php grammar.

Thanks!

### CODE REVIEW

**Comment by ribru17** [comment]
Thanks! I think you need up to update the lockfile to get checks passing

**Comment by calebdw** [comment]
I'm aware :), I was going to update the lockfile when the upstream pr was merged

**Comment by ribru17** [comment]
Ah sorry I see this is draft now :sweat_smile:

**Comment by calebdw** [comment]
This should be good to go!

**Comment by calebdw** [comment]
Thank you!

**Comment by mehalter** [comment]
Hey! Glad to see these updates :D should this commit/PR have been marked as a breaking change since query groups are removed in the new revision? Just wanted to let it be known since this did break queries in other plugins and seeing breaking change indicators in the changelog is very useful for maintainers/developers.

**Comment by clason** [comment]
_All_ updates have to be considered as breaking, as this is still zerover. This is something we want to change after the 1.0 release, but for now it's caveat emptor.

**Comment by mehalter** [comment]
Awesome, thanks so much for the clarification!

**Comment by clason** [comment]
(To be clear, the difficulty here is that the breaking update happens on the parser side, not the query side -- and we have no control, and often no information, of that as the majority of parsers are still not versioned. That needs to change for us to receive and propagate downstream that information.)

**Pull request merged**
