### PR TITLE
Update all parsers and add workflow for automated parser updates

### PR DESCRIPTION
**Pull request by theHamsta**
- [x] Bump all parser versions and
- [x]  try to fix all breakages (except JS, tsx, ... left thoses parsers on old version)
- [x] create automatic PR workflow for bumping parser versions: https://github.com/marketplace/actions/create-pull-request

### CODE REVIEW

**Comment by theHamsta** [comment]
Did not update the JS family: too much changes.

This might be a first indication on what to do (the type of parameters changed):
```

 ; Variables
 ;----------
 
-(formal_parameters (identifier) @parameter)
+(formal_parameters (required_parameter (identifier) @parameter))
 
 (formal_parameters
   (rest_parameter
@@ -94,29 +94,32 @@
 
 ; ({ a }) => null
 (formal_parameters
+ (required_parameter
   (object_pattern
-    (shorthand_property_identifier) @parameter))
+   (shorthand_property_identifier) @parameter)))
 
 ; ({ a: b }) => null
 (formal_parameters
+ (required_parameter
   (object_pattern
-    (pair
-      value: (identifier) @parameter)))
+   (pair
+    value: (identifier) @parameter))))
 
 ; ([ a ]) => null
 (formal_parameters
+ (required_parameter
   (array_pattern
-    (identifier) @parameter))
+   (identifier) @parameter)))
 
 ; a => null
-(variable_declarator                                                                                                                                                                                        
-    value: (arrow_function                                                                                                                                                                                    
-      parameter: (identifier) @parameter))
+(arrow_function                                                                                                                                                                                    
+ parameter: (identifier) @parameter)
 
 ; optional parameters
-(formal_parameters
-  (assignment_pattern
-    (shorthand_property_identifier) @parameter))
+;(formal_parameters;
+ ;(optional_parameter;
+  ;(assignment_pattern;
+   ;(shorthand_property_identifier) @parameter)));
 
```

**Comment by theHamsta** [comment]
@euclidianAce can you check whether the updates for the teal queries are ok? What about the disappeared `functiondef` node?

**Comment by theHamsta** [comment]
It works: https://github.com/theHamsta/nvim-treesitter/pulls

**Review by kyazdani42 — APPROVED** [review]
@vigoux review this too before we merge.

**Comment by theHamsta** [comment]
Would also be cool to get the ok from @euclidianAce

**Comment by theHamsta** [comment]
I tried to merge the exact same PR on my repo and apparently the old version of `jq` does not support `--sort-keys` yet. Need to fix this.

**Comment by theHamsta** [comment]
image

We could open&close such PRs to trigger the tests...

**Review by vigoux — APPROVED** [review]
Gigantic and awesome work, again.

**Pull request merged**
