### PR TITLE
feat: add CSV, PSV, & TSV

### PR DESCRIPTION
**Pull request by amaanq**

### CODE REVIEW

**Comment by ObserverOfTime** [comment]
Where's PSV? :^)

**Comment by amaanq** [comment]
Oh I can add that..didn't know it was a thing :)

**Comment by ObserverOfTime** [comment]
I've seen it in some data dumps.

**Comment by amaanq** [comment]
added PSV

**Review by ObserverOfTime — APPROVED** [review]

**Comment by lucario387** [comment]
@amaanq for csv, all fields are text, as can be seen from the syntax tree

```
1, abcd, true, false, 1.2
```
The nodes in order are `text, text, boolean, boolean, text`

**Comment by amaanq** [comment]
you're right, I wrote this in like 30m at 3am for fun :sweat_smile: will fix shortly

**Pull request merged**
