### PR TITLE
highlights(typescript): `is` and `:` in type predicate

### PR DESCRIPTION
**Pull request by zweimach**
| Before | After |
| ------ | ----- |
| image | image |

### CODE REVIEW

**Review by amaanq — APPROVED** [review]

**Comment by amaanq** [comment]
Hmm, shouldn't `is` be `@keyword.operator`

**Comment by zweimach** [comment]
Yes, I think it could be. I put `is` under `@keyword` because `keyof` and `as` is also `@keyword`.

**Comment by amaanq** [comment]
`as` should be `@keyword.operator` too I'd think

**Comment by zweimach** [comment]
Okay, I got it.
So I take this chance to make some keywords `@keyword.operator`.
From `ecma`: `in`, `instanceof`, and `typeof`.
From `typescript`: `as`, `is`, `keyof`, and `satisfies`.

**Comment by amaanq** [comment]
I was fine with `is` as `@keyword` though :raised_eyebrow:

**Comment by amaanq** [comment]
Oh well...

**Comment by zweimach** [comment]
Thanks, and sorry about the delay.
I may have missed your comments, or I misunderstood your intentions.
Either way, I made a separate PR to clarify that `is` is not included as `@keyword.operator`.

**Pull request merged**
