### PR TITLE
RST: update queries

### PR DESCRIPTION
**Pull request by stsewd**
I have implemented some new nodes into the grammar.

### CODE REVIEW

**Comment by theHamsta** [comment]
Will this cause problems for people with the older parser version? I guess yes

**Comment by stsewd** [comment]
Yeah, this will break people using an old version of the grammar. I was thinking we could suggest

```vim
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
```

for people using vim-plug in the meantime.

**Comment by vigoux** [comment]
Ignoring unknown nodes is not possible, as actually query parsing is done by treesitter itself (the library) and it errors out to nvim. the problem of parser version is a problem that we would want to tackle, my proposal is pinning parsers commit versions, and updating them together with their queries when needed.

Anyway, as we don't have this (yet) implemented, I don't see any problem in blocking this PR, as we already merged queries updates before.

**Comment by theHamsta** [comment]
> Ignoring unknown nodes is not possible,

without processing the string forwarded to Neovim

**Comment by vigoux** [comment]
I think we are heading in the wrong direction. Our problem is having the plugin state consistent, we need to ensure that by piining parser versions, not by finding workarounds to try to fix queries so that they work with every version of the parser.

**Comment by theHamsta** [comment]
> I think we are heading in the wrong direction. Our problem is having the plugin state consistent, we need to ensure that by piining parser versions, not by finding workarounds to try to fix queries so that they work with every version of the parser.

We should just develop meaningful error messages and only load the parsers the user is using. Errors in the syntax can always happen when the users extend the queries and when the users use third party modules leverages or module API.

**Comment by vigoux** [comment]
What do you mean by `load the parsers the user is using` ?

**Comment by theHamsta** [comment]
Why annoy the user with an error in the Dart queries when they never use Dart. Our plugin loads all highlight queries on startup.

Would be better for the user when they get an error when they open a Dart file. "Error: in Dart queries file: ...."

**Comment by vigoux** [comment]
But how will a user have an error in the Dart query if he does not use it ? the query will not be parsed if no Dart file is opened.

**Comment by stsewd** [comment]
> But how will a user have an error in the Dart query if he does not use it ? the query will not be parsed if no Dart file is opened.

I think the CI or checkhealth could catch that

**Comment by theHamsta** [comment]
> But how will a user have an error in the Dart query if he does not use it ? the query will not be parsed if no Dart file is opened.

All the queries are opened on startup. This makes it incredible difficult to guess what file caused the problem and there were already complaints about startup time (though loading the queries should be fast).

**Comment by vigoux** [comment]
> All the queries are opened on startup.

That is not right and I will work on stopping to do this.

**Pull request merged**
