### PR TITLE
fix!: backport `ac9e755` from `main`

### PR DESCRIPTION
**Pull request by llllvvuu**
reference: https://github.com/nvim-treesitter/nvim-treesitter/commit/ac9e75594208e9c348417240df05afd826c78f59

Co-authored-by: Pham Huy Hoang <hoangtun0810@gmail.com>
Closes: neovim/neovim#25088

### CODE REVIEW

**Comment by clason** [comment]
Sorry, but the `master` branch still supports Neovim 0.9.x, which doesn't have the incremental injection PR that this commit relies on.

**Comment by lucario387** [comment]
If you want to backport this, there'll be a need to check for nightly version, and using `parse()` accordingly depending on such version

**Comment by llllvvuu** [comment]
Hold on, doesn't Lua just ignore extra arguments?
```lua
; lua
Lua 5.4.6  Copyright (C) 1994-2023 Lua.org, PUC-Rio
> function hello() print("world") end
> hello({ "foo", "bar", "baz" })
world
```

So backporting just the one line without backporting the tests should be entirely a no-op for `master`. I tested on 0.9.x and it's working fine. I updated the branch but I'm not sure if GitHub subscribes to branches for closed PRs.

**Comment by lucario387** [comment]
I did not know the signature of `parse()` in 0.9. Looks fine to me, if the changes only consist of `indent.lua` changes.

**Comment by lucario387** [comment]
I think this is fine to be backported as it doesn't affect 0.9, and does help for nightly users. cc-ing @clason

**Comment by clason** [comment]
> I updated the branch

That broke the PR. Please open a new one and we can merge it.

**Pull request closed without merging**
