### PR TITLE
feat(lang): add make

### PR DESCRIPTION
**Pull request by lewis6991**

### CODE REVIEW

**Comment by theHamsta** [comment]
Can you run `stylua` or exchange `"` by `'` in your Lua changes?

**Review by theHamsta — APPROVED** [review]
Looks nice! Thank you!

**Comment by theHamsta** [comment]
Is there anything missing in this PR? I guess this could already be merged.

**Comment by lewis6991** [comment]
I threw this together pretty quickly so I added WIP, but viewing this on some big makefiles, it is already much better than vim highlighting.

I guess I can refine this in other PR's.

**Comment by alemuller** [comment]
@lewis6991 I'm rewriting tree-sitter-make (see branch rewrite).

Originally I avoided using the external scanner. But since people seems to be okay with the extensive use of it (markdown call them multiple time at every line) I'll go that route (with moderation).

As a bonus, custom recipeprefix comes for free (and likely a pandora box of bugs because it will need to trigger a reparse).

```make
.RECIPEPREFIX = >
foo:
>echo $@
```

I'll try to update the queries on the tree-sitter-make as I rewrite. But I'll write the query with the intention of documentation, not to conform with the nvim-tree-sitter convention. Some gsub will need to be done.

Some context.

Makefile is a 30+ year old macro language, designed to be easy to parse a line at a time, with two passes, or more with SECONDEXPANSION. Can't really be done with GLR. However it should be possible to parse most files without issue. But will have all the same issues of using macros in C.

**Pull request merged**
