### PR TITLE
feat(install): make compiler selectable

### PR DESCRIPTION
**Pull request by theHamsta**
Compilers are selectable via `'nvim-treesitter.install'.compilers` (list of compilers) or environment variable CC

Addresses #502

### CODE REVIEW

**Comment by theHamsta** [comment]
Documentation for this will go to Windows wiki. On Linux/MacOS it shouldn't really matter which C compiler is used. `CC` is mostly the favorite compiler of the user.

**Review by kyazdani42 — APPROVED** [review]
lgtm :)

**Comment by theHamsta** [comment]
@osherbz FYI, with this you can just use 

```lua
require 'nvim-treesitter.install'.compilers = { "clang" }
```

The new default would be
```
M.compilers = { vim.fn.getenv('CC'), "cc", "gcc", "clang" }
```
Do you think we should prefer `clang` due to the problems you experienced? gcc does not install `cc` but it's currently preferred over clang.

**Comment by osherbz** [comment]
@theHamsta 

No, I personally think `require 'nvim-treesitter.install'.compilers = { "clang" }` will be better. gcc is more common.
We should add this information into windows-support or to README.md.
And updating window-support troubleshooting  (instead of removing compilers form path we will specify the compiler by your command).

**Comment by osherbz** [comment]
@theHamsta  Can you make the wiki editable? please, I want to update the windows-support.md

**Comment by theHamsta** [comment]
@kontheocharis I don't have the rights to make the wiki editable. I already asked `@vigoux`.

**Comment by kontheocharis** [comment]
I assume you tagged me by accident... @theHamsta

**Pull request merged**
