### PR TITLE
feat(julia/highlights): Add `as` keyword

### PR DESCRIPTION
**Pull request by savq**

### CODE REVIEW

**Review by clason — APPROVED** [review]

**Comment by amaanq** [comment]
Would it not be `@keyword`?

**Comment by savq** [comment]
`as` can only be used inside `import` statements, and all the other import related keywords use `@include` so I think it's fine.

**Comment by clason** [comment]
This is similar to `then` being captured as `@conditional` in Lua's `if foo then bar end`.

**Comment by amaanq** [comment]
> `as` can only be used inside `import` statements, and all the other import related keywords use `@include` so I think it's fine.

gotcha, just wasn't sure if it was only used here

**Review by theHamsta — APPROVED** [review]

**Pull request merged**
