### PR TITLE
highlights(python): add "except*"

### PR DESCRIPTION
**Pull request by theHamsta**
Added in https://github.com/tree-sitter/tree-sitter-python/pull/176

About the feature https://realpython.com/python311-exception-groups/#exception-groups-and-except-in-python-311

### CODE REVIEW

**Review by stsewd — APPROVED** [review]

**Comment by Shinzu** [comment]
Hello,

not sure if this is the right place, but it seems this change broke something:

checkhealth output:

```
   91 ## The following errors have been detected:↴                                                                                                                                                                                                                                
   92   - ERROR: python(highlights): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 5813 for language python↴                                                                                                                     
   93     python(highlights) is concatenated from the following files:↴                                                                                                                                                                                                           
   94     | [ERROR]:"/home/xxx/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/python/highlights.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 5813 for language python↴              
   95 ↴ 
```

i just updated all plugins via `PackerSync`

**Comment by clason** [comment]
Not for me. Make sure you've updated the Python parser as well (remove and reinstall manually if needed).

**Comment by Shinzu** [comment]
not sure what you mean with `Python parser` in this case, im relatively new to neovim and its whole plugin system

**Comment by clason** [comment]
Then I would suggest reading up on things, and not using treesitter (which is still experimental) until you are familiar with the basics.

**Comment by Shinzu** [comment]
sure will do, solved it by `:TSUpdate all` for now

**Pull request merged**
