### PR TITLE
feat(cmake): dedent for all closing brackets

### PR DESCRIPTION
**Pull request by uyha**

### CODE REVIEW

**Review by amaanq — APPROVED** [review]

**Review by lucario387 — APPROVED** [review]
Seems intentional and doesn't break CMakeList.txt in neovim that much

**Comment by uyha** [comment]
what do you mean by “that much”? is something breaking?

**Comment by lucario387** [comment]
> what do you mean by “that much”? is something breaking?

as in I tried `gg=G` CMakeList.txt and the end result looks basically the same as before applying it. so lgtm

**Comment by uyha** [comment]
oh, ok, i thought something is breaking 😅

**Review by lucario387 — CHANGES_REQUESTED** [review]
https://github.com/nvim-treesitter/nvim-treesitter/blob/cfd42560c2c4db853521e4389bd3ebea59c2a257/queries/cmake/indents.scm#L12

Typo

**Review by lucario387 — APPROVED** [review]

**Pull request merged**
